/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to CXX Translator
  File name: QuestJoysticks.idl
  Source: QuestJoysticks.cpp
  Cyclone DDS: v0.10.2

*****************************************************************/
#include "QuestJoysticks.hpp"

namespace org{
namespace eclipse{
namespace cyclonedds{
namespace core{
namespace cdr{

template<>
propvec &get_type_props<::leju::msgs::QuestJoysticks>() {
  static thread_local std::mutex mtx;
  static thread_local propvec props;
  static thread_local entity_properties_t *props_end = nullptr;
  static thread_local std::atomic_bool initialized {false};
  key_endpoint keylist;
  if (initialized.load(std::memory_order_relaxed)) {
    auto ptr = props.data();
    while (ptr < props_end)
      (ptr++)->is_present = false;
    return props;
  }
  std::lock_guard<std::mutex> lock(mtx);
  if (initialized.load(std::memory_order_relaxed)) {
    auto ptr = props.data();
    while (ptr < props_end)
      (ptr++)->is_present = false;
    return props;
  }
  props.clear();

  props.push_back(entity_properties_t(0, 0, false, bb_unset, extensibility::ext_final));  //root
  props.push_back(entity_properties_t(1, 0, false, get_bit_bound<int32_t>(), extensibility::ext_final, false));  //::header_sec
  props.push_back(entity_properties_t(1, 1, false, get_bit_bound<uint32_t>(), extensibility::ext_final, false));  //::header_nanosec
  props.push_back(entity_properties_t(1, 2, false, get_bit_bound<float>(), extensibility::ext_final, false));  //::left_x
  props.push_back(entity_properties_t(1, 3, false, get_bit_bound<float>(), extensibility::ext_final, false));  //::left_y
  props.push_back(entity_properties_t(1, 4, false, get_bit_bound<float>(), extensibility::ext_final, false));  //::left_trigger
  props.push_back(entity_properties_t(1, 5, false, get_bit_bound<float>(), extensibility::ext_final, false));  //::left_grip
  props.push_back(entity_properties_t(1, 6, false, get_bit_bound<bool>(), extensibility::ext_final, false));  //::left_first_button_pressed
  props.push_back(entity_properties_t(1, 7, false, get_bit_bound<bool>(), extensibility::ext_final, false));  //::left_second_button_pressed
  props.push_back(entity_properties_t(1, 8, false, get_bit_bound<bool>(), extensibility::ext_final, false));  //::left_first_button_touched
  props.push_back(entity_properties_t(1, 9, false, get_bit_bound<bool>(), extensibility::ext_final, false));  //::left_second_button_touched
  props.push_back(entity_properties_t(1, 10, false, get_bit_bound<float>(), extensibility::ext_final, false));  //::right_x
  props.push_back(entity_properties_t(1, 11, false, get_bit_bound<float>(), extensibility::ext_final, false));  //::right_y
  props.push_back(entity_properties_t(1, 12, false, get_bit_bound<float>(), extensibility::ext_final, false));  //::right_trigger
  props.push_back(entity_properties_t(1, 13, false, get_bit_bound<float>(), extensibility::ext_final, false));  //::right_grip
  props.push_back(entity_properties_t(1, 14, false, get_bit_bound<bool>(), extensibility::ext_final, false));  //::right_first_button_pressed
  props.push_back(entity_properties_t(1, 15, false, get_bit_bound<bool>(), extensibility::ext_final, false));  //::right_second_button_pressed
  props.push_back(entity_properties_t(1, 16, false, get_bit_bound<bool>(), extensibility::ext_final, false));  //::right_first_button_touched
  props.push_back(entity_properties_t(1, 17, false, get_bit_bound<bool>(), extensibility::ext_final, false));  //::right_second_button_touched

  entity_properties_t::finish(props, keylist);
  props_end = props.data() + props.size();
  initialized.store(true, std::memory_order_release);
  return props;
}

} //namespace cdr
} //namespace core
} //namespace cyclonedds
} //namespace eclipse
} //namespace org

