loop_dt: 0.001
default_controller: "amp"

controllers:
  - name: "amp"
    type: "GenericRLController"
    config: "controllers/config_amp.yaml"
    enabled: true

  - name: "mimic_dance"
    type: "GenericRLController"
    config: "controllers/config_mimic_dance.yaml"
    enabled: true
