loop_dt: 0.001
default_controller: "mimic_dance"

controllers:
  - name: "amp"
    type: "GenericRLController"
    config: "controllers/config_amp.yaml"
    enabled: true

  - name: "mimic_dance"
    type: "GenericRLController"
    config: "controllers/config_mimic_dance.yaml"
    enabled: true

  # 实物未测试: 勿运行
  # - name: "mimic_yongchun"
  #   type: "GenericRLController"
  #   config: "controllers/config_mimic_yongchun.yaml"
  #   enabled: true
