HumanoidRobotCfg:
  loop_dt: 0.001
  policy_path: "policy/2025-12-24_15-03-24.onnx" # 相对于配置文件的路径
  motion_data_path: "motion_data/charleston_dance.csv"

  env:
    policy_dt: 0.02
    robot:
      residual_action: true
      joint_names: 
        ["waist_yaw_joint",
         "leg_l1_joint", "leg_l2_joint", "leg_l3_joint", "leg_l4_joint", "leg_l5_joint", "leg_l6_joint", 
         "leg_r1_joint", "leg_r2_joint", "leg_r3_joint", "leg_r4_joint", "leg_r5_joint", "leg_r6_joint", 
         "zarm_l1_joint", "zarm_l2_joint", "zarm_l3_joint", "zarm_l4_joint",
         "zarm_r1_joint", "zarm_r2_joint", "zarm_r3_joint", "zarm_r4_joint"]
      joint_direction:
        [-1.,
         1.,1.,1.,1.,1.,1.,
         1.,1.,1.,1.,1.,1.,
         1.,1.,1.,1.,
         1.,1.,1.,1.]
      joint_default_pos:
        [0.,
         -0.412, -0.0437, -0.287, 0.5, -0.2, 0.,
         0.412, 0.0437, 0.287, 0.5, -0.2, 0.,
         0.2, 0.16, -0.4, -0.5,
         0.2, -0.16, 0.4, -0.5,]
      joint_torque_limit:
        [65.,
         65., 65., 65., 65., 20., 20., 
         65., 65., 65., 65., 20., 20., 
         14.25, 14.25, 14.25, 14.25,
         14.25, 14.25, 14.25, 14.25,]
      actuator_kp:
        [40.179,
         40.179, 99.098, 40.179, 99.098, 14.250, 14.250, 
         40.179, 99.098, 40.179, 99.098, 14.250, 14.250, 
         14.25, 14.25, 14.25, 14.25, 
         14.25, 14.25, 14.25, 14.25, ]
      actuator_kd:
        [2.55,
         2.55, 6.30, 2.55, 6.30, 0.9, 0.9,
         2.55, 6.30, 2.55, 6.30, 0.9, 0.9,
         0.907, 0.907, 0.907, 0.907, 
         0.907, 0.907, 0.907, 0.907, ]
      actuator_control_mode:
        [0,
         0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 
        #  2, 2, 2, 2,
        #  2, 2, 2, 2,]
         0, 0, 0, 0,
         0, 0, 0, 0,]
      action_scale: 
        [0.404,
         0.404, 0.163, 0.404, 0.163, 0.350, 0.350,
         0.404, 0.163, 0.404, 0.163, 0.350, 0.350,
         0.263, 0.263, 0.263, 0.263,
         0.263, 0.263, 0.263, 0.263,]

    observations:
      history_length: 1
      stack_order: "classic" # classic
      terms:
        motion_command:
          scale: 1.
          clip: [-9999., 9999.]
        motion_target_height:
          scale: 1.
          clip: [-9999., 9999.]
        motion_anchor_ori_b:
          scale: 1.
          clip: [-9999., 9999.]
        projected_gravity:
          scale: 1.
          clip: [-9999., 9999.]
        base_ang_vel:
          scale: 1.
          clip: [-9999., 9999.]
        joint_pos:
          scale: 1.
          clip: [-9999., 9999.]
        joint_vel:
          scale: 1.
          clip: [-9999., 9999.]
        actions:
          scale: 1.
          clip: [-9999., 9999.]
        

