/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to CXX Translator
  File name: HandState.idl
  Source: HandState.hpp
  Cyclone DDS: v0.10.2

*****************************************************************/
#ifndef DDSCXX_HANDSTATE_HPP
#define DDSCXX_HANDSTATE_HPP

#include <cstdint>
#include <vector>

namespace leju
{
namespace msgs
{
class HandState
{
private:
 int32_t header_sec_ = 0;
 uint32_t header_nanosec_ = 0;
 bool left_valid_ = false;
 bool right_valid_ = false;
 uint32_t left_sample_age_ms_ = 0;
 uint32_t right_sample_age_ms_ = 0;
 std::vector<double> position_;
 std::vector<double> velocity_;
 std::vector<double> current_;
 std::vector<uint8_t> state_;

public:
  HandState() = default;

  explicit HandState(
    int32_t header_sec,
    uint32_t header_nanosec,
    bool left_valid,
    bool right_valid,
    uint32_t left_sample_age_ms,
    uint32_t right_sample_age_ms,
    const std::vector<double>& position,
    const std::vector<double>& velocity,
    const std::vector<double>& current,
    const std::vector<uint8_t>& state) :
    header_sec_(header_sec),
    header_nanosec_(header_nanosec),
    left_valid_(left_valid),
    right_valid_(right_valid),
    left_sample_age_ms_(left_sample_age_ms),
    right_sample_age_ms_(right_sample_age_ms),
    position_(position),
    velocity_(velocity),
    current_(current),
    state_(state) { }

  int32_t header_sec() const { return this->header_sec_; }
  int32_t& header_sec() { return this->header_sec_; }
  void header_sec(int32_t _val_) { this->header_sec_ = _val_; }
  uint32_t header_nanosec() const { return this->header_nanosec_; }
  uint32_t& header_nanosec() { return this->header_nanosec_; }
  void header_nanosec(uint32_t _val_) { this->header_nanosec_ = _val_; }
  bool left_valid() const { return this->left_valid_; }
  bool& left_valid() { return this->left_valid_; }
  void left_valid(bool _val_) { this->left_valid_ = _val_; }
  bool right_valid() const { return this->right_valid_; }
  bool& right_valid() { return this->right_valid_; }
  void right_valid(bool _val_) { this->right_valid_ = _val_; }
  uint32_t left_sample_age_ms() const { return this->left_sample_age_ms_; }
  uint32_t& left_sample_age_ms() { return this->left_sample_age_ms_; }
  void left_sample_age_ms(uint32_t _val_) { this->left_sample_age_ms_ = _val_; }
  uint32_t right_sample_age_ms() const { return this->right_sample_age_ms_; }
  uint32_t& right_sample_age_ms() { return this->right_sample_age_ms_; }
  void right_sample_age_ms(uint32_t _val_) { this->right_sample_age_ms_ = _val_; }
  const std::vector<double>& position() const { return this->position_; }
  std::vector<double>& position() { return this->position_; }
  void position(const std::vector<double>& _val_) { this->position_ = _val_; }
  void position(std::vector<double>&& _val_) { this->position_ = _val_; }
  const std::vector<double>& velocity() const { return this->velocity_; }
  std::vector<double>& velocity() { return this->velocity_; }
  void velocity(const std::vector<double>& _val_) { this->velocity_ = _val_; }
  void velocity(std::vector<double>&& _val_) { this->velocity_ = _val_; }
  const std::vector<double>& current() const { return this->current_; }
  std::vector<double>& current() { return this->current_; }
  void current(const std::vector<double>& _val_) { this->current_ = _val_; }
  void current(std::vector<double>&& _val_) { this->current_ = _val_; }
  const std::vector<uint8_t>& state() const { return this->state_; }
  std::vector<uint8_t>& state() { return this->state_; }
  void state(const std::vector<uint8_t>& _val_) { this->state_ = _val_; }
  void state(std::vector<uint8_t>&& _val_) { this->state_ = _val_; }

  bool operator==(const HandState& _other) const
  {
    (void) _other;
    return header_sec_ == _other.header_sec_ &&
      header_nanosec_ == _other.header_nanosec_ &&
      left_valid_ == _other.left_valid_ &&
      right_valid_ == _other.right_valid_ &&
      left_sample_age_ms_ == _other.left_sample_age_ms_ &&
      right_sample_age_ms_ == _other.right_sample_age_ms_ &&
      position_ == _other.position_ &&
      velocity_ == _other.velocity_ &&
      current_ == _other.current_ &&
      state_ == _other.state_;
  }

  bool operator!=(const HandState& _other) const
  {
    return !(*this == _other);
  }

};

}

}

#include "dds/topic/TopicTraits.hpp"
#include "org/eclipse/cyclonedds/topic/datatopic.hpp"

namespace org {
namespace eclipse {
namespace cyclonedds {
namespace topic {

template <> constexpr const char* TopicTraits<::leju::msgs::HandState>::getTypeName()
{
  return "leju::msgs::HandState";
}

template <> constexpr bool TopicTraits<::leju::msgs::HandState>::isSelfContained()
{
  return false;
}

template <> constexpr bool TopicTraits<::leju::msgs::HandState>::isKeyless()
{
  return true;
}

#ifdef DDSCXX_HAS_TYPE_DISCOVERY
template<> constexpr unsigned int TopicTraits<::leju::msgs::HandState>::type_map_blob_sz() { return 674; }
template<> constexpr unsigned int TopicTraits<::leju::msgs::HandState>::type_info_blob_sz() { return 100; }
template<> inline const uint8_t * TopicTraits<::leju::msgs::HandState>::type_map_blob() {
  static const uint8_t blob[] = {
 0xdc,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00,  0xf1,  0xd2,  0xc4,  0xc6,  0x44,  0xa3,  0x42,  0xae,
 0xd9,  0x24,  0xc4,  0x5d,  0x24,  0x2f,  0x1b,  0x00,  0xc4,  0x00,  0x00,  0x00,  0xf1,  0x51,  0x01,  0x00,
 0x01,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0xb4,  0x00,  0x00,  0x00,  0x0a,  0x00,  0x00,  0x00,
 0x0b,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x01,  0x00,  0x04,  0x8d,  0xe9,  0xf3,  0x63,  0x00,
 0x0b,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00,  0x01,  0x00,  0x07,  0x80,  0xf9,  0xcc,  0x35,  0x00,
 0x0b,  0x00,  0x00,  0x00,  0x02,  0x00,  0x00,  0x00,  0x01,  0x00,  0x01,  0x2c,  0x1e,  0xfd,  0x42,  0x00,
 0x0b,  0x00,  0x00,  0x00,  0x03,  0x00,  0x00,  0x00,  0x01,  0x00,  0x01,  0xe6,  0x19,  0xe2,  0xd7,  0x00,
 0x0b,  0x00,  0x00,  0x00,  0x04,  0x00,  0x00,  0x00,  0x01,  0x00,  0x07,  0x16,  0xf3,  0xaf,  0xdb,  0x00,
 0x0b,  0x00,  0x00,  0x00,  0x05,  0x00,  0x00,  0x00,  0x01,  0x00,  0x07,  0xdc,  0xb7,  0xaf,  0x5d,  0x00,
 0x10,  0x00,  0x00,  0x00,  0x06,  0x00,  0x00,  0x00,  0x01,  0x00,  0x80,  0xf3,  0x01,  0x00,  0x00,  0x0a,
 0x47,  0x57,  0xfe,  0x07,  0x10,  0x00,  0x00,  0x00,  0x07,  0x00,  0x00,  0x00,  0x01,  0x00,  0x80,  0xf3,
 0x01,  0x00,  0x00,  0x0a,  0xac,  0x1a,  0x45,  0x3d,  0x10,  0x00,  0x00,  0x00,  0x08,  0x00,  0x00,  0x00,
 0x01,  0x00,  0x80,  0xf3,  0x01,  0x00,  0x00,  0x0a,  0x43,  0xb5,  0xc9,  0x17,  0x10,  0x00,  0x00,  0x00,
 0x09,  0x00,  0x00,  0x00,  0x01,  0x00,  0x80,  0xf3,  0x01,  0x00,  0x00,  0x02,  0x9e,  0xd3,  0x9e,  0x2e,
 0x98,  0x01,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00,  0xf2,  0x0f,  0xa7,  0x8c,  0x02,  0x9b,  0xe9,  0x99,
 0x2f,  0xb1,  0xc9,  0x25,  0x90,  0x95,  0xcc,  0x00,  0x80,  0x01,  0x00,  0x00,  0xf2,  0x51,  0x01,  0x00,
 0x1e,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x16,  0x00,  0x00,  0x00,  0x6c,  0x65,  0x6a,  0x75,
 0x3a,  0x3a,  0x6d,  0x73,  0x67,  0x73,  0x3a,  0x3a,  0x48,  0x61,  0x6e,  0x64,  0x53,  0x74,  0x61,  0x74,
 0x65,  0x00,  0x00,  0x00,  0x54,  0x01,  0x00,  0x00,  0x0a,  0x00,  0x00,  0x00,  0x19,  0x00,  0x00,  0x00,
 0x00,  0x00,  0x00,  0x00,  0x01,  0x00,  0x04,  0x00,  0x0b,  0x00,  0x00,  0x00,  0x68,  0x65,  0x61,  0x64,
 0x65,  0x72,  0x5f,  0x73,  0x65,  0x63,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x1d,  0x00,  0x00,  0x00,
 0x01,  0x00,  0x00,  0x00,  0x01,  0x00,  0x07,  0x00,  0x0f,  0x00,  0x00,  0x00,  0x68,  0x65,  0x61,  0x64,
 0x65,  0x72,  0x5f,  0x6e,  0x61,  0x6e,  0x6f,  0x73,  0x65,  0x63,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,
 0x19,  0x00,  0x00,  0x00,  0x02,  0x00,  0x00,  0x00,  0x01,  0x00,  0x01,  0x00,  0x0b,  0x00,  0x00,  0x00,
 0x6c,  0x65,  0x66,  0x74,  0x5f,  0x76,  0x61,  0x6c,  0x69,  0x64,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,
 0x1a,  0x00,  0x00,  0x00,  0x03,  0x00,  0x00,  0x00,  0x01,  0x00,  0x01,  0x00,  0x0c,  0x00,  0x00,  0x00,
 0x72,  0x69,  0x67,  0x68,  0x74,  0x5f,  0x76,  0x61,  0x6c,  0x69,  0x64,  0x00,  0x00,  0x00,  0x00,  0x00,
 0x21,  0x00,  0x00,  0x00,  0x04,  0x00,  0x00,  0x00,  0x01,  0x00,  0x07,  0x00,  0x13,  0x00,  0x00,  0x00,
 0x6c,  0x65,  0x66,  0x74,  0x5f,  0x73,  0x61,  0x6d,  0x70,  0x6c,  0x65,  0x5f,  0x61,  0x67,  0x65,  0x5f,
 0x6d,  0x73,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x22,  0x00,  0x00,  0x00,  0x05,  0x00,  0x00,  0x00,
 0x01,  0x00,  0x07,  0x00,  0x14,  0x00,  0x00,  0x00,  0x72,  0x69,  0x67,  0x68,  0x74,  0x5f,  0x73,  0x61,
 0x6d,  0x70,  0x6c,  0x65,  0x5f,  0x61,  0x67,  0x65,  0x5f,  0x6d,  0x73,  0x00,  0x00,  0x00,  0x00,  0x00,
 0x1b,  0x00,  0x00,  0x00,  0x06,  0x00,  0x00,  0x00,  0x01,  0x00,  0x80,  0xf3,  0x01,  0x00,  0x00,  0x0a,
 0x09,  0x00,  0x00,  0x00,  0x70,  0x6f,  0x73,  0x69,  0x74,  0x69,  0x6f,  0x6e,  0x00,  0x00,  0x00,  0x00,
 0x1b,  0x00,  0x00,  0x00,  0x07,  0x00,  0x00,  0x00,  0x01,  0x00,  0x80,  0xf3,  0x01,  0x00,  0x00,  0x0a,
 0x09,  0x00,  0x00,  0x00,  0x76,  0x65,  0x6c,  0x6f,  0x63,  0x69,  0x74,  0x79,  0x00,  0x00,  0x00,  0x00,
 0x1a,  0x00,  0x00,  0x00,  0x08,  0x00,  0x00,  0x00,  0x01,  0x00,  0x80,  0xf3,  0x01,  0x00,  0x00,  0x0a,
 0x08,  0x00,  0x00,  0x00,  0x63,  0x75,  0x72,  0x72,  0x65,  0x6e,  0x74,  0x00,  0x00,  0x00,  0x00,  0x00,
 0x18,  0x00,  0x00,  0x00,  0x09,  0x00,  0x00,  0x00,  0x01,  0x00,  0x80,  0xf3,  0x01,  0x00,  0x00,  0x02,
 0x06,  0x00,  0x00,  0x00,  0x73,  0x74,  0x61,  0x74,  0x65,  0x00,  0x00,  0x00,  0x22,  0x00,  0x00,  0x00,
 0x01,  0x00,  0x00,  0x00,  0xf2,  0x0f,  0xa7,  0x8c,  0x02,  0x9b,  0xe9,  0x99,  0x2f,  0xb1,  0xc9,  0x25,
 0x90,  0x95,  0xcc,  0xf1,  0xd2,  0xc4,  0xc6,  0x44,  0xa3,  0x42,  0xae,  0xd9,  0x24,  0xc4,  0x5d,  0x24,
 0x2f,  0x1b, };
  return blob;
}
template<> inline const uint8_t * TopicTraits<::leju::msgs::HandState>::type_info_blob() {
  static const uint8_t blob[] = {
 0x60,  0x00,  0x00,  0x00,  0x01,  0x10,  0x00,  0x40,  0x28,  0x00,  0x00,  0x00,  0x24,  0x00,  0x00,  0x00,
 0x14,  0x00,  0x00,  0x00,  0xf1,  0xd2,  0xc4,  0xc6,  0x44,  0xa3,  0x42,  0xae,  0xd9,  0x24,  0xc4,  0x5d,
 0x24,  0x2f,  0x1b,  0x00,  0xc8,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x04,  0x00,  0x00,  0x00,
 0x00,  0x00,  0x00,  0x00,  0x02,  0x10,  0x00,  0x40,  0x28,  0x00,  0x00,  0x00,  0x24,  0x00,  0x00,  0x00,
 0x14,  0x00,  0x00,  0x00,  0xf2,  0x0f,  0xa7,  0x8c,  0x02,  0x9b,  0xe9,  0x99,  0x2f,  0xb1,  0xc9,  0x25,
 0x90,  0x95,  0xcc,  0x00,  0x84,  0x01,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x04,  0x00,  0x00,  0x00,
 0x00,  0x00,  0x00,  0x00, };
  return blob;
}
#endif //DDSCXX_HAS_TYPE_DISCOVERY

} //namespace topic
} //namespace cyclonedds
} //namespace eclipse
} //namespace org

namespace dds {
namespace topic {

template <>
struct topic_type_name<::leju::msgs::HandState>
{
    static std::string value()
    {
      return org::eclipse::cyclonedds::topic::TopicTraits<::leju::msgs::HandState>::getTypeName();
    }
};

}
}

REGISTER_TOPIC_TYPE(::leju::msgs::HandState)

namespace org{
namespace eclipse{
namespace cyclonedds{
namespace core{
namespace cdr{

template<>
propvec &get_type_props<::leju::msgs::HandState>();

template<typename T, std::enable_if_t<std::is_base_of<cdr_stream, T>::value, bool> = true >
bool write(T& streamer, const ::leju::msgs::HandState& instance, entity_properties_t *props) {
  (void)instance;
  if (!streamer.start_struct(*props))
    return false;
  auto prop = streamer.first_entity(props);
  while (prop) {
    switch (prop->m_id) {
      case 0:
      if (!streamer.start_member(*prop))
        return false;
      if (!write(streamer, instance.header_sec()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 1:
      if (!streamer.start_member(*prop))
        return false;
      if (!write(streamer, instance.header_nanosec()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 2:
      if (!streamer.start_member(*prop))
        return false;
      if (!write(streamer, instance.left_valid()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 3:
      if (!streamer.start_member(*prop))
        return false;
      if (!write(streamer, instance.right_valid()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 4:
      if (!streamer.start_member(*prop))
        return false;
      if (!write(streamer, instance.left_sample_age_ms()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 5:
      if (!streamer.start_member(*prop))
        return false;
      if (!write(streamer, instance.right_sample_age_ms()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 6:
      if (!streamer.start_member(*prop))
        return false;
      if (!streamer.start_consecutive(false, true))
        return false;
      {
      uint32_t se_1 = uint32_t(instance.position().size());
      if (!write(streamer, se_1))
        return false;
      if (se_1 > 0 &&
          !write(streamer, instance.position()[0], se_1))
        return false;
      }  //end sequence 1
      if (!streamer.finish_consecutive())
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 7:
      if (!streamer.start_member(*prop))
        return false;
      if (!streamer.start_consecutive(false, true))
        return false;
      {
      uint32_t se_1 = uint32_t(instance.velocity().size());
      if (!write(streamer, se_1))
        return false;
      if (se_1 > 0 &&
          !write(streamer, instance.velocity()[0], se_1))
        return false;
      }  //end sequence 1
      if (!streamer.finish_consecutive())
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 8:
      if (!streamer.start_member(*prop))
        return false;
      if (!streamer.start_consecutive(false, true))
        return false;
      {
      uint32_t se_1 = uint32_t(instance.current().size());
      if (!write(streamer, se_1))
        return false;
      if (se_1 > 0 &&
          !write(streamer, instance.current()[0], se_1))
        return false;
      }  //end sequence 1
      if (!streamer.finish_consecutive())
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 9:
      if (!streamer.start_member(*prop))
        return false;
      if (!streamer.start_consecutive(false, true))
        return false;
      {
      uint32_t se_1 = uint32_t(instance.state().size());
      if (!write(streamer, se_1))
        return false;
      if (se_1 > 0 &&
          !write(streamer, instance.state()[0], se_1))
        return false;
      }  //end sequence 1
      if (!streamer.finish_consecutive())
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
    }
    prop = streamer.next_entity(prop);
  }
  return streamer.finish_struct(*props);
}

template<typename S, std::enable_if_t<std::is_base_of<cdr_stream, S>::value, bool> = true >
bool write(S& str, const ::leju::msgs::HandState& instance, bool as_key) {
  auto &props = get_type_props<::leju::msgs::HandState>();
  str.set_mode(cdr_stream::stream_mode::write, as_key);
  return write(str, instance, props.data());
}

template<typename T, std::enable_if_t<std::is_base_of<cdr_stream, T>::value, bool> = true >
bool read(T& streamer, ::leju::msgs::HandState& instance, entity_properties_t *props) {
  (void)instance;
  if (!streamer.start_struct(*props))
    return false;
  auto prop = streamer.first_entity(props);
  while (prop) {
    switch (prop->m_id) {
      case 0:
      if (!streamer.start_member(*prop))
        return false;
      if (!read(streamer, instance.header_sec()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 1:
      if (!streamer.start_member(*prop))
        return false;
      if (!read(streamer, instance.header_nanosec()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 2:
      if (!streamer.start_member(*prop))
        return false;
      if (!read(streamer, instance.left_valid()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 3:
      if (!streamer.start_member(*prop))
        return false;
      if (!read(streamer, instance.right_valid()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 4:
      if (!streamer.start_member(*prop))
        return false;
      if (!read(streamer, instance.left_sample_age_ms()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 5:
      if (!streamer.start_member(*prop))
        return false;
      if (!read(streamer, instance.right_sample_age_ms()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 6:
      if (!streamer.start_member(*prop))
        return false;
      if (!streamer.start_consecutive(false, true))
        return false;
      {
      uint32_t se_1 = uint32_t(instance.position().size());
      if (!read(streamer, se_1))
        return false;
      instance.position().resize(se_1);
      if (se_1 > 0 &&
          !read(streamer, instance.position()[0], se_1))
        return false;
      }  //end sequence 1
      if (!streamer.finish_consecutive())
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 7:
      if (!streamer.start_member(*prop))
        return false;
      if (!streamer.start_consecutive(false, true))
        return false;
      {
      uint32_t se_1 = uint32_t(instance.velocity().size());
      if (!read(streamer, se_1))
        return false;
      instance.velocity().resize(se_1);
      if (se_1 > 0 &&
          !read(streamer, instance.velocity()[0], se_1))
        return false;
      }  //end sequence 1
      if (!streamer.finish_consecutive())
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 8:
      if (!streamer.start_member(*prop))
        return false;
      if (!streamer.start_consecutive(false, true))
        return false;
      {
      uint32_t se_1 = uint32_t(instance.current().size());
      if (!read(streamer, se_1))
        return false;
      instance.current().resize(se_1);
      if (se_1 > 0 &&
          !read(streamer, instance.current()[0], se_1))
        return false;
      }  //end sequence 1
      if (!streamer.finish_consecutive())
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 9:
      if (!streamer.start_member(*prop))
        return false;
      if (!streamer.start_consecutive(false, true))
        return false;
      {
      uint32_t se_1 = uint32_t(instance.state().size());
      if (!read(streamer, se_1))
        return false;
      instance.state().resize(se_1);
      if (se_1 > 0 &&
          !read(streamer, instance.state()[0], se_1))
        return false;
      }  //end sequence 1
      if (!streamer.finish_consecutive())
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
    }
    prop = streamer.next_entity(prop);
  }
  return streamer.finish_struct(*props);
}

template<typename S, std::enable_if_t<std::is_base_of<cdr_stream, S>::value, bool> = true >
bool read(S& str, ::leju::msgs::HandState& instance, bool as_key) {
  auto &props = get_type_props<::leju::msgs::HandState>();
  str.set_mode(cdr_stream::stream_mode::read, as_key);
  return read(str, instance, props.data());
}

template<typename T, std::enable_if_t<std::is_base_of<cdr_stream, T>::value, bool> = true >
bool move(T& streamer, const ::leju::msgs::HandState& instance, entity_properties_t *props) {
  (void)instance;
  if (!streamer.start_struct(*props))
    return false;
  auto prop = streamer.first_entity(props);
  while (prop) {
    switch (prop->m_id) {
      case 0:
      if (!streamer.start_member(*prop))
        return false;
      if (!move(streamer, instance.header_sec()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 1:
      if (!streamer.start_member(*prop))
        return false;
      if (!move(streamer, instance.header_nanosec()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 2:
      if (!streamer.start_member(*prop))
        return false;
      if (!move(streamer, instance.left_valid()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 3:
      if (!streamer.start_member(*prop))
        return false;
      if (!move(streamer, instance.right_valid()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 4:
      if (!streamer.start_member(*prop))
        return false;
      if (!move(streamer, instance.left_sample_age_ms()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 5:
      if (!streamer.start_member(*prop))
        return false;
      if (!move(streamer, instance.right_sample_age_ms()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 6:
      if (!streamer.start_member(*prop))
        return false;
      if (!streamer.start_consecutive(false, true))
        return false;
      {
      uint32_t se_1 = uint32_t(instance.position().size());
      if (!move(streamer, se_1))
        return false;
      if (se_1 > 0 &&
          !move(streamer, double(), se_1))
        return false;
      }  //end sequence 1
      if (!streamer.finish_consecutive())
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 7:
      if (!streamer.start_member(*prop))
        return false;
      if (!streamer.start_consecutive(false, true))
        return false;
      {
      uint32_t se_1 = uint32_t(instance.velocity().size());
      if (!move(streamer, se_1))
        return false;
      if (se_1 > 0 &&
          !move(streamer, double(), se_1))
        return false;
      }  //end sequence 1
      if (!streamer.finish_consecutive())
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 8:
      if (!streamer.start_member(*prop))
        return false;
      if (!streamer.start_consecutive(false, true))
        return false;
      {
      uint32_t se_1 = uint32_t(instance.current().size());
      if (!move(streamer, se_1))
        return false;
      if (se_1 > 0 &&
          !move(streamer, double(), se_1))
        return false;
      }  //end sequence 1
      if (!streamer.finish_consecutive())
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 9:
      if (!streamer.start_member(*prop))
        return false;
      if (!streamer.start_consecutive(false, true))
        return false;
      {
      uint32_t se_1 = uint32_t(instance.state().size());
      if (!move(streamer, se_1))
        return false;
      if (se_1 > 0 &&
          !move(streamer, uint8_t(), se_1))
        return false;
      }  //end sequence 1
      if (!streamer.finish_consecutive())
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
    }
    prop = streamer.next_entity(prop);
  }
  return streamer.finish_struct(*props);
}

template<typename S, std::enable_if_t<std::is_base_of<cdr_stream, S>::value, bool> = true >
bool move(S& str, const ::leju::msgs::HandState& instance, bool as_key) {
  auto &props = get_type_props<::leju::msgs::HandState>();
  str.set_mode(cdr_stream::stream_mode::move, as_key);
  return move(str, instance, props.data());
}

template<typename T, std::enable_if_t<std::is_base_of<cdr_stream, T>::value, bool> = true >
bool max(T& streamer, const ::leju::msgs::HandState& instance, entity_properties_t *props) {
  (void)instance;
  if (!streamer.start_struct(*props))
    return false;
  auto prop = streamer.first_entity(props);
  while (prop) {
    switch (prop->m_id) {
      case 0:
      if (!streamer.start_member(*prop))
        return false;
      if (!max(streamer, instance.header_sec()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 1:
      if (!streamer.start_member(*prop))
        return false;
      if (!max(streamer, instance.header_nanosec()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 2:
      if (!streamer.start_member(*prop))
        return false;
      if (!max(streamer, instance.left_valid()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 3:
      if (!streamer.start_member(*prop))
        return false;
      if (!max(streamer, instance.right_valid()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 4:
      if (!streamer.start_member(*prop))
        return false;
      if (!max(streamer, instance.left_sample_age_ms()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 5:
      if (!streamer.start_member(*prop))
        return false;
      if (!max(streamer, instance.right_sample_age_ms()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 6:
      if (!streamer.start_member(*prop))
        return false;
      if (!streamer.start_consecutive(false, true))
        return false;
      {
      uint32_t se_1 = 0;
      if (!max(streamer, se_1))
        return false;
      if (se_1 > 0 &&
          !max(streamer, double(), se_1))
        return false;
      }  //end sequence 1
      if (!streamer.finish_consecutive())
        return false;
      streamer.position(SIZE_MAX);
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 7:
      if (!streamer.start_member(*prop))
        return false;
      if (!streamer.start_consecutive(false, true))
        return false;
      {
      uint32_t se_1 = 0;
      if (!max(streamer, se_1))
        return false;
      if (se_1 > 0 &&
          !max(streamer, double(), se_1))
        return false;
      }  //end sequence 1
      if (!streamer.finish_consecutive())
        return false;
      streamer.position(SIZE_MAX);
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 8:
      if (!streamer.start_member(*prop))
        return false;
      if (!streamer.start_consecutive(false, true))
        return false;
      {
      uint32_t se_1 = 0;
      if (!max(streamer, se_1))
        return false;
      if (se_1 > 0 &&
          !max(streamer, double(), se_1))
        return false;
      }  //end sequence 1
      if (!streamer.finish_consecutive())
        return false;
      streamer.position(SIZE_MAX);
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 9:
      if (!streamer.start_member(*prop))
        return false;
      if (!streamer.start_consecutive(false, true))
        return false;
      {
      uint32_t se_1 = 0;
      if (!max(streamer, se_1))
        return false;
      if (se_1 > 0 &&
          !max(streamer, uint8_t(), se_1))
        return false;
      }  //end sequence 1
      if (!streamer.finish_consecutive())
        return false;
      streamer.position(SIZE_MAX);
      if (!streamer.finish_member(*prop))
        return false;
      break;
    }
    prop = streamer.next_entity(prop);
  }
  return streamer.finish_struct(*props);
}

template<typename S, std::enable_if_t<std::is_base_of<cdr_stream, S>::value, bool> = true >
bool max(S& str, const ::leju::msgs::HandState& instance, bool as_key) {
  auto &props = get_type_props<::leju::msgs::HandState>();
  str.set_mode(cdr_stream::stream_mode::max, as_key);
  return max(str, instance, props.data());
}

} //namespace cdr
} //namespace core
} //namespace cyclonedds
} //namespace eclipse
} //namespace org

#endif // DDSCXX_HANDSTATE_HPP
