/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to CXX Translator
  File name: JointState.idl
  Source: JointState.hpp
  Cyclone DDS: v0.10.2

*****************************************************************/
#ifndef DDSCXX_JOINTSTATE_HPP
#define DDSCXX_JOINTSTATE_HPP

#include <cstdint>
#include <vector>

namespace leju
{
namespace msgs
{
class JointState
{
private:
 int32_t header_sec_ = 0;
 uint32_t header_nanosec_ = 0;
 std::vector<double> q_;
 std::vector<double> v_;
 std::vector<double> vd_;
 std::vector<double> tau_;

public:
  JointState() = default;

  explicit JointState(
    int32_t header_sec,
    uint32_t header_nanosec,
    const std::vector<double>& q,
    const std::vector<double>& v,
    const std::vector<double>& vd,
    const std::vector<double>& tau) :
    header_sec_(header_sec),
    header_nanosec_(header_nanosec),
    q_(q),
    v_(v),
    vd_(vd),
    tau_(tau) { }

  int32_t header_sec() const { return this->header_sec_; }
  int32_t& header_sec() { return this->header_sec_; }
  void header_sec(int32_t _val_) { this->header_sec_ = _val_; }
  uint32_t header_nanosec() const { return this->header_nanosec_; }
  uint32_t& header_nanosec() { return this->header_nanosec_; }
  void header_nanosec(uint32_t _val_) { this->header_nanosec_ = _val_; }
  const std::vector<double>& q() const { return this->q_; }
  std::vector<double>& q() { return this->q_; }
  void q(const std::vector<double>& _val_) { this->q_ = _val_; }
  void q(std::vector<double>&& _val_) { this->q_ = _val_; }
  const std::vector<double>& v() const { return this->v_; }
  std::vector<double>& v() { return this->v_; }
  void v(const std::vector<double>& _val_) { this->v_ = _val_; }
  void v(std::vector<double>&& _val_) { this->v_ = _val_; }
  const std::vector<double>& vd() const { return this->vd_; }
  std::vector<double>& vd() { return this->vd_; }
  void vd(const std::vector<double>& _val_) { this->vd_ = _val_; }
  void vd(std::vector<double>&& _val_) { this->vd_ = _val_; }
  const std::vector<double>& tau() const { return this->tau_; }
  std::vector<double>& tau() { return this->tau_; }
  void tau(const std::vector<double>& _val_) { this->tau_ = _val_; }
  void tau(std::vector<double>&& _val_) { this->tau_ = _val_; }

  bool operator==(const JointState& _other) const
  {
    (void) _other;
    return header_sec_ == _other.header_sec_ &&
      header_nanosec_ == _other.header_nanosec_ &&
      q_ == _other.q_ &&
      v_ == _other.v_ &&
      vd_ == _other.vd_ &&
      tau_ == _other.tau_;
  }

  bool operator!=(const JointState& _other) const
  {
    return !(*this == _other);
  }

};

}

}

#include "dds/topic/TopicTraits.hpp"
#include "org/eclipse/cyclonedds/topic/datatopic.hpp"

namespace org {
namespace eclipse {
namespace cyclonedds {
namespace topic {

template <> constexpr const char* TopicTraits<::leju::msgs::JointState>::getTypeName()
{
  return "leju::msgs::JointState";
}

template <> constexpr bool TopicTraits<::leju::msgs::JointState>::isSelfContained()
{
  return false;
}

template <> constexpr bool TopicTraits<::leju::msgs::JointState>::isKeyless()
{
  return true;
}

#ifdef DDSCXX_HAS_TYPE_DISCOVERY
template<> constexpr unsigned int TopicTraits<::leju::msgs::JointState>::type_map_blob_sz() { return 446; }
template<> constexpr unsigned int TopicTraits<::leju::msgs::JointState>::type_info_blob_sz() { return 100; }
template<> inline const uint8_t * TopicTraits<::leju::msgs::JointState>::type_map_blob() {
  static const uint8_t blob[] = {
 0x9c,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00,  0xf1,  0x91,  0x67,  0x5d,  0x25,  0xd5,  0xb4,  0xc8, 
 0x44,  0xba,  0xe4,  0x69,  0x07,  0xf6,  0x33,  0x00,  0x84,  0x00,  0x00,  0x00,  0xf1,  0x51,  0x01,  0x00, 
 0x01,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x74,  0x00,  0x00,  0x00,  0x06,  0x00,  0x00,  0x00, 
 0x0b,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x01,  0x00,  0x04,  0x8d,  0xe9,  0xf3,  0x63,  0x00, 
 0x0b,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00,  0x01,  0x00,  0x07,  0x80,  0xf9,  0xcc,  0x35,  0x00, 
 0x10,  0x00,  0x00,  0x00,  0x02,  0x00,  0x00,  0x00,  0x01,  0x00,  0x80,  0xf3,  0x01,  0x00,  0x00,  0x0a, 
 0x76,  0x94,  0xf4,  0xa6,  0x10,  0x00,  0x00,  0x00,  0x03,  0x00,  0x00,  0x00,  0x01,  0x00,  0x80,  0xf3, 
 0x01,  0x00,  0x00,  0x0a,  0x9e,  0x36,  0x69,  0xd1,  0x10,  0x00,  0x00,  0x00,  0x04,  0x00,  0x00,  0x00, 
 0x01,  0x00,  0x80,  0xf3,  0x01,  0x00,  0x00,  0x0a,  0x8f,  0x7d,  0x15,  0xa8,  0x10,  0x00,  0x00,  0x00, 
 0x05,  0x00,  0x00,  0x00,  0x01,  0x00,  0x80,  0xf3,  0x01,  0x00,  0x00,  0x0a,  0x45,  0x80,  0xc2,  0x74, 
 0xf2,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00,  0xf2,  0x67,  0x87,  0x76,  0xaf,  0x40,  0x9b,  0xf2, 
 0x32,  0x6e,  0xeb,  0xbe,  0xf6,  0xe9,  0x33,  0x00,  0xda,  0x00,  0x00,  0x00,  0xf2,  0x51,  0x01,  0x00, 
 0x1f,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x17,  0x00,  0x00,  0x00,  0x6c,  0x65,  0x6a,  0x75, 
 0x3a,  0x3a,  0x6d,  0x73,  0x67,  0x73,  0x3a,  0x3a,  0x4a,  0x6f,  0x69,  0x6e,  0x74,  0x53,  0x74,  0x61, 
 0x74,  0x65,  0x00,  0x00,  0xae,  0x00,  0x00,  0x00,  0x06,  0x00,  0x00,  0x00,  0x19,  0x00,  0x00,  0x00, 
 0x00,  0x00,  0x00,  0x00,  0x01,  0x00,  0x04,  0x00,  0x0b,  0x00,  0x00,  0x00,  0x68,  0x65,  0x61,  0x64, 
 0x65,  0x72,  0x5f,  0x73,  0x65,  0x63,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x1d,  0x00,  0x00,  0x00, 
 0x01,  0x00,  0x00,  0x00,  0x01,  0x00,  0x07,  0x00,  0x0f,  0x00,  0x00,  0x00,  0x68,  0x65,  0x61,  0x64, 
 0x65,  0x72,  0x5f,  0x6e,  0x61,  0x6e,  0x6f,  0x73,  0x65,  0x63,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00, 
 0x14,  0x00,  0x00,  0x00,  0x02,  0x00,  0x00,  0x00,  0x01,  0x00,  0x80,  0xf3,  0x01,  0x00,  0x00,  0x0a, 
 0x02,  0x00,  0x00,  0x00,  0x71,  0x00,  0x00,  0x00,  0x14,  0x00,  0x00,  0x00,  0x03,  0x00,  0x00,  0x00, 
 0x01,  0x00,  0x80,  0xf3,  0x01,  0x00,  0x00,  0x0a,  0x02,  0x00,  0x00,  0x00,  0x76,  0x00,  0x00,  0x00, 
 0x15,  0x00,  0x00,  0x00,  0x04,  0x00,  0x00,  0x00,  0x01,  0x00,  0x80,  0xf3,  0x01,  0x00,  0x00,  0x0a, 
 0x03,  0x00,  0x00,  0x00,  0x76,  0x64,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x16,  0x00,  0x00,  0x00, 
 0x05,  0x00,  0x00,  0x00,  0x01,  0x00,  0x80,  0xf3,  0x01,  0x00,  0x00,  0x0a,  0x04,  0x00,  0x00,  0x00, 
 0x74,  0x61,  0x75,  0x00,  0x00,  0x00,  0x00,  0x00,  0x22,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00, 
 0xf2,  0x67,  0x87,  0x76,  0xaf,  0x40,  0x9b,  0xf2,  0x32,  0x6e,  0xeb,  0xbe,  0xf6,  0xe9,  0x33,  0xf1, 
 0x91,  0x67,  0x5d,  0x25,  0xd5,  0xb4,  0xc8,  0x44,  0xba,  0xe4,  0x69,  0x07,  0xf6,  0x33, };
  return blob;
}
template<> inline const uint8_t * TopicTraits<::leju::msgs::JointState>::type_info_blob() {
  static const uint8_t blob[] = {
 0x60,  0x00,  0x00,  0x00,  0x01,  0x10,  0x00,  0x40,  0x28,  0x00,  0x00,  0x00,  0x24,  0x00,  0x00,  0x00, 
 0x14,  0x00,  0x00,  0x00,  0xf1,  0x91,  0x67,  0x5d,  0x25,  0xd5,  0xb4,  0xc8,  0x44,  0xba,  0xe4,  0x69, 
 0x07,  0xf6,  0x33,  0x00,  0x88,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x04,  0x00,  0x00,  0x00, 
 0x00,  0x00,  0x00,  0x00,  0x02,  0x10,  0x00,  0x40,  0x28,  0x00,  0x00,  0x00,  0x24,  0x00,  0x00,  0x00, 
 0x14,  0x00,  0x00,  0x00,  0xf2,  0x67,  0x87,  0x76,  0xaf,  0x40,  0x9b,  0xf2,  0x32,  0x6e,  0xeb,  0xbe, 
 0xf6,  0xe9,  0x33,  0x00,  0xde,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x04,  0x00,  0x00,  0x00, 
 0x00,  0x00,  0x00,  0x00, };
  return blob;
}
#endif //DDSCXX_HAS_TYPE_DISCOVERY

} //namespace topic
} //namespace cyclonedds
} //namespace eclipse
} //namespace org

namespace dds {
namespace topic {

template <>
struct topic_type_name<::leju::msgs::JointState>
{
    static std::string value()
    {
      return org::eclipse::cyclonedds::topic::TopicTraits<::leju::msgs::JointState>::getTypeName();
    }
};

}
}

REGISTER_TOPIC_TYPE(::leju::msgs::JointState)

namespace org{
namespace eclipse{
namespace cyclonedds{
namespace core{
namespace cdr{

template<>
propvec &get_type_props<::leju::msgs::JointState>();

template<typename T, std::enable_if_t<std::is_base_of<cdr_stream, T>::value, bool> = true >
bool write(T& streamer, const ::leju::msgs::JointState& instance, entity_properties_t *props) {
  (void)instance;
  if (!streamer.start_struct(*props))
    return false;
  auto prop = streamer.first_entity(props);
  while (prop) {
    switch (prop->m_id) {
      case 0:
      if (!streamer.start_member(*prop))
        return false;
      if (!write(streamer, instance.header_sec()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 1:
      if (!streamer.start_member(*prop))
        return false;
      if (!write(streamer, instance.header_nanosec()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 2:
      if (!streamer.start_member(*prop))
        return false;
      if (!streamer.start_consecutive(false, true))
        return false;
      {
      uint32_t se_1 = uint32_t(instance.q().size());
      if (!write(streamer, se_1))
        return false;
      if (se_1 > 0 &&
          !write(streamer, instance.q()[0], se_1))
        return false;
      }  //end sequence 1
      if (!streamer.finish_consecutive())
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 3:
      if (!streamer.start_member(*prop))
        return false;
      if (!streamer.start_consecutive(false, true))
        return false;
      {
      uint32_t se_1 = uint32_t(instance.v().size());
      if (!write(streamer, se_1))
        return false;
      if (se_1 > 0 &&
          !write(streamer, instance.v()[0], se_1))
        return false;
      }  //end sequence 1
      if (!streamer.finish_consecutive())
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 4:
      if (!streamer.start_member(*prop))
        return false;
      if (!streamer.start_consecutive(false, true))
        return false;
      {
      uint32_t se_1 = uint32_t(instance.vd().size());
      if (!write(streamer, se_1))
        return false;
      if (se_1 > 0 &&
          !write(streamer, instance.vd()[0], se_1))
        return false;
      }  //end sequence 1
      if (!streamer.finish_consecutive())
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 5:
      if (!streamer.start_member(*prop))
        return false;
      if (!streamer.start_consecutive(false, true))
        return false;
      {
      uint32_t se_1 = uint32_t(instance.tau().size());
      if (!write(streamer, se_1))
        return false;
      if (se_1 > 0 &&
          !write(streamer, instance.tau()[0], se_1))
        return false;
      }  //end sequence 1
      if (!streamer.finish_consecutive())
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
    }
    prop = streamer.next_entity(prop);
  }
  return streamer.finish_struct(*props);
}

template<typename S, std::enable_if_t<std::is_base_of<cdr_stream, S>::value, bool> = true >
bool write(S& str, const ::leju::msgs::JointState& instance, bool as_key) {
  auto &props = get_type_props<::leju::msgs::JointState>();
  str.set_mode(cdr_stream::stream_mode::write, as_key);
  return write(str, instance, props.data()); 
}

template<typename T, std::enable_if_t<std::is_base_of<cdr_stream, T>::value, bool> = true >
bool read(T& streamer, ::leju::msgs::JointState& instance, entity_properties_t *props) {
  (void)instance;
  if (!streamer.start_struct(*props))
    return false;
  auto prop = streamer.first_entity(props);
  while (prop) {
    switch (prop->m_id) {
      case 0:
      if (!streamer.start_member(*prop))
        return false;
      if (!read(streamer, instance.header_sec()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 1:
      if (!streamer.start_member(*prop))
        return false;
      if (!read(streamer, instance.header_nanosec()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 2:
      if (!streamer.start_member(*prop))
        return false;
      if (!streamer.start_consecutive(false, true))
        return false;
      {
      uint32_t se_1 = uint32_t(instance.q().size());
      if (!read(streamer, se_1))
        return false;
      instance.q().resize(se_1);
      if (se_1 > 0 &&
          !read(streamer, instance.q()[0], se_1))
        return false;
      }  //end sequence 1
      if (!streamer.finish_consecutive())
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 3:
      if (!streamer.start_member(*prop))
        return false;
      if (!streamer.start_consecutive(false, true))
        return false;
      {
      uint32_t se_1 = uint32_t(instance.v().size());
      if (!read(streamer, se_1))
        return false;
      instance.v().resize(se_1);
      if (se_1 > 0 &&
          !read(streamer, instance.v()[0], se_1))
        return false;
      }  //end sequence 1
      if (!streamer.finish_consecutive())
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 4:
      if (!streamer.start_member(*prop))
        return false;
      if (!streamer.start_consecutive(false, true))
        return false;
      {
      uint32_t se_1 = uint32_t(instance.vd().size());
      if (!read(streamer, se_1))
        return false;
      instance.vd().resize(se_1);
      if (se_1 > 0 &&
          !read(streamer, instance.vd()[0], se_1))
        return false;
      }  //end sequence 1
      if (!streamer.finish_consecutive())
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 5:
      if (!streamer.start_member(*prop))
        return false;
      if (!streamer.start_consecutive(false, true))
        return false;
      {
      uint32_t se_1 = uint32_t(instance.tau().size());
      if (!read(streamer, se_1))
        return false;
      instance.tau().resize(se_1);
      if (se_1 > 0 &&
          !read(streamer, instance.tau()[0], se_1))
        return false;
      }  //end sequence 1
      if (!streamer.finish_consecutive())
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
    }
    prop = streamer.next_entity(prop);
  }
  return streamer.finish_struct(*props);
}

template<typename S, std::enable_if_t<std::is_base_of<cdr_stream, S>::value, bool> = true >
bool read(S& str, ::leju::msgs::JointState& instance, bool as_key) {
  auto &props = get_type_props<::leju::msgs::JointState>();
  str.set_mode(cdr_stream::stream_mode::read, as_key);
  return read(str, instance, props.data()); 
}

template<typename T, std::enable_if_t<std::is_base_of<cdr_stream, T>::value, bool> = true >
bool move(T& streamer, const ::leju::msgs::JointState& instance, entity_properties_t *props) {
  (void)instance;
  if (!streamer.start_struct(*props))
    return false;
  auto prop = streamer.first_entity(props);
  while (prop) {
    switch (prop->m_id) {
      case 0:
      if (!streamer.start_member(*prop))
        return false;
      if (!move(streamer, instance.header_sec()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 1:
      if (!streamer.start_member(*prop))
        return false;
      if (!move(streamer, instance.header_nanosec()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 2:
      if (!streamer.start_member(*prop))
        return false;
      if (!streamer.start_consecutive(false, true))
        return false;
      {
      uint32_t se_1 = uint32_t(instance.q().size());
      if (!move(streamer, se_1))
        return false;
      if (se_1 > 0 &&
          !move(streamer, double(), se_1))
        return false;
      }  //end sequence 1
      if (!streamer.finish_consecutive())
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 3:
      if (!streamer.start_member(*prop))
        return false;
      if (!streamer.start_consecutive(false, true))
        return false;
      {
      uint32_t se_1 = uint32_t(instance.v().size());
      if (!move(streamer, se_1))
        return false;
      if (se_1 > 0 &&
          !move(streamer, double(), se_1))
        return false;
      }  //end sequence 1
      if (!streamer.finish_consecutive())
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 4:
      if (!streamer.start_member(*prop))
        return false;
      if (!streamer.start_consecutive(false, true))
        return false;
      {
      uint32_t se_1 = uint32_t(instance.vd().size());
      if (!move(streamer, se_1))
        return false;
      if (se_1 > 0 &&
          !move(streamer, double(), se_1))
        return false;
      }  //end sequence 1
      if (!streamer.finish_consecutive())
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 5:
      if (!streamer.start_member(*prop))
        return false;
      if (!streamer.start_consecutive(false, true))
        return false;
      {
      uint32_t se_1 = uint32_t(instance.tau().size());
      if (!move(streamer, se_1))
        return false;
      if (se_1 > 0 &&
          !move(streamer, double(), se_1))
        return false;
      }  //end sequence 1
      if (!streamer.finish_consecutive())
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
    }
    prop = streamer.next_entity(prop);
  }
  return streamer.finish_struct(*props);
}

template<typename S, std::enable_if_t<std::is_base_of<cdr_stream, S>::value, bool> = true >
bool move(S& str, const ::leju::msgs::JointState& instance, bool as_key) {
  auto &props = get_type_props<::leju::msgs::JointState>();
  str.set_mode(cdr_stream::stream_mode::move, as_key);
  return move(str, instance, props.data()); 
}

template<typename T, std::enable_if_t<std::is_base_of<cdr_stream, T>::value, bool> = true >
bool max(T& streamer, const ::leju::msgs::JointState& instance, entity_properties_t *props) {
  (void)instance;
  if (!streamer.start_struct(*props))
    return false;
  auto prop = streamer.first_entity(props);
  while (prop) {
    switch (prop->m_id) {
      case 0:
      if (!streamer.start_member(*prop))
        return false;
      if (!max(streamer, instance.header_sec()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 1:
      if (!streamer.start_member(*prop))
        return false;
      if (!max(streamer, instance.header_nanosec()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 2:
      if (!streamer.start_member(*prop))
        return false;
      if (!streamer.start_consecutive(false, true))
        return false;
      {
      uint32_t se_1 = 0;
      if (!max(streamer, se_1))
        return false;
      if (se_1 > 0 &&
          !max(streamer, double(), se_1))
        return false;
      }  //end sequence 1
      if (!streamer.finish_consecutive())
        return false;
      streamer.position(SIZE_MAX);
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 3:
      if (!streamer.start_member(*prop))
        return false;
      if (!streamer.start_consecutive(false, true))
        return false;
      {
      uint32_t se_1 = 0;
      if (!max(streamer, se_1))
        return false;
      if (se_1 > 0 &&
          !max(streamer, double(), se_1))
        return false;
      }  //end sequence 1
      if (!streamer.finish_consecutive())
        return false;
      streamer.position(SIZE_MAX);
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 4:
      if (!streamer.start_member(*prop))
        return false;
      if (!streamer.start_consecutive(false, true))
        return false;
      {
      uint32_t se_1 = 0;
      if (!max(streamer, se_1))
        return false;
      if (se_1 > 0 &&
          !max(streamer, double(), se_1))
        return false;
      }  //end sequence 1
      if (!streamer.finish_consecutive())
        return false;
      streamer.position(SIZE_MAX);
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 5:
      if (!streamer.start_member(*prop))
        return false;
      if (!streamer.start_consecutive(false, true))
        return false;
      {
      uint32_t se_1 = 0;
      if (!max(streamer, se_1))
        return false;
      if (se_1 > 0 &&
          !max(streamer, double(), se_1))
        return false;
      }  //end sequence 1
      if (!streamer.finish_consecutive())
        return false;
      streamer.position(SIZE_MAX);
      if (!streamer.finish_member(*prop))
        return false;
      break;
    }
    prop = streamer.next_entity(prop);
  }
  return streamer.finish_struct(*props);
}

template<typename S, std::enable_if_t<std::is_base_of<cdr_stream, S>::value, bool> = true >
bool max(S& str, const ::leju::msgs::JointState& instance, bool as_key) {
  auto &props = get_type_props<::leju::msgs::JointState>();
  str.set_mode(cdr_stream::stream_mode::max, as_key);
  return max(str, instance, props.data()); 
}

} //namespace cdr
} //namespace core
} //namespace cyclonedds
} //namespace eclipse
} //namespace org

#endif // DDSCXX_JOINTSTATE_HPP
