/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to CXX Translator
  File name: QuestJoysticks.idl
  Source: QuestJoysticks.hpp
  Cyclone DDS: v0.10.2

*****************************************************************/
#ifndef DDSCXX_QUESTJOYSTICKS_HPP
#define DDSCXX_QUESTJOYSTICKS_HPP

#include <cstdint>

namespace leju
{
namespace msgs
{
class QuestJoysticks
{
private:
 int32_t header_sec_ = 0;
 uint32_t header_nanosec_ = 0;
 float left_x_ = 0.0f;
 float left_y_ = 0.0f;
 float left_trigger_ = 0.0f;
 float left_grip_ = 0.0f;
 bool left_first_button_pressed_ = false;
 bool left_second_button_pressed_ = false;
 bool left_first_button_touched_ = false;
 bool left_second_button_touched_ = false;
 float right_x_ = 0.0f;
 float right_y_ = 0.0f;
 float right_trigger_ = 0.0f;
 float right_grip_ = 0.0f;
 bool right_first_button_pressed_ = false;
 bool right_second_button_pressed_ = false;
 bool right_first_button_touched_ = false;
 bool right_second_button_touched_ = false;

public:
  QuestJoysticks() = default;

  explicit QuestJoysticks(
    int32_t header_sec,
    uint32_t header_nanosec,
    float left_x,
    float left_y,
    float left_trigger,
    float left_grip,
    bool left_first_button_pressed,
    bool left_second_button_pressed,
    bool left_first_button_touched,
    bool left_second_button_touched,
    float right_x,
    float right_y,
    float right_trigger,
    float right_grip,
    bool right_first_button_pressed,
    bool right_second_button_pressed,
    bool right_first_button_touched,
    bool right_second_button_touched) :
    header_sec_(header_sec),
    header_nanosec_(header_nanosec),
    left_x_(left_x),
    left_y_(left_y),
    left_trigger_(left_trigger),
    left_grip_(left_grip),
    left_first_button_pressed_(left_first_button_pressed),
    left_second_button_pressed_(left_second_button_pressed),
    left_first_button_touched_(left_first_button_touched),
    left_second_button_touched_(left_second_button_touched),
    right_x_(right_x),
    right_y_(right_y),
    right_trigger_(right_trigger),
    right_grip_(right_grip),
    right_first_button_pressed_(right_first_button_pressed),
    right_second_button_pressed_(right_second_button_pressed),
    right_first_button_touched_(right_first_button_touched),
    right_second_button_touched_(right_second_button_touched) { }

  int32_t header_sec() const { return this->header_sec_; }
  int32_t& header_sec() { return this->header_sec_; }
  void header_sec(int32_t _val_) { this->header_sec_ = _val_; }
  uint32_t header_nanosec() const { return this->header_nanosec_; }
  uint32_t& header_nanosec() { return this->header_nanosec_; }
  void header_nanosec(uint32_t _val_) { this->header_nanosec_ = _val_; }
  float left_x() const { return this->left_x_; }
  float& left_x() { return this->left_x_; }
  void left_x(float _val_) { this->left_x_ = _val_; }
  float left_y() const { return this->left_y_; }
  float& left_y() { return this->left_y_; }
  void left_y(float _val_) { this->left_y_ = _val_; }
  float left_trigger() const { return this->left_trigger_; }
  float& left_trigger() { return this->left_trigger_; }
  void left_trigger(float _val_) { this->left_trigger_ = _val_; }
  float left_grip() const { return this->left_grip_; }
  float& left_grip() { return this->left_grip_; }
  void left_grip(float _val_) { this->left_grip_ = _val_; }
  bool left_first_button_pressed() const { return this->left_first_button_pressed_; }
  bool& left_first_button_pressed() { return this->left_first_button_pressed_; }
  void left_first_button_pressed(bool _val_) { this->left_first_button_pressed_ = _val_; }
  bool left_second_button_pressed() const { return this->left_second_button_pressed_; }
  bool& left_second_button_pressed() { return this->left_second_button_pressed_; }
  void left_second_button_pressed(bool _val_) { this->left_second_button_pressed_ = _val_; }
  bool left_first_button_touched() const { return this->left_first_button_touched_; }
  bool& left_first_button_touched() { return this->left_first_button_touched_; }
  void left_first_button_touched(bool _val_) { this->left_first_button_touched_ = _val_; }
  bool left_second_button_touched() const { return this->left_second_button_touched_; }
  bool& left_second_button_touched() { return this->left_second_button_touched_; }
  void left_second_button_touched(bool _val_) { this->left_second_button_touched_ = _val_; }
  float right_x() const { return this->right_x_; }
  float& right_x() { return this->right_x_; }
  void right_x(float _val_) { this->right_x_ = _val_; }
  float right_y() const { return this->right_y_; }
  float& right_y() { return this->right_y_; }
  void right_y(float _val_) { this->right_y_ = _val_; }
  float right_trigger() const { return this->right_trigger_; }
  float& right_trigger() { return this->right_trigger_; }
  void right_trigger(float _val_) { this->right_trigger_ = _val_; }
  float right_grip() const { return this->right_grip_; }
  float& right_grip() { return this->right_grip_; }
  void right_grip(float _val_) { this->right_grip_ = _val_; }
  bool right_first_button_pressed() const { return this->right_first_button_pressed_; }
  bool& right_first_button_pressed() { return this->right_first_button_pressed_; }
  void right_first_button_pressed(bool _val_) { this->right_first_button_pressed_ = _val_; }
  bool right_second_button_pressed() const { return this->right_second_button_pressed_; }
  bool& right_second_button_pressed() { return this->right_second_button_pressed_; }
  void right_second_button_pressed(bool _val_) { this->right_second_button_pressed_ = _val_; }
  bool right_first_button_touched() const { return this->right_first_button_touched_; }
  bool& right_first_button_touched() { return this->right_first_button_touched_; }
  void right_first_button_touched(bool _val_) { this->right_first_button_touched_ = _val_; }
  bool right_second_button_touched() const { return this->right_second_button_touched_; }
  bool& right_second_button_touched() { return this->right_second_button_touched_; }
  void right_second_button_touched(bool _val_) { this->right_second_button_touched_ = _val_; }

  bool operator==(const QuestJoysticks& _other) const
  {
    (void) _other;
    return header_sec_ == _other.header_sec_ &&
      header_nanosec_ == _other.header_nanosec_ &&
      left_x_ == _other.left_x_ &&
      left_y_ == _other.left_y_ &&
      left_trigger_ == _other.left_trigger_ &&
      left_grip_ == _other.left_grip_ &&
      left_first_button_pressed_ == _other.left_first_button_pressed_ &&
      left_second_button_pressed_ == _other.left_second_button_pressed_ &&
      left_first_button_touched_ == _other.left_first_button_touched_ &&
      left_second_button_touched_ == _other.left_second_button_touched_ &&
      right_x_ == _other.right_x_ &&
      right_y_ == _other.right_y_ &&
      right_trigger_ == _other.right_trigger_ &&
      right_grip_ == _other.right_grip_ &&
      right_first_button_pressed_ == _other.right_first_button_pressed_ &&
      right_second_button_pressed_ == _other.right_second_button_pressed_ &&
      right_first_button_touched_ == _other.right_first_button_touched_ &&
      right_second_button_touched_ == _other.right_second_button_touched_;
  }

  bool operator!=(const QuestJoysticks& _other) const
  {
    return !(*this == _other);
  }

};

}

}

#include "dds/topic/TopicTraits.hpp"
#include "org/eclipse/cyclonedds/topic/datatopic.hpp"

namespace org {
namespace eclipse {
namespace cyclonedds {
namespace topic {

template <> constexpr const char* TopicTraits<::leju::msgs::QuestJoysticks>::getTypeName()
{
  return "leju::msgs::QuestJoysticks";
}

template <> constexpr bool TopicTraits<::leju::msgs::QuestJoysticks>::isKeyless()
{
  return true;
}

#ifdef DDSCXX_HAS_TYPE_DISCOVERY
template<> constexpr unsigned int TopicTraits<::leju::msgs::QuestJoysticks>::type_map_blob_sz() { return 1134; }
template<> constexpr unsigned int TopicTraits<::leju::msgs::QuestJoysticks>::type_info_blob_sz() { return 100; }
template<> inline const uint8_t * TopicTraits<::leju::msgs::QuestJoysticks>::type_map_blob() {
  static const uint8_t blob[] = {
 0x4b,  0x01,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00,  0xf1,  0xb0,  0xc2,  0x12,  0x55,  0x3d,  0x09,  0xec, 
 0x90,  0xd4,  0x46,  0x0c,  0x3a,  0x85,  0x8b,  0x00,  0x33,  0x01,  0x00,  0x00,  0xf1,  0x51,  0x01,  0x00, 
 0x01,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x23,  0x01,  0x00,  0x00,  0x12,  0x00,  0x00,  0x00, 
 0x0b,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x01,  0x00,  0x04,  0x8d,  0xe9,  0xf3,  0x63,  0x00, 
 0x0b,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00,  0x01,  0x00,  0x07,  0x80,  0xf9,  0xcc,  0x35,  0x00, 
 0x0b,  0x00,  0x00,  0x00,  0x02,  0x00,  0x00,  0x00,  0x01,  0x00,  0x09,  0x81,  0x7a,  0x2f,  0x18,  0x00, 
 0x0b,  0x00,  0x00,  0x00,  0x03,  0x00,  0x00,  0x00,  0x01,  0x00,  0x09,  0x86,  0x07,  0x07,  0xea,  0x00, 
 0x0b,  0x00,  0x00,  0x00,  0x04,  0x00,  0x00,  0x00,  0x01,  0x00,  0x09,  0x05,  0xa0,  0xf5,  0xec,  0x00, 
 0x0b,  0x00,  0x00,  0x00,  0x05,  0x00,  0x00,  0x00,  0x01,  0x00,  0x09,  0xce,  0x9a,  0x8c,  0xc4,  0x00, 
 0x0b,  0x00,  0x00,  0x00,  0x06,  0x00,  0x00,  0x00,  0x01,  0x00,  0x01,  0xbd,  0xa1,  0x26,  0xaa,  0x00, 
 0x0b,  0x00,  0x00,  0x00,  0x07,  0x00,  0x00,  0x00,  0x01,  0x00,  0x01,  0x07,  0x28,  0xf7,  0x63,  0x00, 
 0x0b,  0x00,  0x00,  0x00,  0x08,  0x00,  0x00,  0x00,  0x01,  0x00,  0x01,  0x3f,  0x1c,  0xe3,  0x3c,  0x00, 
 0x0b,  0x00,  0x00,  0x00,  0x09,  0x00,  0x00,  0x00,  0x01,  0x00,  0x01,  0x6d,  0x19,  0x41,  0x25,  0x00, 
 0x0b,  0x00,  0x00,  0x00,  0x0a,  0x00,  0x00,  0x00,  0x01,  0x00,  0x09,  0x4c,  0x2a,  0x93,  0x5b,  0x00, 
 0x0b,  0x00,  0x00,  0x00,  0x0b,  0x00,  0x00,  0x00,  0x01,  0x00,  0x09,  0x2a,  0x4c,  0x0d,  0x09,  0x00, 
 0x0b,  0x00,  0x00,  0x00,  0x0c,  0x00,  0x00,  0x00,  0x01,  0x00,  0x09,  0x2c,  0x2a,  0x76,  0xf1,  0x00, 
 0x0b,  0x00,  0x00,  0x00,  0x0d,  0x00,  0x00,  0x00,  0x01,  0x00,  0x09,  0xde,  0xb0,  0x27,  0xf7,  0x00, 
 0x0b,  0x00,  0x00,  0x00,  0x0e,  0x00,  0x00,  0x00,  0x01,  0x00,  0x01,  0x76,  0x59,  0xe0,  0x8b,  0x00, 
 0x0b,  0x00,  0x00,  0x00,  0x0f,  0x00,  0x00,  0x00,  0x01,  0x00,  0x01,  0x7d,  0xc3,  0x92,  0xcc,  0x00, 
 0x0b,  0x00,  0x00,  0x00,  0x10,  0x00,  0x00,  0x00,  0x01,  0x00,  0x01,  0x15,  0xca,  0x5b,  0x56,  0x00, 
 0x0b,  0x00,  0x00,  0x00,  0x11,  0x00,  0x00,  0x00,  0x01,  0x00,  0x01,  0x32,  0x0c,  0x05,  0xf2,  0x00, 
 0xf2,  0x02,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00,  0xf2,  0xd1,  0x32,  0x8d,  0x33,  0xe5,  0x1d,  0x79, 
 0x2f,  0xe6,  0x0e,  0x61,  0x05,  0x05,  0xf0,  0x00,  0xda,  0x02,  0x00,  0x00,  0xf2,  0x51,  0x01,  0x00, 
 0x23,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x1b,  0x00,  0x00,  0x00,  0x6c,  0x65,  0x6a,  0x75, 
 0x3a,  0x3a,  0x6d,  0x73,  0x67,  0x73,  0x3a,  0x3a,  0x51,  0x75,  0x65,  0x73,  0x74,  0x4a,  0x6f,  0x79, 
 0x73,  0x74,  0x69,  0x63,  0x6b,  0x73,  0x00,  0x00,  0xaa,  0x02,  0x00,  0x00,  0x12,  0x00,  0x00,  0x00, 
 0x19,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x01,  0x00,  0x04,  0x00,  0x0b,  0x00,  0x00,  0x00, 
 0x68,  0x65,  0x61,  0x64,  0x65,  0x72,  0x5f,  0x73,  0x65,  0x63,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00, 
 0x1d,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00,  0x01,  0x00,  0x07,  0x00,  0x0f,  0x00,  0x00,  0x00, 
 0x68,  0x65,  0x61,  0x64,  0x65,  0x72,  0x5f,  0x6e,  0x61,  0x6e,  0x6f,  0x73,  0x65,  0x63,  0x00,  0x00, 
 0x00,  0x00,  0x00,  0x00,  0x15,  0x00,  0x00,  0x00,  0x02,  0x00,  0x00,  0x00,  0x01,  0x00,  0x09,  0x00, 
 0x07,  0x00,  0x00,  0x00,  0x6c,  0x65,  0x66,  0x74,  0x5f,  0x78,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00, 
 0x15,  0x00,  0x00,  0x00,  0x03,  0x00,  0x00,  0x00,  0x01,  0x00,  0x09,  0x00,  0x07,  0x00,  0x00,  0x00, 
 0x6c,  0x65,  0x66,  0x74,  0x5f,  0x79,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x1b,  0x00,  0x00,  0x00, 
 0x04,  0x00,  0x00,  0x00,  0x01,  0x00,  0x09,  0x00,  0x0d,  0x00,  0x00,  0x00,  0x6c,  0x65,  0x66,  0x74, 
 0x5f,  0x74,  0x72,  0x69,  0x67,  0x67,  0x65,  0x72,  0x00,  0x00,  0x00,  0x00,  0x18,  0x00,  0x00,  0x00, 
 0x05,  0x00,  0x00,  0x00,  0x01,  0x00,  0x09,  0x00,  0x0a,  0x00,  0x00,  0x00,  0x6c,  0x65,  0x66,  0x74, 
 0x5f,  0x67,  0x72,  0x69,  0x70,  0x00,  0x00,  0x00,  0x28,  0x00,  0x00,  0x00,  0x06,  0x00,  0x00,  0x00, 
 0x01,  0x00,  0x01,  0x00,  0x1a,  0x00,  0x00,  0x00,  0x6c,  0x65,  0x66,  0x74,  0x5f,  0x66,  0x69,  0x72, 
 0x73,  0x74,  0x5f,  0x62,  0x75,  0x74,  0x74,  0x6f,  0x6e,  0x5f,  0x70,  0x72,  0x65,  0x73,  0x73,  0x65, 
 0x64,  0x00,  0x00,  0x00,  0x29,  0x00,  0x00,  0x00,  0x07,  0x00,  0x00,  0x00,  0x01,  0x00,  0x01,  0x00, 
 0x1b,  0x00,  0x00,  0x00,  0x6c,  0x65,  0x66,  0x74,  0x5f,  0x73,  0x65,  0x63,  0x6f,  0x6e,  0x64,  0x5f, 
 0x62,  0x75,  0x74,  0x74,  0x6f,  0x6e,  0x5f,  0x70,  0x72,  0x65,  0x73,  0x73,  0x65,  0x64,  0x00,  0x00, 
 0x00,  0x00,  0x00,  0x00,  0x28,  0x00,  0x00,  0x00,  0x08,  0x00,  0x00,  0x00,  0x01,  0x00,  0x01,  0x00, 
 0x1a,  0x00,  0x00,  0x00,  0x6c,  0x65,  0x66,  0x74,  0x5f,  0x66,  0x69,  0x72,  0x73,  0x74,  0x5f,  0x62, 
 0x75,  0x74,  0x74,  0x6f,  0x6e,  0x5f,  0x74,  0x6f,  0x75,  0x63,  0x68,  0x65,  0x64,  0x00,  0x00,  0x00, 
 0x29,  0x00,  0x00,  0x00,  0x09,  0x00,  0x00,  0x00,  0x01,  0x00,  0x01,  0x00,  0x1b,  0x00,  0x00,  0x00, 
 0x6c,  0x65,  0x66,  0x74,  0x5f,  0x73,  0x65,  0x63,  0x6f,  0x6e,  0x64,  0x5f,  0x62,  0x75,  0x74,  0x74, 
 0x6f,  0x6e,  0x5f,  0x74,  0x6f,  0x75,  0x63,  0x68,  0x65,  0x64,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00, 
 0x16,  0x00,  0x00,  0x00,  0x0a,  0x00,  0x00,  0x00,  0x01,  0x00,  0x09,  0x00,  0x08,  0x00,  0x00,  0x00, 
 0x72,  0x69,  0x67,  0x68,  0x74,  0x5f,  0x78,  0x00,  0x00,  0x00,  0x00,  0x00,  0x16,  0x00,  0x00,  0x00, 
 0x0b,  0x00,  0x00,  0x00,  0x01,  0x00,  0x09,  0x00,  0x08,  0x00,  0x00,  0x00,  0x72,  0x69,  0x67,  0x68, 
 0x74,  0x5f,  0x79,  0x00,  0x00,  0x00,  0x00,  0x00,  0x1c,  0x00,  0x00,  0x00,  0x0c,  0x00,  0x00,  0x00, 
 0x01,  0x00,  0x09,  0x00,  0x0e,  0x00,  0x00,  0x00,  0x72,  0x69,  0x67,  0x68,  0x74,  0x5f,  0x74,  0x72, 
 0x69,  0x67,  0x67,  0x65,  0x72,  0x00,  0x00,  0x00,  0x19,  0x00,  0x00,  0x00,  0x0d,  0x00,  0x00,  0x00, 
 0x01,  0x00,  0x09,  0x00,  0x0b,  0x00,  0x00,  0x00,  0x72,  0x69,  0x67,  0x68,  0x74,  0x5f,  0x67,  0x72, 
 0x69,  0x70,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x29,  0x00,  0x00,  0x00,  0x0e,  0x00,  0x00,  0x00, 
 0x01,  0x00,  0x01,  0x00,  0x1b,  0x00,  0x00,  0x00,  0x72,  0x69,  0x67,  0x68,  0x74,  0x5f,  0x66,  0x69, 
 0x72,  0x73,  0x74,  0x5f,  0x62,  0x75,  0x74,  0x74,  0x6f,  0x6e,  0x5f,  0x70,  0x72,  0x65,  0x73,  0x73, 
 0x65,  0x64,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x2a,  0x00,  0x00,  0x00,  0x0f,  0x00,  0x00,  0x00, 
 0x01,  0x00,  0x01,  0x00,  0x1c,  0x00,  0x00,  0x00,  0x72,  0x69,  0x67,  0x68,  0x74,  0x5f,  0x73,  0x65, 
 0x63,  0x6f,  0x6e,  0x64,  0x5f,  0x62,  0x75,  0x74,  0x74,  0x6f,  0x6e,  0x5f,  0x70,  0x72,  0x65,  0x73, 
 0x73,  0x65,  0x64,  0x00,  0x00,  0x00,  0x00,  0x00,  0x29,  0x00,  0x00,  0x00,  0x10,  0x00,  0x00,  0x00, 
 0x01,  0x00,  0x01,  0x00,  0x1b,  0x00,  0x00,  0x00,  0x72,  0x69,  0x67,  0x68,  0x74,  0x5f,  0x66,  0x69, 
 0x72,  0x73,  0x74,  0x5f,  0x62,  0x75,  0x74,  0x74,  0x6f,  0x6e,  0x5f,  0x74,  0x6f,  0x75,  0x63,  0x68, 
 0x65,  0x64,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x2a,  0x00,  0x00,  0x00,  0x11,  0x00,  0x00,  0x00, 
 0x01,  0x00,  0x01,  0x00,  0x1c,  0x00,  0x00,  0x00,  0x72,  0x69,  0x67,  0x68,  0x74,  0x5f,  0x73,  0x65, 
 0x63,  0x6f,  0x6e,  0x64,  0x5f,  0x62,  0x75,  0x74,  0x74,  0x6f,  0x6e,  0x5f,  0x74,  0x6f,  0x75,  0x63, 
 0x68,  0x65,  0x64,  0x00,  0x00,  0x00,  0x00,  0x00,  0x22,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00, 
 0xf2,  0xd1,  0x32,  0x8d,  0x33,  0xe5,  0x1d,  0x79,  0x2f,  0xe6,  0x0e,  0x61,  0x05,  0x05,  0xf0,  0xf1, 
 0xb0,  0xc2,  0x12,  0x55,  0x3d,  0x09,  0xec,  0x90,  0xd4,  0x46,  0x0c,  0x3a,  0x85,  0x8b, };
  return blob;
}
template<> inline const uint8_t * TopicTraits<::leju::msgs::QuestJoysticks>::type_info_blob() {
  static const uint8_t blob[] = {
 0x60,  0x00,  0x00,  0x00,  0x01,  0x10,  0x00,  0x40,  0x28,  0x00,  0x00,  0x00,  0x24,  0x00,  0x00,  0x00, 
 0x14,  0x00,  0x00,  0x00,  0xf1,  0xb0,  0xc2,  0x12,  0x55,  0x3d,  0x09,  0xec,  0x90,  0xd4,  0x46,  0x0c, 
 0x3a,  0x85,  0x8b,  0x00,  0x37,  0x01,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x04,  0x00,  0x00,  0x00, 
 0x00,  0x00,  0x00,  0x00,  0x02,  0x10,  0x00,  0x40,  0x28,  0x00,  0x00,  0x00,  0x24,  0x00,  0x00,  0x00, 
 0x14,  0x00,  0x00,  0x00,  0xf2,  0xd1,  0x32,  0x8d,  0x33,  0xe5,  0x1d,  0x79,  0x2f,  0xe6,  0x0e,  0x61, 
 0x05,  0x05,  0xf0,  0x00,  0xde,  0x02,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x04,  0x00,  0x00,  0x00, 
 0x00,  0x00,  0x00,  0x00, };
  return blob;
}
#endif //DDSCXX_HAS_TYPE_DISCOVERY

} //namespace topic
} //namespace cyclonedds
} //namespace eclipse
} //namespace org

namespace dds {
namespace topic {

template <>
struct topic_type_name<::leju::msgs::QuestJoysticks>
{
    static std::string value()
    {
      return org::eclipse::cyclonedds::topic::TopicTraits<::leju::msgs::QuestJoysticks>::getTypeName();
    }
};

}
}

REGISTER_TOPIC_TYPE(::leju::msgs::QuestJoysticks)

namespace org{
namespace eclipse{
namespace cyclonedds{
namespace core{
namespace cdr{

template<>
propvec &get_type_props<::leju::msgs::QuestJoysticks>();

template<typename T, std::enable_if_t<std::is_base_of<cdr_stream, T>::value, bool> = true >
bool write(T& streamer, const ::leju::msgs::QuestJoysticks& instance, entity_properties_t *props) {
  (void)instance;
  if (!streamer.start_struct(*props))
    return false;
  auto prop = streamer.first_entity(props);
  while (prop) {
    switch (prop->m_id) {
      case 0:
      if (!streamer.start_member(*prop))
        return false;
      if (!write(streamer, instance.header_sec()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 1:
      if (!streamer.start_member(*prop))
        return false;
      if (!write(streamer, instance.header_nanosec()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 2:
      if (!streamer.start_member(*prop))
        return false;
      if (!write(streamer, instance.left_x()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 3:
      if (!streamer.start_member(*prop))
        return false;
      if (!write(streamer, instance.left_y()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 4:
      if (!streamer.start_member(*prop))
        return false;
      if (!write(streamer, instance.left_trigger()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 5:
      if (!streamer.start_member(*prop))
        return false;
      if (!write(streamer, instance.left_grip()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 6:
      if (!streamer.start_member(*prop))
        return false;
      if (!write(streamer, instance.left_first_button_pressed()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 7:
      if (!streamer.start_member(*prop))
        return false;
      if (!write(streamer, instance.left_second_button_pressed()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 8:
      if (!streamer.start_member(*prop))
        return false;
      if (!write(streamer, instance.left_first_button_touched()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 9:
      if (!streamer.start_member(*prop))
        return false;
      if (!write(streamer, instance.left_second_button_touched()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 10:
      if (!streamer.start_member(*prop))
        return false;
      if (!write(streamer, instance.right_x()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 11:
      if (!streamer.start_member(*prop))
        return false;
      if (!write(streamer, instance.right_y()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 12:
      if (!streamer.start_member(*prop))
        return false;
      if (!write(streamer, instance.right_trigger()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 13:
      if (!streamer.start_member(*prop))
        return false;
      if (!write(streamer, instance.right_grip()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 14:
      if (!streamer.start_member(*prop))
        return false;
      if (!write(streamer, instance.right_first_button_pressed()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 15:
      if (!streamer.start_member(*prop))
        return false;
      if (!write(streamer, instance.right_second_button_pressed()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 16:
      if (!streamer.start_member(*prop))
        return false;
      if (!write(streamer, instance.right_first_button_touched()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 17:
      if (!streamer.start_member(*prop))
        return false;
      if (!write(streamer, instance.right_second_button_touched()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
    }
    prop = streamer.next_entity(prop);
  }
  return streamer.finish_struct(*props);
}

template<typename S, std::enable_if_t<std::is_base_of<cdr_stream, S>::value, bool> = true >
bool write(S& str, const ::leju::msgs::QuestJoysticks& instance, bool as_key) {
  auto &props = get_type_props<::leju::msgs::QuestJoysticks>();
  str.set_mode(cdr_stream::stream_mode::write, as_key);
  return write(str, instance, props.data()); 
}

template<typename T, std::enable_if_t<std::is_base_of<cdr_stream, T>::value, bool> = true >
bool read(T& streamer, ::leju::msgs::QuestJoysticks& instance, entity_properties_t *props) {
  (void)instance;
  if (!streamer.start_struct(*props))
    return false;
  auto prop = streamer.first_entity(props);
  while (prop) {
    switch (prop->m_id) {
      case 0:
      if (!streamer.start_member(*prop))
        return false;
      if (!read(streamer, instance.header_sec()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 1:
      if (!streamer.start_member(*prop))
        return false;
      if (!read(streamer, instance.header_nanosec()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 2:
      if (!streamer.start_member(*prop))
        return false;
      if (!read(streamer, instance.left_x()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 3:
      if (!streamer.start_member(*prop))
        return false;
      if (!read(streamer, instance.left_y()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 4:
      if (!streamer.start_member(*prop))
        return false;
      if (!read(streamer, instance.left_trigger()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 5:
      if (!streamer.start_member(*prop))
        return false;
      if (!read(streamer, instance.left_grip()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 6:
      if (!streamer.start_member(*prop))
        return false;
      if (!read(streamer, instance.left_first_button_pressed()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 7:
      if (!streamer.start_member(*prop))
        return false;
      if (!read(streamer, instance.left_second_button_pressed()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 8:
      if (!streamer.start_member(*prop))
        return false;
      if (!read(streamer, instance.left_first_button_touched()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 9:
      if (!streamer.start_member(*prop))
        return false;
      if (!read(streamer, instance.left_second_button_touched()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 10:
      if (!streamer.start_member(*prop))
        return false;
      if (!read(streamer, instance.right_x()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 11:
      if (!streamer.start_member(*prop))
        return false;
      if (!read(streamer, instance.right_y()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 12:
      if (!streamer.start_member(*prop))
        return false;
      if (!read(streamer, instance.right_trigger()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 13:
      if (!streamer.start_member(*prop))
        return false;
      if (!read(streamer, instance.right_grip()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 14:
      if (!streamer.start_member(*prop))
        return false;
      if (!read(streamer, instance.right_first_button_pressed()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 15:
      if (!streamer.start_member(*prop))
        return false;
      if (!read(streamer, instance.right_second_button_pressed()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 16:
      if (!streamer.start_member(*prop))
        return false;
      if (!read(streamer, instance.right_first_button_touched()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 17:
      if (!streamer.start_member(*prop))
        return false;
      if (!read(streamer, instance.right_second_button_touched()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
    }
    prop = streamer.next_entity(prop);
  }
  return streamer.finish_struct(*props);
}

template<typename S, std::enable_if_t<std::is_base_of<cdr_stream, S>::value, bool> = true >
bool read(S& str, ::leju::msgs::QuestJoysticks& instance, bool as_key) {
  auto &props = get_type_props<::leju::msgs::QuestJoysticks>();
  str.set_mode(cdr_stream::stream_mode::read, as_key);
  return read(str, instance, props.data()); 
}

template<typename T, std::enable_if_t<std::is_base_of<cdr_stream, T>::value, bool> = true >
bool move(T& streamer, const ::leju::msgs::QuestJoysticks& instance, entity_properties_t *props) {
  (void)instance;
  if (!streamer.start_struct(*props))
    return false;
  auto prop = streamer.first_entity(props);
  while (prop) {
    switch (prop->m_id) {
      case 0:
      if (!streamer.start_member(*prop))
        return false;
      if (!move(streamer, instance.header_sec()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 1:
      if (!streamer.start_member(*prop))
        return false;
      if (!move(streamer, instance.header_nanosec()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 2:
      if (!streamer.start_member(*prop))
        return false;
      if (!move(streamer, instance.left_x()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 3:
      if (!streamer.start_member(*prop))
        return false;
      if (!move(streamer, instance.left_y()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 4:
      if (!streamer.start_member(*prop))
        return false;
      if (!move(streamer, instance.left_trigger()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 5:
      if (!streamer.start_member(*prop))
        return false;
      if (!move(streamer, instance.left_grip()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 6:
      if (!streamer.start_member(*prop))
        return false;
      if (!move(streamer, instance.left_first_button_pressed()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 7:
      if (!streamer.start_member(*prop))
        return false;
      if (!move(streamer, instance.left_second_button_pressed()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 8:
      if (!streamer.start_member(*prop))
        return false;
      if (!move(streamer, instance.left_first_button_touched()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 9:
      if (!streamer.start_member(*prop))
        return false;
      if (!move(streamer, instance.left_second_button_touched()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 10:
      if (!streamer.start_member(*prop))
        return false;
      if (!move(streamer, instance.right_x()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 11:
      if (!streamer.start_member(*prop))
        return false;
      if (!move(streamer, instance.right_y()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 12:
      if (!streamer.start_member(*prop))
        return false;
      if (!move(streamer, instance.right_trigger()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 13:
      if (!streamer.start_member(*prop))
        return false;
      if (!move(streamer, instance.right_grip()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 14:
      if (!streamer.start_member(*prop))
        return false;
      if (!move(streamer, instance.right_first_button_pressed()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 15:
      if (!streamer.start_member(*prop))
        return false;
      if (!move(streamer, instance.right_second_button_pressed()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 16:
      if (!streamer.start_member(*prop))
        return false;
      if (!move(streamer, instance.right_first_button_touched()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 17:
      if (!streamer.start_member(*prop))
        return false;
      if (!move(streamer, instance.right_second_button_touched()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
    }
    prop = streamer.next_entity(prop);
  }
  return streamer.finish_struct(*props);
}

template<typename S, std::enable_if_t<std::is_base_of<cdr_stream, S>::value, bool> = true >
bool move(S& str, const ::leju::msgs::QuestJoysticks& instance, bool as_key) {
  auto &props = get_type_props<::leju::msgs::QuestJoysticks>();
  str.set_mode(cdr_stream::stream_mode::move, as_key);
  return move(str, instance, props.data()); 
}

template<typename T, std::enable_if_t<std::is_base_of<cdr_stream, T>::value, bool> = true >
bool max(T& streamer, const ::leju::msgs::QuestJoysticks& instance, entity_properties_t *props) {
  (void)instance;
  if (!streamer.start_struct(*props))
    return false;
  auto prop = streamer.first_entity(props);
  while (prop) {
    switch (prop->m_id) {
      case 0:
      if (!streamer.start_member(*prop))
        return false;
      if (!max(streamer, instance.header_sec()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 1:
      if (!streamer.start_member(*prop))
        return false;
      if (!max(streamer, instance.header_nanosec()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 2:
      if (!streamer.start_member(*prop))
        return false;
      if (!max(streamer, instance.left_x()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 3:
      if (!streamer.start_member(*prop))
        return false;
      if (!max(streamer, instance.left_y()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 4:
      if (!streamer.start_member(*prop))
        return false;
      if (!max(streamer, instance.left_trigger()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 5:
      if (!streamer.start_member(*prop))
        return false;
      if (!max(streamer, instance.left_grip()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 6:
      if (!streamer.start_member(*prop))
        return false;
      if (!max(streamer, instance.left_first_button_pressed()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 7:
      if (!streamer.start_member(*prop))
        return false;
      if (!max(streamer, instance.left_second_button_pressed()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 8:
      if (!streamer.start_member(*prop))
        return false;
      if (!max(streamer, instance.left_first_button_touched()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 9:
      if (!streamer.start_member(*prop))
        return false;
      if (!max(streamer, instance.left_second_button_touched()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 10:
      if (!streamer.start_member(*prop))
        return false;
      if (!max(streamer, instance.right_x()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 11:
      if (!streamer.start_member(*prop))
        return false;
      if (!max(streamer, instance.right_y()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 12:
      if (!streamer.start_member(*prop))
        return false;
      if (!max(streamer, instance.right_trigger()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 13:
      if (!streamer.start_member(*prop))
        return false;
      if (!max(streamer, instance.right_grip()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 14:
      if (!streamer.start_member(*prop))
        return false;
      if (!max(streamer, instance.right_first_button_pressed()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 15:
      if (!streamer.start_member(*prop))
        return false;
      if (!max(streamer, instance.right_second_button_pressed()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 16:
      if (!streamer.start_member(*prop))
        return false;
      if (!max(streamer, instance.right_first_button_touched()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 17:
      if (!streamer.start_member(*prop))
        return false;
      if (!max(streamer, instance.right_second_button_touched()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
    }
    prop = streamer.next_entity(prop);
  }
  return streamer.finish_struct(*props);
}

template<typename S, std::enable_if_t<std::is_base_of<cdr_stream, S>::value, bool> = true >
bool max(S& str, const ::leju::msgs::QuestJoysticks& instance, bool as_key) {
  auto &props = get_type_props<::leju::msgs::QuestJoysticks>();
  str.set_mode(cdr_stream::stream_mode::max, as_key);
  return max(str, instance, props.data()); 
}

} //namespace cdr
} //namespace core
} //namespace cyclonedds
} //namespace eclipse
} //namespace org

#endif // DDSCXX_QUESTJOYSTICKS_HPP
