/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to CXX Translator
  File name: QuestBonePoses.idl
  Source: QuestBonePoses.hpp
  Cyclone DDS: v0.10.2

*****************************************************************/
#ifndef DDSCXX_QUESTBONEPOSES_HPP
#define DDSCXX_QUESTBONEPOSES_HPP

#include <cstdint>
#include <vector>

namespace leju
{
namespace msgs
{
class Pose
{
private:
 float x_ = 0.0f;
 float y_ = 0.0f;
 float z_ = 0.0f;
 float qx_ = 0.0f;
 float qy_ = 0.0f;
 float qz_ = 0.0f;
 float qw_ = 0.0f;

public:
  Pose() = default;

  explicit Pose(
    float x,
    float y,
    float z,
    float qx,
    float qy,
    float qz,
    float qw) :
    x_(x),
    y_(y),
    z_(z),
    qx_(qx),
    qy_(qy),
    qz_(qz),
    qw_(qw) { }

  float x() const { return this->x_; }
  float& x() { return this->x_; }
  void x(float _val_) { this->x_ = _val_; }
  float y() const { return this->y_; }
  float& y() { return this->y_; }
  void y(float _val_) { this->y_ = _val_; }
  float z() const { return this->z_; }
  float& z() { return this->z_; }
  void z(float _val_) { this->z_ = _val_; }
  float qx() const { return this->qx_; }
  float& qx() { return this->qx_; }
  void qx(float _val_) { this->qx_ = _val_; }
  float qy() const { return this->qy_; }
  float& qy() { return this->qy_; }
  void qy(float _val_) { this->qy_ = _val_; }
  float qz() const { return this->qz_; }
  float& qz() { return this->qz_; }
  void qz(float _val_) { this->qz_ = _val_; }
  float qw() const { return this->qw_; }
  float& qw() { return this->qw_; }
  void qw(float _val_) { this->qw_ = _val_; }

  bool operator==(const Pose& _other) const
  {
    (void) _other;
    return x_ == _other.x_ &&
      y_ == _other.y_ &&
      z_ == _other.z_ &&
      qx_ == _other.qx_ &&
      qy_ == _other.qy_ &&
      qz_ == _other.qz_ &&
      qw_ == _other.qw_;
  }

  bool operator!=(const Pose& _other) const
  {
    return !(*this == _other);
  }

};

class QuestBonePoses
{
private:
 int32_t header_sec_ = 0;
 uint32_t header_nanosec_ = 0;
 int64_t timestamp_ms_ = 0;
 bool is_high_confidence_ = false;
 bool is_hand_tracking_ = false;
 std::vector<::leju::msgs::Pose> poses_;

public:
  QuestBonePoses() = default;

  explicit QuestBonePoses(
    int32_t header_sec,
    uint32_t header_nanosec,
    int64_t timestamp_ms,
    bool is_high_confidence,
    bool is_hand_tracking,
    const std::vector<::leju::msgs::Pose>& poses) :
    header_sec_(header_sec),
    header_nanosec_(header_nanosec),
    timestamp_ms_(timestamp_ms),
    is_high_confidence_(is_high_confidence),
    is_hand_tracking_(is_hand_tracking),
    poses_(poses) { }

  int32_t header_sec() const { return this->header_sec_; }
  int32_t& header_sec() { return this->header_sec_; }
  void header_sec(int32_t _val_) { this->header_sec_ = _val_; }
  uint32_t header_nanosec() const { return this->header_nanosec_; }
  uint32_t& header_nanosec() { return this->header_nanosec_; }
  void header_nanosec(uint32_t _val_) { this->header_nanosec_ = _val_; }
  int64_t timestamp_ms() const { return this->timestamp_ms_; }
  int64_t& timestamp_ms() { return this->timestamp_ms_; }
  void timestamp_ms(int64_t _val_) { this->timestamp_ms_ = _val_; }
  bool is_high_confidence() const { return this->is_high_confidence_; }
  bool& is_high_confidence() { return this->is_high_confidence_; }
  void is_high_confidence(bool _val_) { this->is_high_confidence_ = _val_; }
  bool is_hand_tracking() const { return this->is_hand_tracking_; }
  bool& is_hand_tracking() { return this->is_hand_tracking_; }
  void is_hand_tracking(bool _val_) { this->is_hand_tracking_ = _val_; }
  const std::vector<::leju::msgs::Pose>& poses() const { return this->poses_; }
  std::vector<::leju::msgs::Pose>& poses() { return this->poses_; }
  void poses(const std::vector<::leju::msgs::Pose>& _val_) { this->poses_ = _val_; }
  void poses(std::vector<::leju::msgs::Pose>&& _val_) { this->poses_ = _val_; }

  bool operator==(const QuestBonePoses& _other) const
  {
    (void) _other;
    return header_sec_ == _other.header_sec_ &&
      header_nanosec_ == _other.header_nanosec_ &&
      timestamp_ms_ == _other.timestamp_ms_ &&
      is_high_confidence_ == _other.is_high_confidence_ &&
      is_hand_tracking_ == _other.is_hand_tracking_ &&
      poses_ == _other.poses_;
  }

  bool operator!=(const QuestBonePoses& _other) const
  {
    return !(*this == _other);
  }

};

}

}

#include "dds/topic/TopicTraits.hpp"
#include "org/eclipse/cyclonedds/topic/datatopic.hpp"

namespace org {
namespace eclipse {
namespace cyclonedds {
namespace topic {

template <> constexpr const char* TopicTraits<::leju::msgs::Pose>::getTypeName()
{
  return "leju::msgs::Pose";
}

template <> constexpr bool TopicTraits<::leju::msgs::Pose>::isKeyless()
{
  return true;
}

#ifdef DDSCXX_HAS_TYPE_DISCOVERY
template<> constexpr unsigned int TopicTraits<::leju::msgs::Pose>::type_map_blob_sz() { return 426; }
template<> constexpr unsigned int TopicTraits<::leju::msgs::Pose>::type_info_blob_sz() { return 100; }
template<> inline const uint8_t * TopicTraits<::leju::msgs::Pose>::type_map_blob() {
  static const uint8_t blob[] = {
 0x9b,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00,  0xf1,  0x3f,  0x9d,  0x21,  0x0d,  0x9b,  0xd5,  0x07, 
 0x7d,  0xeb,  0xee,  0x3e,  0x47,  0x67,  0x90,  0x00,  0x83,  0x00,  0x00,  0x00,  0xf1,  0x51,  0x01,  0x00, 
 0x01,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x73,  0x00,  0x00,  0x00,  0x07,  0x00,  0x00,  0x00, 
 0x0b,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x01,  0x00,  0x09,  0x9d,  0xd4,  0xe4,  0x61,  0x00, 
 0x0b,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00,  0x01,  0x00,  0x09,  0x41,  0x52,  0x90,  0x76,  0x00, 
 0x0b,  0x00,  0x00,  0x00,  0x02,  0x00,  0x00,  0x00,  0x01,  0x00,  0x09,  0xfb,  0xad,  0xe9,  0xe3,  0x00, 
 0x0b,  0x00,  0x00,  0x00,  0x03,  0x00,  0x00,  0x00,  0x01,  0x00,  0x09,  0x80,  0x30,  0xaa,  0xc3,  0x00, 
 0x0b,  0x00,  0x00,  0x00,  0x04,  0x00,  0x00,  0x00,  0x01,  0x00,  0x09,  0x28,  0x3a,  0xaf,  0x75,  0x00, 
 0x0b,  0x00,  0x00,  0x00,  0x05,  0x00,  0x00,  0x00,  0x01,  0x00,  0x09,  0x38,  0x79,  0x18,  0x63,  0x00, 
 0x0b,  0x00,  0x00,  0x00,  0x06,  0x00,  0x00,  0x00,  0x01,  0x00,  0x09,  0x00,  0x6d,  0x21,  0x43,  0x00, 
 0xdd,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00,  0xf2,  0xa9,  0x39,  0xf5,  0x4b,  0x7f,  0x48,  0x9d, 
 0x43,  0x66,  0xbb,  0x79,  0xbe,  0xe0,  0x0d,  0x00,  0xc5,  0x00,  0x00,  0x00,  0xf2,  0x51,  0x01,  0x00, 
 0x19,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x11,  0x00,  0x00,  0x00,  0x6c,  0x65,  0x6a,  0x75, 
 0x3a,  0x3a,  0x6d,  0x73,  0x67,  0x73,  0x3a,  0x3a,  0x50,  0x6f,  0x73,  0x65,  0x00,  0x00,  0x00,  0x00, 
 0x9d,  0x00,  0x00,  0x00,  0x07,  0x00,  0x00,  0x00,  0x10,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00, 
 0x01,  0x00,  0x09,  0x00,  0x02,  0x00,  0x00,  0x00,  0x78,  0x00,  0x00,  0x00,  0x10,  0x00,  0x00,  0x00, 
 0x01,  0x00,  0x00,  0x00,  0x01,  0x00,  0x09,  0x00,  0x02,  0x00,  0x00,  0x00,  0x79,  0x00,  0x00,  0x00, 
 0x10,  0x00,  0x00,  0x00,  0x02,  0x00,  0x00,  0x00,  0x01,  0x00,  0x09,  0x00,  0x02,  0x00,  0x00,  0x00, 
 0x7a,  0x00,  0x00,  0x00,  0x11,  0x00,  0x00,  0x00,  0x03,  0x00,  0x00,  0x00,  0x01,  0x00,  0x09,  0x00, 
 0x03,  0x00,  0x00,  0x00,  0x71,  0x78,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x11,  0x00,  0x00,  0x00, 
 0x04,  0x00,  0x00,  0x00,  0x01,  0x00,  0x09,  0x00,  0x03,  0x00,  0x00,  0x00,  0x71,  0x79,  0x00,  0x00, 
 0x00,  0x00,  0x00,  0x00,  0x11,  0x00,  0x00,  0x00,  0x05,  0x00,  0x00,  0x00,  0x01,  0x00,  0x09,  0x00, 
 0x03,  0x00,  0x00,  0x00,  0x71,  0x7a,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x11,  0x00,  0x00,  0x00, 
 0x06,  0x00,  0x00,  0x00,  0x01,  0x00,  0x09,  0x00,  0x03,  0x00,  0x00,  0x00,  0x71,  0x77,  0x00,  0x00, 
 0x00,  0x00,  0x00,  0x00,  0x22,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00,  0xf2,  0xa9,  0x39,  0xf5, 
 0x4b,  0x7f,  0x48,  0x9d,  0x43,  0x66,  0xbb,  0x79,  0xbe,  0xe0,  0x0d,  0xf1,  0x3f,  0x9d,  0x21,  0x0d, 
 0x9b,  0xd5,  0x07,  0x7d,  0xeb,  0xee,  0x3e,  0x47,  0x67,  0x90, };
  return blob;
}
template<> inline const uint8_t * TopicTraits<::leju::msgs::Pose>::type_info_blob() {
  static const uint8_t blob[] = {
 0x60,  0x00,  0x00,  0x00,  0x01,  0x10,  0x00,  0x40,  0x28,  0x00,  0x00,  0x00,  0x24,  0x00,  0x00,  0x00, 
 0x14,  0x00,  0x00,  0x00,  0xf1,  0x3f,  0x9d,  0x21,  0x0d,  0x9b,  0xd5,  0x07,  0x7d,  0xeb,  0xee,  0x3e, 
 0x47,  0x67,  0x90,  0x00,  0x87,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x04,  0x00,  0x00,  0x00, 
 0x00,  0x00,  0x00,  0x00,  0x02,  0x10,  0x00,  0x40,  0x28,  0x00,  0x00,  0x00,  0x24,  0x00,  0x00,  0x00, 
 0x14,  0x00,  0x00,  0x00,  0xf2,  0xa9,  0x39,  0xf5,  0x4b,  0x7f,  0x48,  0x9d,  0x43,  0x66,  0xbb,  0x79, 
 0xbe,  0xe0,  0x0d,  0x00,  0xc9,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x04,  0x00,  0x00,  0x00, 
 0x00,  0x00,  0x00,  0x00, };
  return blob;
}
#endif //DDSCXX_HAS_TYPE_DISCOVERY

template <> constexpr const char* TopicTraits<::leju::msgs::QuestBonePoses>::getTypeName()
{
  return "leju::msgs::QuestBonePoses";
}

template <> constexpr bool TopicTraits<::leju::msgs::QuestBonePoses>::isSelfContained()
{
  return false;
}

template <> constexpr bool TopicTraits<::leju::msgs::QuestBonePoses>::isKeyless()
{
  return true;
}

#ifdef DDSCXX_HAS_TYPE_DISCOVERY
template<> constexpr unsigned int TopicTraits<::leju::msgs::QuestBonePoses>::type_map_blob_sz() { return 904; }
template<> constexpr unsigned int TopicTraits<::leju::msgs::QuestBonePoses>::type_info_blob_sz() { return 148; }
template<> inline const uint8_t * TopicTraits<::leju::msgs::QuestBonePoses>::type_map_blob() {
  static const uint8_t blob[] = {
 0x37,  0x01,  0x00,  0x00,  0x02,  0x00,  0x00,  0x00,  0xf1,  0x7f,  0x2a,  0xf7,  0xaa,  0xcf,  0xf4,  0x52, 
 0xf4,  0x00,  0xe5,  0x6e,  0xc8,  0xd5,  0x5f,  0x00,  0x86,  0x00,  0x00,  0x00,  0xf1,  0x51,  0x01,  0x00, 
 0x01,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x76,  0x00,  0x00,  0x00,  0x06,  0x00,  0x00,  0x00, 
 0x0b,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x01,  0x00,  0x04,  0x8d,  0xe9,  0xf3,  0x63,  0x00, 
 0x0b,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00,  0x01,  0x00,  0x07,  0x80,  0xf9,  0xcc,  0x35,  0x00, 
 0x0b,  0x00,  0x00,  0x00,  0x02,  0x00,  0x00,  0x00,  0x01,  0x00,  0x05,  0x73,  0xf4,  0x70,  0xb7,  0x00, 
 0x0b,  0x00,  0x00,  0x00,  0x03,  0x00,  0x00,  0x00,  0x01,  0x00,  0x01,  0x50,  0x37,  0x45,  0xdc,  0x00, 
 0x0b,  0x00,  0x00,  0x00,  0x04,  0x00,  0x00,  0x00,  0x01,  0x00,  0x01,  0xe1,  0x41,  0xc2,  0x95,  0x00, 
 0x1e,  0x00,  0x00,  0x00,  0x05,  0x00,  0x00,  0x00,  0x01,  0x00,  0x80,  0xf1,  0x01,  0x00,  0x00,  0xf1, 
 0x3f,  0x9d,  0x21,  0x0d,  0x9b,  0xd5,  0x07,  0x7d,  0xeb,  0xee,  0x3e,  0x47,  0x67,  0x90,  0x3d,  0xe5, 
 0x6b,  0x84,  0xf1,  0x3f,  0x9d,  0x21,  0x0d,  0x9b,  0xd5,  0x07,  0x7d,  0xeb,  0xee,  0x3e,  0x47,  0x67, 
 0x90,  0x00,  0x00,  0x00,  0x83,  0x00,  0x00,  0x00,  0xf1,  0x51,  0x01,  0x00,  0x01,  0x00,  0x00,  0x00, 
 0x00,  0x00,  0x00,  0x00,  0x73,  0x00,  0x00,  0x00,  0x07,  0x00,  0x00,  0x00,  0x0b,  0x00,  0x00,  0x00, 
 0x00,  0x00,  0x00,  0x00,  0x01,  0x00,  0x09,  0x9d,  0xd4,  0xe4,  0x61,  0x00,  0x0b,  0x00,  0x00,  0x00, 
 0x01,  0x00,  0x00,  0x00,  0x01,  0x00,  0x09,  0x41,  0x52,  0x90,  0x76,  0x00,  0x0b,  0x00,  0x00,  0x00, 
 0x02,  0x00,  0x00,  0x00,  0x01,  0x00,  0x09,  0xfb,  0xad,  0xe9,  0xe3,  0x00,  0x0b,  0x00,  0x00,  0x00, 
 0x03,  0x00,  0x00,  0x00,  0x01,  0x00,  0x09,  0x80,  0x30,  0xaa,  0xc3,  0x00,  0x0b,  0x00,  0x00,  0x00, 
 0x04,  0x00,  0x00,  0x00,  0x01,  0x00,  0x09,  0x28,  0x3a,  0xaf,  0x75,  0x00,  0x0b,  0x00,  0x00,  0x00, 
 0x05,  0x00,  0x00,  0x00,  0x01,  0x00,  0x09,  0x38,  0x79,  0x18,  0x63,  0x00,  0x0b,  0x00,  0x00,  0x00, 
 0x06,  0x00,  0x00,  0x00,  0x01,  0x00,  0x09,  0x00,  0x6d,  0x21,  0x43,  0x00,  0x01,  0x02,  0x00,  0x00, 
 0x02,  0x00,  0x00,  0x00,  0xf2,  0xcb,  0x14,  0xe1,  0xd1,  0xcc,  0x1f,  0x99,  0x58,  0xce,  0xc9,  0xc3, 
 0x9f,  0xbe,  0x17,  0x00,  0x10,  0x01,  0x00,  0x00,  0xf2,  0x51,  0x01,  0x00,  0x23,  0x00,  0x00,  0x00, 
 0x00,  0x00,  0x00,  0x00,  0x1b,  0x00,  0x00,  0x00,  0x6c,  0x65,  0x6a,  0x75,  0x3a,  0x3a,  0x6d,  0x73, 
 0x67,  0x73,  0x3a,  0x3a,  0x51,  0x75,  0x65,  0x73,  0x74,  0x42,  0x6f,  0x6e,  0x65,  0x50,  0x6f,  0x73, 
 0x65,  0x73,  0x00,  0x00,  0xe0,  0x00,  0x00,  0x00,  0x06,  0x00,  0x00,  0x00,  0x19,  0x00,  0x00,  0x00, 
 0x00,  0x00,  0x00,  0x00,  0x01,  0x00,  0x04,  0x00,  0x0b,  0x00,  0x00,  0x00,  0x68,  0x65,  0x61,  0x64, 
 0x65,  0x72,  0x5f,  0x73,  0x65,  0x63,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x1d,  0x00,  0x00,  0x00, 
 0x01,  0x00,  0x00,  0x00,  0x01,  0x00,  0x07,  0x00,  0x0f,  0x00,  0x00,  0x00,  0x68,  0x65,  0x61,  0x64, 
 0x65,  0x72,  0x5f,  0x6e,  0x61,  0x6e,  0x6f,  0x73,  0x65,  0x63,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00, 
 0x1b,  0x00,  0x00,  0x00,  0x02,  0x00,  0x00,  0x00,  0x01,  0x00,  0x05,  0x00,  0x0d,  0x00,  0x00,  0x00, 
 0x74,  0x69,  0x6d,  0x65,  0x73,  0x74,  0x61,  0x6d,  0x70,  0x5f,  0x6d,  0x73,  0x00,  0x00,  0x00,  0x00, 
 0x21,  0x00,  0x00,  0x00,  0x03,  0x00,  0x00,  0x00,  0x01,  0x00,  0x01,  0x00,  0x13,  0x00,  0x00,  0x00, 
 0x69,  0x73,  0x5f,  0x68,  0x69,  0x67,  0x68,  0x5f,  0x63,  0x6f,  0x6e,  0x66,  0x69,  0x64,  0x65,  0x6e, 
 0x63,  0x65,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x1f,  0x00,  0x00,  0x00,  0x04,  0x00,  0x00,  0x00, 
 0x01,  0x00,  0x01,  0x00,  0x11,  0x00,  0x00,  0x00,  0x69,  0x73,  0x5f,  0x68,  0x61,  0x6e,  0x64,  0x5f, 
 0x74,  0x72,  0x61,  0x63,  0x6b,  0x69,  0x6e,  0x67,  0x00,  0x00,  0x00,  0x00,  0x28,  0x00,  0x00,  0x00, 
 0x05,  0x00,  0x00,  0x00,  0x01,  0x00,  0x80,  0xf2,  0x01,  0x00,  0x00,  0xf2,  0xa9,  0x39,  0xf5,  0x4b, 
 0x7f,  0x48,  0x9d,  0x43,  0x66,  0xbb,  0x79,  0xbe,  0xe0,  0x0d,  0x00,  0x00,  0x06,  0x00,  0x00,  0x00, 
 0x70,  0x6f,  0x73,  0x65,  0x73,  0x00,  0x00,  0x00,  0xf2,  0xa9,  0x39,  0xf5,  0x4b,  0x7f,  0x48,  0x9d, 
 0x43,  0x66,  0xbb,  0x79,  0xbe,  0xe0,  0x0d,  0x00,  0xc5,  0x00,  0x00,  0x00,  0xf2,  0x51,  0x01,  0x00, 
 0x19,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x11,  0x00,  0x00,  0x00,  0x6c,  0x65,  0x6a,  0x75, 
 0x3a,  0x3a,  0x6d,  0x73,  0x67,  0x73,  0x3a,  0x3a,  0x50,  0x6f,  0x73,  0x65,  0x00,  0x00,  0x00,  0x00, 
 0x9d,  0x00,  0x00,  0x00,  0x07,  0x00,  0x00,  0x00,  0x10,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00, 
 0x01,  0x00,  0x09,  0x00,  0x02,  0x00,  0x00,  0x00,  0x78,  0x00,  0x00,  0x00,  0x10,  0x00,  0x00,  0x00, 
 0x01,  0x00,  0x00,  0x00,  0x01,  0x00,  0x09,  0x00,  0x02,  0x00,  0x00,  0x00,  0x79,  0x00,  0x00,  0x00, 
 0x10,  0x00,  0x00,  0x00,  0x02,  0x00,  0x00,  0x00,  0x01,  0x00,  0x09,  0x00,  0x02,  0x00,  0x00,  0x00, 
 0x7a,  0x00,  0x00,  0x00,  0x11,  0x00,  0x00,  0x00,  0x03,  0x00,  0x00,  0x00,  0x01,  0x00,  0x09,  0x00, 
 0x03,  0x00,  0x00,  0x00,  0x71,  0x78,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x11,  0x00,  0x00,  0x00, 
 0x04,  0x00,  0x00,  0x00,  0x01,  0x00,  0x09,  0x00,  0x03,  0x00,  0x00,  0x00,  0x71,  0x79,  0x00,  0x00, 
 0x00,  0x00,  0x00,  0x00,  0x11,  0x00,  0x00,  0x00,  0x05,  0x00,  0x00,  0x00,  0x01,  0x00,  0x09,  0x00, 
 0x03,  0x00,  0x00,  0x00,  0x71,  0x7a,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x11,  0x00,  0x00,  0x00, 
 0x06,  0x00,  0x00,  0x00,  0x01,  0x00,  0x09,  0x00,  0x03,  0x00,  0x00,  0x00,  0x71,  0x77,  0x00,  0x00, 
 0x00,  0x00,  0x00,  0x00,  0x40,  0x00,  0x00,  0x00,  0x02,  0x00,  0x00,  0x00,  0xf2,  0xcb,  0x14,  0xe1, 
 0xd1,  0xcc,  0x1f,  0x99,  0x58,  0xce,  0xc9,  0xc3,  0x9f,  0xbe,  0x17,  0xf1,  0x7f,  0x2a,  0xf7,  0xaa, 
 0xcf,  0xf4,  0x52,  0xf4,  0x00,  0xe5,  0x6e,  0xc8,  0xd5,  0x5f,  0xf2,  0xa9,  0x39,  0xf5,  0x4b,  0x7f, 
 0x48,  0x9d,  0x43,  0x66,  0xbb,  0x79,  0xbe,  0xe0,  0x0d,  0xf1,  0x3f,  0x9d,  0x21,  0x0d,  0x9b,  0xd5, 
 0x07,  0x7d,  0xeb,  0xee,  0x3e,  0x47,  0x67,  0x90, };
  return blob;
}
template<> inline const uint8_t * TopicTraits<::leju::msgs::QuestBonePoses>::type_info_blob() {
  static const uint8_t blob[] = {
 0x90,  0x00,  0x00,  0x00,  0x01,  0x10,  0x00,  0x40,  0x40,  0x00,  0x00,  0x00,  0x3c,  0x00,  0x00,  0x00, 
 0x14,  0x00,  0x00,  0x00,  0xf1,  0x7f,  0x2a,  0xf7,  0xaa,  0xcf,  0xf4,  0x52,  0xf4,  0x00,  0xe5,  0x6e, 
 0xc8,  0xd5,  0x5f,  0x00,  0x8a,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00,  0x1c,  0x00,  0x00,  0x00, 
 0x01,  0x00,  0x00,  0x00,  0x14,  0x00,  0x00,  0x00,  0xf1,  0x3f,  0x9d,  0x21,  0x0d,  0x9b,  0xd5,  0x07, 
 0x7d,  0xeb,  0xee,  0x3e,  0x47,  0x67,  0x90,  0x00,  0x87,  0x00,  0x00,  0x00,  0x02,  0x10,  0x00,  0x40, 
 0x40,  0x00,  0x00,  0x00,  0x3c,  0x00,  0x00,  0x00,  0x14,  0x00,  0x00,  0x00,  0xf2,  0xcb,  0x14,  0xe1, 
 0xd1,  0xcc,  0x1f,  0x99,  0x58,  0xce,  0xc9,  0xc3,  0x9f,  0xbe,  0x17,  0x00,  0x14,  0x01,  0x00,  0x00, 
 0x01,  0x00,  0x00,  0x00,  0x1c,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00,  0x14,  0x00,  0x00,  0x00, 
 0xf2,  0xa9,  0x39,  0xf5,  0x4b,  0x7f,  0x48,  0x9d,  0x43,  0x66,  0xbb,  0x79,  0xbe,  0xe0,  0x0d,  0x00, 
 0xc9,  0x00,  0x00,  0x00, };
  return blob;
}
#endif //DDSCXX_HAS_TYPE_DISCOVERY

} //namespace topic
} //namespace cyclonedds
} //namespace eclipse
} //namespace org

namespace dds {
namespace topic {

template <>
struct topic_type_name<::leju::msgs::Pose>
{
    static std::string value()
    {
      return org::eclipse::cyclonedds::topic::TopicTraits<::leju::msgs::Pose>::getTypeName();
    }
};

template <>
struct topic_type_name<::leju::msgs::QuestBonePoses>
{
    static std::string value()
    {
      return org::eclipse::cyclonedds::topic::TopicTraits<::leju::msgs::QuestBonePoses>::getTypeName();
    }
};

}
}

REGISTER_TOPIC_TYPE(::leju::msgs::Pose)
REGISTER_TOPIC_TYPE(::leju::msgs::QuestBonePoses)

namespace org{
namespace eclipse{
namespace cyclonedds{
namespace core{
namespace cdr{

template<>
propvec &get_type_props<::leju::msgs::Pose>();

template<typename T, std::enable_if_t<std::is_base_of<cdr_stream, T>::value, bool> = true >
bool write(T& streamer, const ::leju::msgs::Pose& instance, entity_properties_t *props) {
  (void)instance;
  if (!streamer.start_struct(*props))
    return false;
  auto prop = streamer.first_entity(props);
  while (prop) {
    switch (prop->m_id) {
      case 0:
      if (!streamer.start_member(*prop))
        return false;
      if (!write(streamer, instance.x()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 1:
      if (!streamer.start_member(*prop))
        return false;
      if (!write(streamer, instance.y()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 2:
      if (!streamer.start_member(*prop))
        return false;
      if (!write(streamer, instance.z()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 3:
      if (!streamer.start_member(*prop))
        return false;
      if (!write(streamer, instance.qx()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 4:
      if (!streamer.start_member(*prop))
        return false;
      if (!write(streamer, instance.qy()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 5:
      if (!streamer.start_member(*prop))
        return false;
      if (!write(streamer, instance.qz()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 6:
      if (!streamer.start_member(*prop))
        return false;
      if (!write(streamer, instance.qw()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
    }
    prop = streamer.next_entity(prop);
  }
  return streamer.finish_struct(*props);
}

template<typename S, std::enable_if_t<std::is_base_of<cdr_stream, S>::value, bool> = true >
bool write(S& str, const ::leju::msgs::Pose& instance, bool as_key) {
  auto &props = get_type_props<::leju::msgs::Pose>();
  str.set_mode(cdr_stream::stream_mode::write, as_key);
  return write(str, instance, props.data()); 
}

template<typename T, std::enable_if_t<std::is_base_of<cdr_stream, T>::value, bool> = true >
bool read(T& streamer, ::leju::msgs::Pose& instance, entity_properties_t *props) {
  (void)instance;
  if (!streamer.start_struct(*props))
    return false;
  auto prop = streamer.first_entity(props);
  while (prop) {
    switch (prop->m_id) {
      case 0:
      if (!streamer.start_member(*prop))
        return false;
      if (!read(streamer, instance.x()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 1:
      if (!streamer.start_member(*prop))
        return false;
      if (!read(streamer, instance.y()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 2:
      if (!streamer.start_member(*prop))
        return false;
      if (!read(streamer, instance.z()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 3:
      if (!streamer.start_member(*prop))
        return false;
      if (!read(streamer, instance.qx()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 4:
      if (!streamer.start_member(*prop))
        return false;
      if (!read(streamer, instance.qy()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 5:
      if (!streamer.start_member(*prop))
        return false;
      if (!read(streamer, instance.qz()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 6:
      if (!streamer.start_member(*prop))
        return false;
      if (!read(streamer, instance.qw()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
    }
    prop = streamer.next_entity(prop);
  }
  return streamer.finish_struct(*props);
}

template<typename S, std::enable_if_t<std::is_base_of<cdr_stream, S>::value, bool> = true >
bool read(S& str, ::leju::msgs::Pose& instance, bool as_key) {
  auto &props = get_type_props<::leju::msgs::Pose>();
  str.set_mode(cdr_stream::stream_mode::read, as_key);
  return read(str, instance, props.data()); 
}

template<typename T, std::enable_if_t<std::is_base_of<cdr_stream, T>::value, bool> = true >
bool move(T& streamer, const ::leju::msgs::Pose& instance, entity_properties_t *props) {
  (void)instance;
  if (!streamer.start_struct(*props))
    return false;
  auto prop = streamer.first_entity(props);
  while (prop) {
    switch (prop->m_id) {
      case 0:
      if (!streamer.start_member(*prop))
        return false;
      if (!move(streamer, instance.x()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 1:
      if (!streamer.start_member(*prop))
        return false;
      if (!move(streamer, instance.y()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 2:
      if (!streamer.start_member(*prop))
        return false;
      if (!move(streamer, instance.z()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 3:
      if (!streamer.start_member(*prop))
        return false;
      if (!move(streamer, instance.qx()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 4:
      if (!streamer.start_member(*prop))
        return false;
      if (!move(streamer, instance.qy()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 5:
      if (!streamer.start_member(*prop))
        return false;
      if (!move(streamer, instance.qz()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 6:
      if (!streamer.start_member(*prop))
        return false;
      if (!move(streamer, instance.qw()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
    }
    prop = streamer.next_entity(prop);
  }
  return streamer.finish_struct(*props);
}

template<typename S, std::enable_if_t<std::is_base_of<cdr_stream, S>::value, bool> = true >
bool move(S& str, const ::leju::msgs::Pose& instance, bool as_key) {
  auto &props = get_type_props<::leju::msgs::Pose>();
  str.set_mode(cdr_stream::stream_mode::move, as_key);
  return move(str, instance, props.data()); 
}

template<typename T, std::enable_if_t<std::is_base_of<cdr_stream, T>::value, bool> = true >
bool max(T& streamer, const ::leju::msgs::Pose& instance, entity_properties_t *props) {
  (void)instance;
  if (!streamer.start_struct(*props))
    return false;
  auto prop = streamer.first_entity(props);
  while (prop) {
    switch (prop->m_id) {
      case 0:
      if (!streamer.start_member(*prop))
        return false;
      if (!max(streamer, instance.x()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 1:
      if (!streamer.start_member(*prop))
        return false;
      if (!max(streamer, instance.y()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 2:
      if (!streamer.start_member(*prop))
        return false;
      if (!max(streamer, instance.z()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 3:
      if (!streamer.start_member(*prop))
        return false;
      if (!max(streamer, instance.qx()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 4:
      if (!streamer.start_member(*prop))
        return false;
      if (!max(streamer, instance.qy()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 5:
      if (!streamer.start_member(*prop))
        return false;
      if (!max(streamer, instance.qz()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 6:
      if (!streamer.start_member(*prop))
        return false;
      if (!max(streamer, instance.qw()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
    }
    prop = streamer.next_entity(prop);
  }
  return streamer.finish_struct(*props);
}

template<typename S, std::enable_if_t<std::is_base_of<cdr_stream, S>::value, bool> = true >
bool max(S& str, const ::leju::msgs::Pose& instance, bool as_key) {
  auto &props = get_type_props<::leju::msgs::Pose>();
  str.set_mode(cdr_stream::stream_mode::max, as_key);
  return max(str, instance, props.data()); 
}

template<>
propvec &get_type_props<::leju::msgs::QuestBonePoses>();

template<typename T, std::enable_if_t<std::is_base_of<cdr_stream, T>::value, bool> = true >
bool write(T& streamer, const ::leju::msgs::QuestBonePoses& instance, entity_properties_t *props) {
  (void)instance;
  if (!streamer.start_struct(*props))
    return false;
  auto prop = streamer.first_entity(props);
  while (prop) {
    switch (prop->m_id) {
      case 0:
      if (!streamer.start_member(*prop))
        return false;
      if (!write(streamer, instance.header_sec()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 1:
      if (!streamer.start_member(*prop))
        return false;
      if (!write(streamer, instance.header_nanosec()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 2:
      if (!streamer.start_member(*prop))
        return false;
      if (!write(streamer, instance.timestamp_ms()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 3:
      if (!streamer.start_member(*prop))
        return false;
      if (!write(streamer, instance.is_high_confidence()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 4:
      if (!streamer.start_member(*prop))
        return false;
      if (!write(streamer, instance.is_hand_tracking()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 5:
      if (!streamer.start_member(*prop))
        return false;
      if (!streamer.start_consecutive(false, false))
        return false;
      {
      uint32_t se_1 = uint32_t(instance.poses().size());
      if (!write(streamer, se_1))
        return false;
      for (uint32_t i_1 = 0; i_1 < se_1; i_1++) {
      if (!write(streamer, instance.poses()[i_1], prop))
        return false;
      }  //i_1
      }  //end sequence 1
      if (!streamer.finish_consecutive())
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
    }
    prop = streamer.next_entity(prop);
  }
  return streamer.finish_struct(*props);
}

template<typename S, std::enable_if_t<std::is_base_of<cdr_stream, S>::value, bool> = true >
bool write(S& str, const ::leju::msgs::QuestBonePoses& instance, bool as_key) {
  auto &props = get_type_props<::leju::msgs::QuestBonePoses>();
  str.set_mode(cdr_stream::stream_mode::write, as_key);
  return write(str, instance, props.data()); 
}

template<typename T, std::enable_if_t<std::is_base_of<cdr_stream, T>::value, bool> = true >
bool read(T& streamer, ::leju::msgs::QuestBonePoses& instance, entity_properties_t *props) {
  (void)instance;
  if (!streamer.start_struct(*props))
    return false;
  auto prop = streamer.first_entity(props);
  while (prop) {
    switch (prop->m_id) {
      case 0:
      if (!streamer.start_member(*prop))
        return false;
      if (!read(streamer, instance.header_sec()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 1:
      if (!streamer.start_member(*prop))
        return false;
      if (!read(streamer, instance.header_nanosec()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 2:
      if (!streamer.start_member(*prop))
        return false;
      if (!read(streamer, instance.timestamp_ms()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 3:
      if (!streamer.start_member(*prop))
        return false;
      if (!read(streamer, instance.is_high_confidence()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 4:
      if (!streamer.start_member(*prop))
        return false;
      if (!read(streamer, instance.is_hand_tracking()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 5:
      if (!streamer.start_member(*prop))
        return false;
      if (!streamer.start_consecutive(false, false))
        return false;
      {
      uint32_t se_1 = uint32_t(instance.poses().size());
      if (!read(streamer, se_1))
        return false;
      instance.poses().resize(se_1);
      for (uint32_t i_1 = 0; i_1 < se_1; i_1++) {
      if (!read(streamer, instance.poses()[i_1], prop))
        return false;
      }  //i_1
      }  //end sequence 1
      if (!streamer.finish_consecutive())
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
    }
    prop = streamer.next_entity(prop);
  }
  return streamer.finish_struct(*props);
}

template<typename S, std::enable_if_t<std::is_base_of<cdr_stream, S>::value, bool> = true >
bool read(S& str, ::leju::msgs::QuestBonePoses& instance, bool as_key) {
  auto &props = get_type_props<::leju::msgs::QuestBonePoses>();
  str.set_mode(cdr_stream::stream_mode::read, as_key);
  return read(str, instance, props.data()); 
}

template<typename T, std::enable_if_t<std::is_base_of<cdr_stream, T>::value, bool> = true >
bool move(T& streamer, const ::leju::msgs::QuestBonePoses& instance, entity_properties_t *props) {
  (void)instance;
  if (!streamer.start_struct(*props))
    return false;
  auto prop = streamer.first_entity(props);
  while (prop) {
    switch (prop->m_id) {
      case 0:
      if (!streamer.start_member(*prop))
        return false;
      if (!move(streamer, instance.header_sec()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 1:
      if (!streamer.start_member(*prop))
        return false;
      if (!move(streamer, instance.header_nanosec()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 2:
      if (!streamer.start_member(*prop))
        return false;
      if (!move(streamer, instance.timestamp_ms()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 3:
      if (!streamer.start_member(*prop))
        return false;
      if (!move(streamer, instance.is_high_confidence()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 4:
      if (!streamer.start_member(*prop))
        return false;
      if (!move(streamer, instance.is_hand_tracking()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 5:
      if (!streamer.start_member(*prop))
        return false;
      if (!streamer.start_consecutive(false, false))
        return false;
      {
      uint32_t se_1 = uint32_t(instance.poses().size());
      if (!move(streamer, se_1))
        return false;
      for (uint32_t i_1 = 0; i_1 < se_1; i_1++) {
      if (!move(streamer, instance.poses()[i_1], prop))
        return false;
      }  //i_1
      }  //end sequence 1
      if (!streamer.finish_consecutive())
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
    }
    prop = streamer.next_entity(prop);
  }
  return streamer.finish_struct(*props);
}

template<typename S, std::enable_if_t<std::is_base_of<cdr_stream, S>::value, bool> = true >
bool move(S& str, const ::leju::msgs::QuestBonePoses& instance, bool as_key) {
  auto &props = get_type_props<::leju::msgs::QuestBonePoses>();
  str.set_mode(cdr_stream::stream_mode::move, as_key);
  return move(str, instance, props.data()); 
}

template<typename T, std::enable_if_t<std::is_base_of<cdr_stream, T>::value, bool> = true >
bool max(T& streamer, const ::leju::msgs::QuestBonePoses& instance, entity_properties_t *props) {
  (void)instance;
  if (!streamer.start_struct(*props))
    return false;
  auto prop = streamer.first_entity(props);
  while (prop) {
    switch (prop->m_id) {
      case 0:
      if (!streamer.start_member(*prop))
        return false;
      if (!max(streamer, instance.header_sec()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 1:
      if (!streamer.start_member(*prop))
        return false;
      if (!max(streamer, instance.header_nanosec()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 2:
      if (!streamer.start_member(*prop))
        return false;
      if (!max(streamer, instance.timestamp_ms()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 3:
      if (!streamer.start_member(*prop))
        return false;
      if (!max(streamer, instance.is_high_confidence()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 4:
      if (!streamer.start_member(*prop))
        return false;
      if (!max(streamer, instance.is_hand_tracking()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 5:
      if (!streamer.start_member(*prop))
        return false;
      if (!streamer.start_consecutive(false, false))
        return false;
      {
      uint32_t se_1 = 0;
      if (!max(streamer, se_1))
        return false;
      for (uint32_t i_1 = 0; i_1 < se_1; i_1++) {
      if (!max(streamer, instance.poses()[i_1], prop))
        return false;
      }  //i_1
      }  //end sequence 1
      if (!streamer.finish_consecutive())
        return false;
      streamer.position(SIZE_MAX);
      if (!streamer.finish_member(*prop))
        return false;
      break;
    }
    prop = streamer.next_entity(prop);
  }
  return streamer.finish_struct(*props);
}

template<typename S, std::enable_if_t<std::is_base_of<cdr_stream, S>::value, bool> = true >
bool max(S& str, const ::leju::msgs::QuestBonePoses& instance, bool as_key) {
  auto &props = get_type_props<::leju::msgs::QuestBonePoses>();
  str.set_mode(cdr_stream::stream_mode::max, as_key);
  return max(str, instance, props.data()); 
}

} //namespace cdr
} //namespace core
} //namespace cyclonedds
} //namespace eclipse
} //namespace org

#endif // DDSCXX_QUESTBONEPOSES_HPP
