#########################################################
# bcan3 测试配置 (仅 2 个已确认响应的电机)
# 经典 CAN 单帧协议
#########################################################
canbus_interfaces:
  bcan3:
    type: SOCKETCAN
    name: "bcan3"
    nbitrate: 1000000
    dbitrate: 1000000
    nsamplepos: 80
    dsamplepos: 80
    enable: true
#########################################################
# bcan3: 2个电机 (ID 0x01, 0x02)
#########################################################
bcan3_devices:
  - name: Rarm_joint_01
    class: motor
    device_id: 0x01
    params: [0, 25, 8, 0, 0, 0, 0]
    ratio: 25
    negtive: false
    ignore: false
  - name: Rarm_joint_02
    class: motor
    device_id: 0x02
    params: [0, 20, 6, 0, 0, 0, 0]
    ratio: 25
    negtive: false
    ignore: false
