// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/hand_wrench_srv.proto

#ifndef PROTOBUF_INCLUDED_protos_2fhand_5fwrench_5fsrv_2eproto
#define PROTOBUF_INCLUDED_protos_2fhand_5fwrench_5fsrv_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_protos_2fhand_5fwrench_5fsrv_2eproto 

namespace protobuf_protos_2fhand_5fwrench_5fsrv_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[3];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_protos_2fhand_5fwrench_5fsrv_2eproto
namespace protos {
class ItemMassForce;
class ItemMassForceDefaultTypeInternal;
extern ItemMassForceDefaultTypeInternal _ItemMassForce_default_instance_;
class ItemMassForceRequest;
class ItemMassForceRequestDefaultTypeInternal;
extern ItemMassForceRequestDefaultTypeInternal _ItemMassForceRequest_default_instance_;
class ItemMassForceResponse;
class ItemMassForceResponseDefaultTypeInternal;
extern ItemMassForceResponseDefaultTypeInternal _ItemMassForceResponse_default_instance_;
}  // namespace protos
namespace google {
namespace protobuf {
template<> ::protos::ItemMassForce* Arena::CreateMaybeMessage<::protos::ItemMassForce>(Arena*);
template<> ::protos::ItemMassForceRequest* Arena::CreateMaybeMessage<::protos::ItemMassForceRequest>(Arena*);
template<> ::protos::ItemMassForceResponse* Arena::CreateMaybeMessage<::protos::ItemMassForceResponse>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace protos {

enum ItemMassForceResponse_OperationStatus {
  ItemMassForceResponse_OperationStatus_SUCCESS = 0,
  ItemMassForceResponse_OperationStatus_ERROR = 1,
  ItemMassForceResponse_OperationStatus_TIMEOUT = 2,
  ItemMassForceResponse_OperationStatus_INVALID_REQUEST = 3,
  ItemMassForceResponse_OperationStatus_ItemMassForceResponse_OperationStatus_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  ItemMassForceResponse_OperationStatus_ItemMassForceResponse_OperationStatus_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool ItemMassForceResponse_OperationStatus_IsValid(int value);
const ItemMassForceResponse_OperationStatus ItemMassForceResponse_OperationStatus_OperationStatus_MIN = ItemMassForceResponse_OperationStatus_SUCCESS;
const ItemMassForceResponse_OperationStatus ItemMassForceResponse_OperationStatus_OperationStatus_MAX = ItemMassForceResponse_OperationStatus_INVALID_REQUEST;
const int ItemMassForceResponse_OperationStatus_OperationStatus_ARRAYSIZE = ItemMassForceResponse_OperationStatus_OperationStatus_MAX + 1;

const ::google::protobuf::EnumDescriptor* ItemMassForceResponse_OperationStatus_descriptor();
inline const ::std::string& ItemMassForceResponse_OperationStatus_Name(ItemMassForceResponse_OperationStatus value) {
  return ::google::protobuf::internal::NameOfEnum(
    ItemMassForceResponse_OperationStatus_descriptor(), value);
}
inline bool ItemMassForceResponse_OperationStatus_Parse(
    const ::std::string& name, ItemMassForceResponse_OperationStatus* value) {
  return ::google::protobuf::internal::ParseNamedEnum<ItemMassForceResponse_OperationStatus>(
    ItemMassForceResponse_OperationStatus_descriptor(), name, value);
}
enum ItemMassForceOperation {
  GET = 0,
  SET = 1,
  ItemMassForceOperation_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  ItemMassForceOperation_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool ItemMassForceOperation_IsValid(int value);
const ItemMassForceOperation ItemMassForceOperation_MIN = GET;
const ItemMassForceOperation ItemMassForceOperation_MAX = SET;
const int ItemMassForceOperation_ARRAYSIZE = ItemMassForceOperation_MAX + 1;

const ::google::protobuf::EnumDescriptor* ItemMassForceOperation_descriptor();
inline const ::std::string& ItemMassForceOperation_Name(ItemMassForceOperation value) {
  return ::google::protobuf::internal::NameOfEnum(
    ItemMassForceOperation_descriptor(), value);
}
inline bool ItemMassForceOperation_Parse(
    const ::std::string& name, ItemMassForceOperation* value) {
  return ::google::protobuf::internal::ParseNamedEnum<ItemMassForceOperation>(
    ItemMassForceOperation_descriptor(), name, value);
}
// ===================================================================

class ItemMassForce : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:protos.ItemMassForce) */ {
 public:
  ItemMassForce();
  virtual ~ItemMassForce();

  ItemMassForce(const ItemMassForce& from);

  inline ItemMassForce& operator=(const ItemMassForce& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  ItemMassForce(ItemMassForce&& from) noexcept
    : ItemMassForce() {
    *this = ::std::move(from);
  }

  inline ItemMassForce& operator=(ItemMassForce&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const ItemMassForce& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ItemMassForce* internal_default_instance() {
    return reinterpret_cast<const ItemMassForce*>(
               &_ItemMassForce_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(ItemMassForce* other);
  friend void swap(ItemMassForce& a, ItemMassForce& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ItemMassForce* New() const final {
    return CreateMaybeMessage<ItemMassForce>(NULL);
  }

  ItemMassForce* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<ItemMassForce>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const ItemMassForce& from);
  void MergeFrom(const ItemMassForce& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ItemMassForce* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string case_name = 1;
  void clear_case_name();
  static const int kCaseNameFieldNumber = 1;
  const ::std::string& case_name() const;
  void set_case_name(const ::std::string& value);
  #if LANG_CXX11
  void set_case_name(::std::string&& value);
  #endif
  void set_case_name(const char* value);
  void set_case_name(const char* value, size_t size);
  ::std::string* mutable_case_name();
  ::std::string* release_case_name();
  void set_allocated_case_name(::std::string* case_name);

  // string description = 2;
  void clear_description();
  static const int kDescriptionFieldNumber = 2;
  const ::std::string& description() const;
  void set_description(const ::std::string& value);
  #if LANG_CXX11
  void set_description(::std::string&& value);
  #endif
  void set_description(const char* value);
  void set_description(const char* value, size_t size);
  ::std::string* mutable_description();
  ::std::string* release_description();
  void set_allocated_description(::std::string* description);

  // double item_mass = 3;
  void clear_item_mass();
  static const int kItemMassFieldNumber = 3;
  double item_mass() const;
  void set_item_mass(double value);

  // double lforce_x = 4;
  void clear_lforce_x();
  static const int kLforceXFieldNumber = 4;
  double lforce_x() const;
  void set_lforce_x(double value);

  // double lforce_y = 5;
  void clear_lforce_y();
  static const int kLforceYFieldNumber = 5;
  double lforce_y() const;
  void set_lforce_y(double value);

  // double lforce_z = 6;
  void clear_lforce_z();
  static const int kLforceZFieldNumber = 6;
  double lforce_z() const;
  void set_lforce_z(double value);

  // @@protoc_insertion_point(class_scope:protos.ItemMassForce)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr case_name_;
  ::google::protobuf::internal::ArenaStringPtr description_;
  double item_mass_;
  double lforce_x_;
  double lforce_y_;
  double lforce_z_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_protos_2fhand_5fwrench_5fsrv_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class ItemMassForceRequest : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:protos.ItemMassForceRequest) */ {
 public:
  ItemMassForceRequest();
  virtual ~ItemMassForceRequest();

  ItemMassForceRequest(const ItemMassForceRequest& from);

  inline ItemMassForceRequest& operator=(const ItemMassForceRequest& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  ItemMassForceRequest(ItemMassForceRequest&& from) noexcept
    : ItemMassForceRequest() {
    *this = ::std::move(from);
  }

  inline ItemMassForceRequest& operator=(ItemMassForceRequest&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const ItemMassForceRequest& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ItemMassForceRequest* internal_default_instance() {
    return reinterpret_cast<const ItemMassForceRequest*>(
               &_ItemMassForceRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void Swap(ItemMassForceRequest* other);
  friend void swap(ItemMassForceRequest& a, ItemMassForceRequest& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ItemMassForceRequest* New() const final {
    return CreateMaybeMessage<ItemMassForceRequest>(NULL);
  }

  ItemMassForceRequest* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<ItemMassForceRequest>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const ItemMassForceRequest& from);
  void MergeFrom(const ItemMassForceRequest& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ItemMassForceRequest* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // .protos.ItemMassForce data = 2;
  bool has_data() const;
  void clear_data();
  static const int kDataFieldNumber = 2;
  private:
  const ::protos::ItemMassForce& _internal_data() const;
  public:
  const ::protos::ItemMassForce& data() const;
  ::protos::ItemMassForce* release_data();
  ::protos::ItemMassForce* mutable_data();
  void set_allocated_data(::protos::ItemMassForce* data);

  // .protos.ItemMassForceOperation operation = 1;
  void clear_operation();
  static const int kOperationFieldNumber = 1;
  ::protos::ItemMassForceOperation operation() const;
  void set_operation(::protos::ItemMassForceOperation value);

  // @@protoc_insertion_point(class_scope:protos.ItemMassForceRequest)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::protos::ItemMassForce* data_;
  int operation_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_protos_2fhand_5fwrench_5fsrv_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class ItemMassForceResponse : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:protos.ItemMassForceResponse) */ {
 public:
  ItemMassForceResponse();
  virtual ~ItemMassForceResponse();

  ItemMassForceResponse(const ItemMassForceResponse& from);

  inline ItemMassForceResponse& operator=(const ItemMassForceResponse& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  ItemMassForceResponse(ItemMassForceResponse&& from) noexcept
    : ItemMassForceResponse() {
    *this = ::std::move(from);
  }

  inline ItemMassForceResponse& operator=(ItemMassForceResponse&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const ItemMassForceResponse& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ItemMassForceResponse* internal_default_instance() {
    return reinterpret_cast<const ItemMassForceResponse*>(
               &_ItemMassForceResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  void Swap(ItemMassForceResponse* other);
  friend void swap(ItemMassForceResponse& a, ItemMassForceResponse& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ItemMassForceResponse* New() const final {
    return CreateMaybeMessage<ItemMassForceResponse>(NULL);
  }

  ItemMassForceResponse* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<ItemMassForceResponse>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const ItemMassForceResponse& from);
  void MergeFrom(const ItemMassForceResponse& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ItemMassForceResponse* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  typedef ItemMassForceResponse_OperationStatus OperationStatus;
  static const OperationStatus SUCCESS =
    ItemMassForceResponse_OperationStatus_SUCCESS;
  static const OperationStatus ERROR =
    ItemMassForceResponse_OperationStatus_ERROR;
  static const OperationStatus TIMEOUT =
    ItemMassForceResponse_OperationStatus_TIMEOUT;
  static const OperationStatus INVALID_REQUEST =
    ItemMassForceResponse_OperationStatus_INVALID_REQUEST;
  static inline bool OperationStatus_IsValid(int value) {
    return ItemMassForceResponse_OperationStatus_IsValid(value);
  }
  static const OperationStatus OperationStatus_MIN =
    ItemMassForceResponse_OperationStatus_OperationStatus_MIN;
  static const OperationStatus OperationStatus_MAX =
    ItemMassForceResponse_OperationStatus_OperationStatus_MAX;
  static const int OperationStatus_ARRAYSIZE =
    ItemMassForceResponse_OperationStatus_OperationStatus_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  OperationStatus_descriptor() {
    return ItemMassForceResponse_OperationStatus_descriptor();
  }
  static inline const ::std::string& OperationStatus_Name(OperationStatus value) {
    return ItemMassForceResponse_OperationStatus_Name(value);
  }
  static inline bool OperationStatus_Parse(const ::std::string& name,
      OperationStatus* value) {
    return ItemMassForceResponse_OperationStatus_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // repeated .protos.ItemMassForce item_mass_forces = 4;
  int item_mass_forces_size() const;
  void clear_item_mass_forces();
  static const int kItemMassForcesFieldNumber = 4;
  ::protos::ItemMassForce* mutable_item_mass_forces(int index);
  ::google::protobuf::RepeatedPtrField< ::protos::ItemMassForce >*
      mutable_item_mass_forces();
  const ::protos::ItemMassForce& item_mass_forces(int index) const;
  ::protos::ItemMassForce* add_item_mass_forces();
  const ::google::protobuf::RepeatedPtrField< ::protos::ItemMassForce >&
      item_mass_forces() const;

  // string description = 3;
  void clear_description();
  static const int kDescriptionFieldNumber = 3;
  const ::std::string& description() const;
  void set_description(const ::std::string& value);
  #if LANG_CXX11
  void set_description(::std::string&& value);
  #endif
  void set_description(const char* value);
  void set_description(const char* value, size_t size);
  ::std::string* mutable_description();
  ::std::string* release_description();
  void set_allocated_description(::std::string* description);

  // .protos.ItemMassForceOperation operation = 1;
  void clear_operation();
  static const int kOperationFieldNumber = 1;
  ::protos::ItemMassForceOperation operation() const;
  void set_operation(::protos::ItemMassForceOperation value);

  // .protos.ItemMassForceResponse.OperationStatus status = 2;
  void clear_status();
  static const int kStatusFieldNumber = 2;
  ::protos::ItemMassForceResponse_OperationStatus status() const;
  void set_status(::protos::ItemMassForceResponse_OperationStatus value);

  // @@protoc_insertion_point(class_scope:protos.ItemMassForceResponse)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::protos::ItemMassForce > item_mass_forces_;
  ::google::protobuf::internal::ArenaStringPtr description_;
  int operation_;
  int status_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_protos_2fhand_5fwrench_5fsrv_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// ItemMassForce

// string case_name = 1;
inline void ItemMassForce::clear_case_name() {
  case_name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& ItemMassForce::case_name() const {
  // @@protoc_insertion_point(field_get:protos.ItemMassForce.case_name)
  return case_name_.GetNoArena();
}
inline void ItemMassForce::set_case_name(const ::std::string& value) {
  
  case_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:protos.ItemMassForce.case_name)
}
#if LANG_CXX11
inline void ItemMassForce::set_case_name(::std::string&& value) {
  
  case_name_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:protos.ItemMassForce.case_name)
}
#endif
inline void ItemMassForce::set_case_name(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  case_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:protos.ItemMassForce.case_name)
}
inline void ItemMassForce::set_case_name(const char* value, size_t size) {
  
  case_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:protos.ItemMassForce.case_name)
}
inline ::std::string* ItemMassForce::mutable_case_name() {
  
  // @@protoc_insertion_point(field_mutable:protos.ItemMassForce.case_name)
  return case_name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* ItemMassForce::release_case_name() {
  // @@protoc_insertion_point(field_release:protos.ItemMassForce.case_name)
  
  return case_name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ItemMassForce::set_allocated_case_name(::std::string* case_name) {
  if (case_name != NULL) {
    
  } else {
    
  }
  case_name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), case_name);
  // @@protoc_insertion_point(field_set_allocated:protos.ItemMassForce.case_name)
}

// string description = 2;
inline void ItemMassForce::clear_description() {
  description_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& ItemMassForce::description() const {
  // @@protoc_insertion_point(field_get:protos.ItemMassForce.description)
  return description_.GetNoArena();
}
inline void ItemMassForce::set_description(const ::std::string& value) {
  
  description_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:protos.ItemMassForce.description)
}
#if LANG_CXX11
inline void ItemMassForce::set_description(::std::string&& value) {
  
  description_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:protos.ItemMassForce.description)
}
#endif
inline void ItemMassForce::set_description(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  description_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:protos.ItemMassForce.description)
}
inline void ItemMassForce::set_description(const char* value, size_t size) {
  
  description_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:protos.ItemMassForce.description)
}
inline ::std::string* ItemMassForce::mutable_description() {
  
  // @@protoc_insertion_point(field_mutable:protos.ItemMassForce.description)
  return description_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* ItemMassForce::release_description() {
  // @@protoc_insertion_point(field_release:protos.ItemMassForce.description)
  
  return description_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ItemMassForce::set_allocated_description(::std::string* description) {
  if (description != NULL) {
    
  } else {
    
  }
  description_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), description);
  // @@protoc_insertion_point(field_set_allocated:protos.ItemMassForce.description)
}

// double item_mass = 3;
inline void ItemMassForce::clear_item_mass() {
  item_mass_ = 0;
}
inline double ItemMassForce::item_mass() const {
  // @@protoc_insertion_point(field_get:protos.ItemMassForce.item_mass)
  return item_mass_;
}
inline void ItemMassForce::set_item_mass(double value) {
  
  item_mass_ = value;
  // @@protoc_insertion_point(field_set:protos.ItemMassForce.item_mass)
}

// double lforce_x = 4;
inline void ItemMassForce::clear_lforce_x() {
  lforce_x_ = 0;
}
inline double ItemMassForce::lforce_x() const {
  // @@protoc_insertion_point(field_get:protos.ItemMassForce.lforce_x)
  return lforce_x_;
}
inline void ItemMassForce::set_lforce_x(double value) {
  
  lforce_x_ = value;
  // @@protoc_insertion_point(field_set:protos.ItemMassForce.lforce_x)
}

// double lforce_y = 5;
inline void ItemMassForce::clear_lforce_y() {
  lforce_y_ = 0;
}
inline double ItemMassForce::lforce_y() const {
  // @@protoc_insertion_point(field_get:protos.ItemMassForce.lforce_y)
  return lforce_y_;
}
inline void ItemMassForce::set_lforce_y(double value) {
  
  lforce_y_ = value;
  // @@protoc_insertion_point(field_set:protos.ItemMassForce.lforce_y)
}

// double lforce_z = 6;
inline void ItemMassForce::clear_lforce_z() {
  lforce_z_ = 0;
}
inline double ItemMassForce::lforce_z() const {
  // @@protoc_insertion_point(field_get:protos.ItemMassForce.lforce_z)
  return lforce_z_;
}
inline void ItemMassForce::set_lforce_z(double value) {
  
  lforce_z_ = value;
  // @@protoc_insertion_point(field_set:protos.ItemMassForce.lforce_z)
}

// -------------------------------------------------------------------

// ItemMassForceRequest

// .protos.ItemMassForceOperation operation = 1;
inline void ItemMassForceRequest::clear_operation() {
  operation_ = 0;
}
inline ::protos::ItemMassForceOperation ItemMassForceRequest::operation() const {
  // @@protoc_insertion_point(field_get:protos.ItemMassForceRequest.operation)
  return static_cast< ::protos::ItemMassForceOperation >(operation_);
}
inline void ItemMassForceRequest::set_operation(::protos::ItemMassForceOperation value) {
  
  operation_ = value;
  // @@protoc_insertion_point(field_set:protos.ItemMassForceRequest.operation)
}

// .protos.ItemMassForce data = 2;
inline bool ItemMassForceRequest::has_data() const {
  return this != internal_default_instance() && data_ != NULL;
}
inline void ItemMassForceRequest::clear_data() {
  if (GetArenaNoVirtual() == NULL && data_ != NULL) {
    delete data_;
  }
  data_ = NULL;
}
inline const ::protos::ItemMassForce& ItemMassForceRequest::_internal_data() const {
  return *data_;
}
inline const ::protos::ItemMassForce& ItemMassForceRequest::data() const {
  const ::protos::ItemMassForce* p = data_;
  // @@protoc_insertion_point(field_get:protos.ItemMassForceRequest.data)
  return p != NULL ? *p : *reinterpret_cast<const ::protos::ItemMassForce*>(
      &::protos::_ItemMassForce_default_instance_);
}
inline ::protos::ItemMassForce* ItemMassForceRequest::release_data() {
  // @@protoc_insertion_point(field_release:protos.ItemMassForceRequest.data)
  
  ::protos::ItemMassForce* temp = data_;
  data_ = NULL;
  return temp;
}
inline ::protos::ItemMassForce* ItemMassForceRequest::mutable_data() {
  
  if (data_ == NULL) {
    auto* p = CreateMaybeMessage<::protos::ItemMassForce>(GetArenaNoVirtual());
    data_ = p;
  }
  // @@protoc_insertion_point(field_mutable:protos.ItemMassForceRequest.data)
  return data_;
}
inline void ItemMassForceRequest::set_allocated_data(::protos::ItemMassForce* data) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete data_;
  }
  if (data) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      data = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, data, submessage_arena);
    }
    
  } else {
    
  }
  data_ = data;
  // @@protoc_insertion_point(field_set_allocated:protos.ItemMassForceRequest.data)
}

// -------------------------------------------------------------------

// ItemMassForceResponse

// .protos.ItemMassForceOperation operation = 1;
inline void ItemMassForceResponse::clear_operation() {
  operation_ = 0;
}
inline ::protos::ItemMassForceOperation ItemMassForceResponse::operation() const {
  // @@protoc_insertion_point(field_get:protos.ItemMassForceResponse.operation)
  return static_cast< ::protos::ItemMassForceOperation >(operation_);
}
inline void ItemMassForceResponse::set_operation(::protos::ItemMassForceOperation value) {
  
  operation_ = value;
  // @@protoc_insertion_point(field_set:protos.ItemMassForceResponse.operation)
}

// .protos.ItemMassForceResponse.OperationStatus status = 2;
inline void ItemMassForceResponse::clear_status() {
  status_ = 0;
}
inline ::protos::ItemMassForceResponse_OperationStatus ItemMassForceResponse::status() const {
  // @@protoc_insertion_point(field_get:protos.ItemMassForceResponse.status)
  return static_cast< ::protos::ItemMassForceResponse_OperationStatus >(status_);
}
inline void ItemMassForceResponse::set_status(::protos::ItemMassForceResponse_OperationStatus value) {
  
  status_ = value;
  // @@protoc_insertion_point(field_set:protos.ItemMassForceResponse.status)
}

// string description = 3;
inline void ItemMassForceResponse::clear_description() {
  description_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& ItemMassForceResponse::description() const {
  // @@protoc_insertion_point(field_get:protos.ItemMassForceResponse.description)
  return description_.GetNoArena();
}
inline void ItemMassForceResponse::set_description(const ::std::string& value) {
  
  description_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:protos.ItemMassForceResponse.description)
}
#if LANG_CXX11
inline void ItemMassForceResponse::set_description(::std::string&& value) {
  
  description_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:protos.ItemMassForceResponse.description)
}
#endif
inline void ItemMassForceResponse::set_description(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  description_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:protos.ItemMassForceResponse.description)
}
inline void ItemMassForceResponse::set_description(const char* value, size_t size) {
  
  description_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:protos.ItemMassForceResponse.description)
}
inline ::std::string* ItemMassForceResponse::mutable_description() {
  
  // @@protoc_insertion_point(field_mutable:protos.ItemMassForceResponse.description)
  return description_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* ItemMassForceResponse::release_description() {
  // @@protoc_insertion_point(field_release:protos.ItemMassForceResponse.description)
  
  return description_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ItemMassForceResponse::set_allocated_description(::std::string* description) {
  if (description != NULL) {
    
  } else {
    
  }
  description_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), description);
  // @@protoc_insertion_point(field_set_allocated:protos.ItemMassForceResponse.description)
}

// repeated .protos.ItemMassForce item_mass_forces = 4;
inline int ItemMassForceResponse::item_mass_forces_size() const {
  return item_mass_forces_.size();
}
inline void ItemMassForceResponse::clear_item_mass_forces() {
  item_mass_forces_.Clear();
}
inline ::protos::ItemMassForce* ItemMassForceResponse::mutable_item_mass_forces(int index) {
  // @@protoc_insertion_point(field_mutable:protos.ItemMassForceResponse.item_mass_forces)
  return item_mass_forces_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::protos::ItemMassForce >*
ItemMassForceResponse::mutable_item_mass_forces() {
  // @@protoc_insertion_point(field_mutable_list:protos.ItemMassForceResponse.item_mass_forces)
  return &item_mass_forces_;
}
inline const ::protos::ItemMassForce& ItemMassForceResponse::item_mass_forces(int index) const {
  // @@protoc_insertion_point(field_get:protos.ItemMassForceResponse.item_mass_forces)
  return item_mass_forces_.Get(index);
}
inline ::protos::ItemMassForce* ItemMassForceResponse::add_item_mass_forces() {
  // @@protoc_insertion_point(field_add:protos.ItemMassForceResponse.item_mass_forces)
  return item_mass_forces_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::protos::ItemMassForce >&
ItemMassForceResponse::item_mass_forces() const {
  // @@protoc_insertion_point(field_list:protos.ItemMassForceResponse.item_mass_forces)
  return item_mass_forces_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace protos

namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::protos::ItemMassForceResponse_OperationStatus> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::protos::ItemMassForceResponse_OperationStatus>() {
  return ::protos::ItemMassForceResponse_OperationStatus_descriptor();
}
template <> struct is_proto_enum< ::protos::ItemMassForceOperation> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::protos::ItemMassForceOperation>() {
  return ::protos::ItemMassForceOperation_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_protos_2fhand_5fwrench_5fsrv_2eproto
