// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/robot_info.proto

#include "robot_info.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

namespace protos {
class RobotDescriptionDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<RobotDescription>
      _instance;
} _RobotDescription_default_instance_;
}  // namespace protos
namespace protobuf_protos_2frobot_5finfo_2eproto {
static void InitDefaultsRobotDescription() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::protos::_RobotDescription_default_instance_;
    new (ptr) ::protos::RobotDescription();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::protos::RobotDescription::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_RobotDescription =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsRobotDescription}, {}};

void InitDefaults() {
  ::google::protobuf::internal::InitSCC(&scc_info_RobotDescription.base);
}

::google::protobuf::Metadata file_level_metadata[1];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::protos::RobotDescription, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::protos::RobotDescription, robot_name_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::protos::RobotDescription, robot_version_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::protos::RobotDescription)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::protos::_RobotDescription_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  AssignDescriptors(
      "protos/robot_info.proto", schemas, file_default_instances, TableStruct::offsets,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 1);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\027protos/robot_info.proto\022\006protos\"=\n\020Rob"
      "otDescription\022\022\n\nrobot_name\030\001 \001(\t\022\025\n\rrob"
      "ot_version\030\002 \001(\005b\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 104);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "protos/robot_info.proto", &protobuf_RegisterTypes);
}

void AddDescriptors() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_protos_2frobot_5finfo_2eproto
namespace protos {

// ===================================================================

void RobotDescription::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int RobotDescription::kRobotNameFieldNumber;
const int RobotDescription::kRobotVersionFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

RobotDescription::RobotDescription()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_protos_2frobot_5finfo_2eproto::scc_info_RobotDescription.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:protos.RobotDescription)
}
RobotDescription::RobotDescription(const RobotDescription& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  robot_name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.robot_name().size() > 0) {
    robot_name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.robot_name_);
  }
  robot_version_ = from.robot_version_;
  // @@protoc_insertion_point(copy_constructor:protos.RobotDescription)
}

void RobotDescription::SharedCtor() {
  robot_name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  robot_version_ = 0;
}

RobotDescription::~RobotDescription() {
  // @@protoc_insertion_point(destructor:protos.RobotDescription)
  SharedDtor();
}

void RobotDescription::SharedDtor() {
  robot_name_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void RobotDescription::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* RobotDescription::descriptor() {
  ::protobuf_protos_2frobot_5finfo_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_protos_2frobot_5finfo_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const RobotDescription& RobotDescription::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_protos_2frobot_5finfo_2eproto::scc_info_RobotDescription.base);
  return *internal_default_instance();
}


void RobotDescription::Clear() {
// @@protoc_insertion_point(message_clear_start:protos.RobotDescription)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  robot_name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  robot_version_ = 0;
  _internal_metadata_.Clear();
}

bool RobotDescription::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:protos.RobotDescription)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // string robot_name = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_robot_name()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->robot_name().data(), static_cast<int>(this->robot_name().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "protos.RobotDescription.robot_name"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 robot_version = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u /* 16 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &robot_version_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:protos.RobotDescription)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:protos.RobotDescription)
  return false;
#undef DO_
}

void RobotDescription::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:protos.RobotDescription)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string robot_name = 1;
  if (this->robot_name().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->robot_name().data(), static_cast<int>(this->robot_name().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "protos.RobotDescription.robot_name");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->robot_name(), output);
  }

  // int32 robot_version = 2;
  if (this->robot_version() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->robot_version(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:protos.RobotDescription)
}

::google::protobuf::uint8* RobotDescription::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:protos.RobotDescription)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string robot_name = 1;
  if (this->robot_name().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->robot_name().data(), static_cast<int>(this->robot_name().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "protos.RobotDescription.robot_name");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->robot_name(), target);
  }

  // int32 robot_version = 2;
  if (this->robot_version() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->robot_version(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:protos.RobotDescription)
  return target;
}

size_t RobotDescription::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:protos.RobotDescription)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // string robot_name = 1;
  if (this->robot_name().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->robot_name());
  }

  // int32 robot_version = 2;
  if (this->robot_version() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->robot_version());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void RobotDescription::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:protos.RobotDescription)
  GOOGLE_DCHECK_NE(&from, this);
  const RobotDescription* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const RobotDescription>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:protos.RobotDescription)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:protos.RobotDescription)
    MergeFrom(*source);
  }
}

void RobotDescription::MergeFrom(const RobotDescription& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:protos.RobotDescription)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.robot_name().size() > 0) {

    robot_name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.robot_name_);
  }
  if (from.robot_version() != 0) {
    set_robot_version(from.robot_version());
  }
}

void RobotDescription::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:protos.RobotDescription)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void RobotDescription::CopyFrom(const RobotDescription& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:protos.RobotDescription)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool RobotDescription::IsInitialized() const {
  return true;
}

void RobotDescription::Swap(RobotDescription* other) {
  if (other == this) return;
  InternalSwap(other);
}
void RobotDescription::InternalSwap(RobotDescription* other) {
  using std::swap;
  robot_name_.Swap(&other->robot_name_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(robot_version_, other->robot_version_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata RobotDescription::GetMetadata() const {
  protobuf_protos_2frobot_5finfo_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_protos_2frobot_5finfo_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace protos
namespace google {
namespace protobuf {
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::protos::RobotDescription* Arena::CreateMaybeMessage< ::protos::RobotDescription >(Arena* arena) {
  return Arena::CreateInternal< ::protos::RobotDescription >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
