/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to CXX Translator
  File name: Float64Types.idl
  Source: Float64Types.hpp
  Cyclone DDS: v0.10.2

*****************************************************************/
#ifndef DDSCXX_FLOAT64TYPES_HPP
#define DDSCXX_FLOAT64TYPES_HPP

#include <cstdint>
#include <vector>

namespace leju
{
namespace msgs
{
class Float64
{
private:
 int32_t header_sec_ = 0;
 uint32_t header_nanosec_ = 0;
 double data_ = 0.0;

public:
  Float64() = default;

  explicit Float64(
    int32_t header_sec,
    uint32_t header_nanosec,
    double data) :
    header_sec_(header_sec),
    header_nanosec_(header_nanosec),
    data_(data) { }

  int32_t header_sec() const { return this->header_sec_; }
  int32_t& header_sec() { return this->header_sec_; }
  void header_sec(int32_t _val_) { this->header_sec_ = _val_; }
  uint32_t header_nanosec() const { return this->header_nanosec_; }
  uint32_t& header_nanosec() { return this->header_nanosec_; }
  void header_nanosec(uint32_t _val_) { this->header_nanosec_ = _val_; }
  double data() const { return this->data_; }
  double& data() { return this->data_; }
  void data(double _val_) { this->data_ = _val_; }

  bool operator==(const Float64& _other) const
  {
    (void) _other;
    return header_sec_ == _other.header_sec_ &&
      header_nanosec_ == _other.header_nanosec_ &&
      data_ == _other.data_;
  }

  bool operator!=(const Float64& _other) const
  {
    return !(*this == _other);
  }

};

class Float64Array
{
private:
 int32_t header_sec_ = 0;
 uint32_t header_nanosec_ = 0;
 std::vector<double> data_;

public:
  Float64Array() = default;

  explicit Float64Array(
    int32_t header_sec,
    uint32_t header_nanosec,
    const std::vector<double>& data) :
    header_sec_(header_sec),
    header_nanosec_(header_nanosec),
    data_(data) { }

  int32_t header_sec() const { return this->header_sec_; }
  int32_t& header_sec() { return this->header_sec_; }
  void header_sec(int32_t _val_) { this->header_sec_ = _val_; }
  uint32_t header_nanosec() const { return this->header_nanosec_; }
  uint32_t& header_nanosec() { return this->header_nanosec_; }
  void header_nanosec(uint32_t _val_) { this->header_nanosec_ = _val_; }
  const std::vector<double>& data() const { return this->data_; }
  std::vector<double>& data() { return this->data_; }
  void data(const std::vector<double>& _val_) { this->data_ = _val_; }
  void data(std::vector<double>&& _val_) { this->data_ = _val_; }

  bool operator==(const Float64Array& _other) const
  {
    (void) _other;
    return header_sec_ == _other.header_sec_ &&
      header_nanosec_ == _other.header_nanosec_ &&
      data_ == _other.data_;
  }

  bool operator!=(const Float64Array& _other) const
  {
    return !(*this == _other);
  }

};

}

}

#include "dds/topic/TopicTraits.hpp"
#include "org/eclipse/cyclonedds/topic/datatopic.hpp"

namespace org {
namespace eclipse {
namespace cyclonedds {
namespace topic {

template <> constexpr const char* TopicTraits<::leju::msgs::Float64>::getTypeName()
{
  return "leju::msgs::Float64";
}

template <> constexpr bool TopicTraits<::leju::msgs::Float64>::isKeyless()
{
  return true;
}

#ifdef DDSCXX_HAS_TYPE_DISCOVERY
template<> constexpr unsigned int TopicTraits<::leju::msgs::Float64>::type_map_blob_sz() { return 298; }
template<> constexpr unsigned int TopicTraits<::leju::msgs::Float64>::type_info_blob_sz() { return 100; }
template<> inline const uint8_t * TopicTraits<::leju::msgs::Float64>::type_map_blob() {
  static const uint8_t blob[] = {
 0x5b,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00,  0xf1,  0xb3,  0x90,  0x32,  0x0f,  0x8e,  0x3b,  0x53, 
 0x44,  0x87,  0x80,  0x2f,  0xdb,  0x6f,  0x07,  0x00,  0x43,  0x00,  0x00,  0x00,  0xf1,  0x51,  0x01,  0x00, 
 0x01,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x33,  0x00,  0x00,  0x00,  0x03,  0x00,  0x00,  0x00, 
 0x0b,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x01,  0x00,  0x04,  0x8d,  0xe9,  0xf3,  0x63,  0x00, 
 0x0b,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00,  0x01,  0x00,  0x07,  0x80,  0xf9,  0xcc,  0x35,  0x00, 
 0x0b,  0x00,  0x00,  0x00,  0x02,  0x00,  0x00,  0x00,  0x01,  0x00,  0x0a,  0x8d,  0x77,  0x7f,  0x38,  0x00, 
 0x9f,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00,  0xf2,  0x4b,  0xc8,  0x82,  0xe7,  0xd8,  0x59,  0x84, 
 0x6a,  0x18,  0x84,  0xd8,  0x6f,  0xac,  0xcb,  0x00,  0x87,  0x00,  0x00,  0x00,  0xf2,  0x51,  0x01,  0x00, 
 0x1c,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x14,  0x00,  0x00,  0x00,  0x6c,  0x65,  0x6a,  0x75, 
 0x3a,  0x3a,  0x6d,  0x73,  0x67,  0x73,  0x3a,  0x3a,  0x46,  0x6c,  0x6f,  0x61,  0x74,  0x36,  0x34,  0x00, 
 0x5f,  0x00,  0x00,  0x00,  0x03,  0x00,  0x00,  0x00,  0x19,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00, 
 0x01,  0x00,  0x04,  0x00,  0x0b,  0x00,  0x00,  0x00,  0x68,  0x65,  0x61,  0x64,  0x65,  0x72,  0x5f,  0x73, 
 0x65,  0x63,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x1d,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00, 
 0x01,  0x00,  0x07,  0x00,  0x0f,  0x00,  0x00,  0x00,  0x68,  0x65,  0x61,  0x64,  0x65,  0x72,  0x5f,  0x6e, 
 0x61,  0x6e,  0x6f,  0x73,  0x65,  0x63,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x13,  0x00,  0x00,  0x00, 
 0x02,  0x00,  0x00,  0x00,  0x01,  0x00,  0x0a,  0x00,  0x05,  0x00,  0x00,  0x00,  0x64,  0x61,  0x74,  0x61, 
 0x00,  0x00,  0x00,  0x00,  0x22,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00,  0xf2,  0x4b,  0xc8,  0x82, 
 0xe7,  0xd8,  0x59,  0x84,  0x6a,  0x18,  0x84,  0xd8,  0x6f,  0xac,  0xcb,  0xf1,  0xb3,  0x90,  0x32,  0x0f, 
 0x8e,  0x3b,  0x53,  0x44,  0x87,  0x80,  0x2f,  0xdb,  0x6f,  0x07, };
  return blob;
}
template<> inline const uint8_t * TopicTraits<::leju::msgs::Float64>::type_info_blob() {
  static const uint8_t blob[] = {
 0x60,  0x00,  0x00,  0x00,  0x01,  0x10,  0x00,  0x40,  0x28,  0x00,  0x00,  0x00,  0x24,  0x00,  0x00,  0x00, 
 0x14,  0x00,  0x00,  0x00,  0xf1,  0xb3,  0x90,  0x32,  0x0f,  0x8e,  0x3b,  0x53,  0x44,  0x87,  0x80,  0x2f, 
 0xdb,  0x6f,  0x07,  0x00,  0x47,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x04,  0x00,  0x00,  0x00, 
 0x00,  0x00,  0x00,  0x00,  0x02,  0x10,  0x00,  0x40,  0x28,  0x00,  0x00,  0x00,  0x24,  0x00,  0x00,  0x00, 
 0x14,  0x00,  0x00,  0x00,  0xf2,  0x4b,  0xc8,  0x82,  0xe7,  0xd8,  0x59,  0x84,  0x6a,  0x18,  0x84,  0xd8, 
 0x6f,  0xac,  0xcb,  0x00,  0x8b,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x04,  0x00,  0x00,  0x00, 
 0x00,  0x00,  0x00,  0x00, };
  return blob;
}
#endif //DDSCXX_HAS_TYPE_DISCOVERY

template <> constexpr const char* TopicTraits<::leju::msgs::Float64Array>::getTypeName()
{
  return "leju::msgs::Float64Array";
}

template <> constexpr bool TopicTraits<::leju::msgs::Float64Array>::isSelfContained()
{
  return false;
}

template <> constexpr bool TopicTraits<::leju::msgs::Float64Array>::isKeyless()
{
  return true;
}

#ifdef DDSCXX_HAS_TYPE_DISCOVERY
template<> constexpr unsigned int TopicTraits<::leju::msgs::Float64Array>::type_map_blob_sz() { return 314; }
template<> constexpr unsigned int TopicTraits<::leju::msgs::Float64Array>::type_info_blob_sz() { return 100; }
template<> inline const uint8_t * TopicTraits<::leju::msgs::Float64Array>::type_map_blob() {
  static const uint8_t blob[] = {
 0x60,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00,  0xf1,  0xb0,  0xcc,  0x5c,  0x9d,  0xb1,  0xe2,  0xa8, 
 0x79,  0x90,  0x53,  0x44,  0x47,  0x2e,  0x70,  0x00,  0x48,  0x00,  0x00,  0x00,  0xf1,  0x51,  0x01,  0x00, 
 0x01,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x38,  0x00,  0x00,  0x00,  0x03,  0x00,  0x00,  0x00, 
 0x0b,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x01,  0x00,  0x04,  0x8d,  0xe9,  0xf3,  0x63,  0x00, 
 0x0b,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00,  0x01,  0x00,  0x07,  0x80,  0xf9,  0xcc,  0x35,  0x00, 
 0x10,  0x00,  0x00,  0x00,  0x02,  0x00,  0x00,  0x00,  0x01,  0x00,  0x80,  0xf3,  0x01,  0x00,  0x00,  0x0a, 
 0x8d,  0x77,  0x7f,  0x38,  0xab,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00,  0xf2,  0xa3,  0xc7,  0x66, 
 0xfe,  0x04,  0x34,  0x8d,  0xb1,  0xb3,  0x28,  0x7f,  0x62,  0x79,  0xf0,  0x00,  0x93,  0x00,  0x00,  0x00, 
 0xf2,  0x51,  0x01,  0x00,  0x21,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x19,  0x00,  0x00,  0x00, 
 0x6c,  0x65,  0x6a,  0x75,  0x3a,  0x3a,  0x6d,  0x73,  0x67,  0x73,  0x3a,  0x3a,  0x46,  0x6c,  0x6f,  0x61, 
 0x74,  0x36,  0x34,  0x41,  0x72,  0x72,  0x61,  0x79,  0x00,  0x00,  0x00,  0x00,  0x63,  0x00,  0x00,  0x00, 
 0x03,  0x00,  0x00,  0x00,  0x19,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x01,  0x00,  0x04,  0x00, 
 0x0b,  0x00,  0x00,  0x00,  0x68,  0x65,  0x61,  0x64,  0x65,  0x72,  0x5f,  0x73,  0x65,  0x63,  0x00,  0x00, 
 0x00,  0x00,  0x00,  0x00,  0x1d,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00,  0x01,  0x00,  0x07,  0x00, 
 0x0f,  0x00,  0x00,  0x00,  0x68,  0x65,  0x61,  0x64,  0x65,  0x72,  0x5f,  0x6e,  0x61,  0x6e,  0x6f,  0x73, 
 0x65,  0x63,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x17,  0x00,  0x00,  0x00,  0x02,  0x00,  0x00,  0x00, 
 0x01,  0x00,  0x80,  0xf3,  0x01,  0x00,  0x00,  0x0a,  0x05,  0x00,  0x00,  0x00,  0x64,  0x61,  0x74,  0x61, 
 0x00,  0x00,  0x00,  0x00,  0x22,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00,  0xf2,  0xa3,  0xc7,  0x66, 
 0xfe,  0x04,  0x34,  0x8d,  0xb1,  0xb3,  0x28,  0x7f,  0x62,  0x79,  0xf0,  0xf1,  0xb0,  0xcc,  0x5c,  0x9d, 
 0xb1,  0xe2,  0xa8,  0x79,  0x90,  0x53,  0x44,  0x47,  0x2e,  0x70, };
  return blob;
}
template<> inline const uint8_t * TopicTraits<::leju::msgs::Float64Array>::type_info_blob() {
  static const uint8_t blob[] = {
 0x60,  0x00,  0x00,  0x00,  0x01,  0x10,  0x00,  0x40,  0x28,  0x00,  0x00,  0x00,  0x24,  0x00,  0x00,  0x00, 
 0x14,  0x00,  0x00,  0x00,  0xf1,  0xb0,  0xcc,  0x5c,  0x9d,  0xb1,  0xe2,  0xa8,  0x79,  0x90,  0x53,  0x44, 
 0x47,  0x2e,  0x70,  0x00,  0x4c,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x04,  0x00,  0x00,  0x00, 
 0x00,  0x00,  0x00,  0x00,  0x02,  0x10,  0x00,  0x40,  0x28,  0x00,  0x00,  0x00,  0x24,  0x00,  0x00,  0x00, 
 0x14,  0x00,  0x00,  0x00,  0xf2,  0xa3,  0xc7,  0x66,  0xfe,  0x04,  0x34,  0x8d,  0xb1,  0xb3,  0x28,  0x7f, 
 0x62,  0x79,  0xf0,  0x00,  0x97,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x04,  0x00,  0x00,  0x00, 
 0x00,  0x00,  0x00,  0x00, };
  return blob;
}
#endif //DDSCXX_HAS_TYPE_DISCOVERY

} //namespace topic
} //namespace cyclonedds
} //namespace eclipse
} //namespace org

namespace dds {
namespace topic {

template <>
struct topic_type_name<::leju::msgs::Float64>
{
    static std::string value()
    {
      return org::eclipse::cyclonedds::topic::TopicTraits<::leju::msgs::Float64>::getTypeName();
    }
};

template <>
struct topic_type_name<::leju::msgs::Float64Array>
{
    static std::string value()
    {
      return org::eclipse::cyclonedds::topic::TopicTraits<::leju::msgs::Float64Array>::getTypeName();
    }
};

}
}

REGISTER_TOPIC_TYPE(::leju::msgs::Float64)
REGISTER_TOPIC_TYPE(::leju::msgs::Float64Array)

namespace org{
namespace eclipse{
namespace cyclonedds{
namespace core{
namespace cdr{

template<>
propvec &get_type_props<::leju::msgs::Float64>();

template<typename T, std::enable_if_t<std::is_base_of<cdr_stream, T>::value, bool> = true >
bool write(T& streamer, const ::leju::msgs::Float64& instance, entity_properties_t *props) {
  (void)instance;
  if (!streamer.start_struct(*props))
    return false;
  auto prop = streamer.first_entity(props);
  while (prop) {
    switch (prop->m_id) {
      case 0:
      if (!streamer.start_member(*prop))
        return false;
      if (!write(streamer, instance.header_sec()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 1:
      if (!streamer.start_member(*prop))
        return false;
      if (!write(streamer, instance.header_nanosec()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 2:
      if (!streamer.start_member(*prop))
        return false;
      if (!write(streamer, instance.data()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
    }
    prop = streamer.next_entity(prop);
  }
  return streamer.finish_struct(*props);
}

template<typename S, std::enable_if_t<std::is_base_of<cdr_stream, S>::value, bool> = true >
bool write(S& str, const ::leju::msgs::Float64& instance, bool as_key) {
  auto &props = get_type_props<::leju::msgs::Float64>();
  str.set_mode(cdr_stream::stream_mode::write, as_key);
  return write(str, instance, props.data()); 
}

template<typename T, std::enable_if_t<std::is_base_of<cdr_stream, T>::value, bool> = true >
bool read(T& streamer, ::leju::msgs::Float64& instance, entity_properties_t *props) {
  (void)instance;
  if (!streamer.start_struct(*props))
    return false;
  auto prop = streamer.first_entity(props);
  while (prop) {
    switch (prop->m_id) {
      case 0:
      if (!streamer.start_member(*prop))
        return false;
      if (!read(streamer, instance.header_sec()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 1:
      if (!streamer.start_member(*prop))
        return false;
      if (!read(streamer, instance.header_nanosec()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 2:
      if (!streamer.start_member(*prop))
        return false;
      if (!read(streamer, instance.data()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
    }
    prop = streamer.next_entity(prop);
  }
  return streamer.finish_struct(*props);
}

template<typename S, std::enable_if_t<std::is_base_of<cdr_stream, S>::value, bool> = true >
bool read(S& str, ::leju::msgs::Float64& instance, bool as_key) {
  auto &props = get_type_props<::leju::msgs::Float64>();
  str.set_mode(cdr_stream::stream_mode::read, as_key);
  return read(str, instance, props.data()); 
}

template<typename T, std::enable_if_t<std::is_base_of<cdr_stream, T>::value, bool> = true >
bool move(T& streamer, const ::leju::msgs::Float64& instance, entity_properties_t *props) {
  (void)instance;
  if (!streamer.start_struct(*props))
    return false;
  auto prop = streamer.first_entity(props);
  while (prop) {
    switch (prop->m_id) {
      case 0:
      if (!streamer.start_member(*prop))
        return false;
      if (!move(streamer, instance.header_sec()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 1:
      if (!streamer.start_member(*prop))
        return false;
      if (!move(streamer, instance.header_nanosec()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 2:
      if (!streamer.start_member(*prop))
        return false;
      if (!move(streamer, instance.data()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
    }
    prop = streamer.next_entity(prop);
  }
  return streamer.finish_struct(*props);
}

template<typename S, std::enable_if_t<std::is_base_of<cdr_stream, S>::value, bool> = true >
bool move(S& str, const ::leju::msgs::Float64& instance, bool as_key) {
  auto &props = get_type_props<::leju::msgs::Float64>();
  str.set_mode(cdr_stream::stream_mode::move, as_key);
  return move(str, instance, props.data()); 
}

template<typename T, std::enable_if_t<std::is_base_of<cdr_stream, T>::value, bool> = true >
bool max(T& streamer, const ::leju::msgs::Float64& instance, entity_properties_t *props) {
  (void)instance;
  if (!streamer.start_struct(*props))
    return false;
  auto prop = streamer.first_entity(props);
  while (prop) {
    switch (prop->m_id) {
      case 0:
      if (!streamer.start_member(*prop))
        return false;
      if (!max(streamer, instance.header_sec()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 1:
      if (!streamer.start_member(*prop))
        return false;
      if (!max(streamer, instance.header_nanosec()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 2:
      if (!streamer.start_member(*prop))
        return false;
      if (!max(streamer, instance.data()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
    }
    prop = streamer.next_entity(prop);
  }
  return streamer.finish_struct(*props);
}

template<typename S, std::enable_if_t<std::is_base_of<cdr_stream, S>::value, bool> = true >
bool max(S& str, const ::leju::msgs::Float64& instance, bool as_key) {
  auto &props = get_type_props<::leju::msgs::Float64>();
  str.set_mode(cdr_stream::stream_mode::max, as_key);
  return max(str, instance, props.data()); 
}

template<>
propvec &get_type_props<::leju::msgs::Float64Array>();

template<typename T, std::enable_if_t<std::is_base_of<cdr_stream, T>::value, bool> = true >
bool write(T& streamer, const ::leju::msgs::Float64Array& instance, entity_properties_t *props) {
  (void)instance;
  if (!streamer.start_struct(*props))
    return false;
  auto prop = streamer.first_entity(props);
  while (prop) {
    switch (prop->m_id) {
      case 0:
      if (!streamer.start_member(*prop))
        return false;
      if (!write(streamer, instance.header_sec()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 1:
      if (!streamer.start_member(*prop))
        return false;
      if (!write(streamer, instance.header_nanosec()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 2:
      if (!streamer.start_member(*prop))
        return false;
      if (!streamer.start_consecutive(false, true))
        return false;
      {
      uint32_t se_1 = uint32_t(instance.data().size());
      if (!write(streamer, se_1))
        return false;
      if (se_1 > 0 &&
          !write(streamer, instance.data()[0], se_1))
        return false;
      }  //end sequence 1
      if (!streamer.finish_consecutive())
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
    }
    prop = streamer.next_entity(prop);
  }
  return streamer.finish_struct(*props);
}

template<typename S, std::enable_if_t<std::is_base_of<cdr_stream, S>::value, bool> = true >
bool write(S& str, const ::leju::msgs::Float64Array& instance, bool as_key) {
  auto &props = get_type_props<::leju::msgs::Float64Array>();
  str.set_mode(cdr_stream::stream_mode::write, as_key);
  return write(str, instance, props.data()); 
}

template<typename T, std::enable_if_t<std::is_base_of<cdr_stream, T>::value, bool> = true >
bool read(T& streamer, ::leju::msgs::Float64Array& instance, entity_properties_t *props) {
  (void)instance;
  if (!streamer.start_struct(*props))
    return false;
  auto prop = streamer.first_entity(props);
  while (prop) {
    switch (prop->m_id) {
      case 0:
      if (!streamer.start_member(*prop))
        return false;
      if (!read(streamer, instance.header_sec()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 1:
      if (!streamer.start_member(*prop))
        return false;
      if (!read(streamer, instance.header_nanosec()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 2:
      if (!streamer.start_member(*prop))
        return false;
      if (!streamer.start_consecutive(false, true))
        return false;
      {
      uint32_t se_1 = uint32_t(instance.data().size());
      if (!read(streamer, se_1))
        return false;
      instance.data().resize(se_1);
      if (se_1 > 0 &&
          !read(streamer, instance.data()[0], se_1))
        return false;
      }  //end sequence 1
      if (!streamer.finish_consecutive())
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
    }
    prop = streamer.next_entity(prop);
  }
  return streamer.finish_struct(*props);
}

template<typename S, std::enable_if_t<std::is_base_of<cdr_stream, S>::value, bool> = true >
bool read(S& str, ::leju::msgs::Float64Array& instance, bool as_key) {
  auto &props = get_type_props<::leju::msgs::Float64Array>();
  str.set_mode(cdr_stream::stream_mode::read, as_key);
  return read(str, instance, props.data()); 
}

template<typename T, std::enable_if_t<std::is_base_of<cdr_stream, T>::value, bool> = true >
bool move(T& streamer, const ::leju::msgs::Float64Array& instance, entity_properties_t *props) {
  (void)instance;
  if (!streamer.start_struct(*props))
    return false;
  auto prop = streamer.first_entity(props);
  while (prop) {
    switch (prop->m_id) {
      case 0:
      if (!streamer.start_member(*prop))
        return false;
      if (!move(streamer, instance.header_sec()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 1:
      if (!streamer.start_member(*prop))
        return false;
      if (!move(streamer, instance.header_nanosec()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 2:
      if (!streamer.start_member(*prop))
        return false;
      if (!streamer.start_consecutive(false, true))
        return false;
      {
      uint32_t se_1 = uint32_t(instance.data().size());
      if (!move(streamer, se_1))
        return false;
      if (se_1 > 0 &&
          !move(streamer, double(), se_1))
        return false;
      }  //end sequence 1
      if (!streamer.finish_consecutive())
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
    }
    prop = streamer.next_entity(prop);
  }
  return streamer.finish_struct(*props);
}

template<typename S, std::enable_if_t<std::is_base_of<cdr_stream, S>::value, bool> = true >
bool move(S& str, const ::leju::msgs::Float64Array& instance, bool as_key) {
  auto &props = get_type_props<::leju::msgs::Float64Array>();
  str.set_mode(cdr_stream::stream_mode::move, as_key);
  return move(str, instance, props.data()); 
}

template<typename T, std::enable_if_t<std::is_base_of<cdr_stream, T>::value, bool> = true >
bool max(T& streamer, const ::leju::msgs::Float64Array& instance, entity_properties_t *props) {
  (void)instance;
  if (!streamer.start_struct(*props))
    return false;
  auto prop = streamer.first_entity(props);
  while (prop) {
    switch (prop->m_id) {
      case 0:
      if (!streamer.start_member(*prop))
        return false;
      if (!max(streamer, instance.header_sec()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 1:
      if (!streamer.start_member(*prop))
        return false;
      if (!max(streamer, instance.header_nanosec()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 2:
      if (!streamer.start_member(*prop))
        return false;
      if (!streamer.start_consecutive(false, true))
        return false;
      {
      uint32_t se_1 = 0;
      if (!max(streamer, se_1))
        return false;
      if (se_1 > 0 &&
          !max(streamer, double(), se_1))
        return false;
      }  //end sequence 1
      if (!streamer.finish_consecutive())
        return false;
      streamer.position(SIZE_MAX);
      if (!streamer.finish_member(*prop))
        return false;
      break;
    }
    prop = streamer.next_entity(prop);
  }
  return streamer.finish_struct(*props);
}

template<typename S, std::enable_if_t<std::is_base_of<cdr_stream, S>::value, bool> = true >
bool max(S& str, const ::leju::msgs::Float64Array& instance, bool as_key) {
  auto &props = get_type_props<::leju::msgs::Float64Array>();
  str.set_mode(cdr_stream::stream_mode::max, as_key);
  return max(str, instance, props.data()); 
}

} //namespace cdr
} //namespace core
} //namespace cyclonedds
} //namespace eclipse
} //namespace org

#endif // DDSCXX_FLOAT64TYPES_HPP
