// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/hand_wrench_srv.proto

#include "hand_wrench_srv.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
extern PROTOBUF_INTERNAL_EXPORT_protos_2fhand_5fwrench_5fsrv_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_ItemMassForce_protos_2fhand_5fwrench_5fsrv_2eproto;
namespace protos {
class ItemMassForceDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<ItemMassForce> _instance;
} _ItemMassForce_default_instance_;
class ItemMassForceRequestDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<ItemMassForceRequest> _instance;
} _ItemMassForceRequest_default_instance_;
class ItemMassForceResponseDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<ItemMassForceResponse> _instance;
} _ItemMassForceResponse_default_instance_;
}  // namespace protos
static void InitDefaultsscc_info_ItemMassForce_protos_2fhand_5fwrench_5fsrv_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::protos::_ItemMassForce_default_instance_;
    new (ptr) ::protos::ItemMassForce();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::protos::ItemMassForce::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_ItemMassForce_protos_2fhand_5fwrench_5fsrv_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_ItemMassForce_protos_2fhand_5fwrench_5fsrv_2eproto}, {}};

static void InitDefaultsscc_info_ItemMassForceRequest_protos_2fhand_5fwrench_5fsrv_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::protos::_ItemMassForceRequest_default_instance_;
    new (ptr) ::protos::ItemMassForceRequest();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::protos::ItemMassForceRequest::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<1> scc_info_ItemMassForceRequest_protos_2fhand_5fwrench_5fsrv_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 1, 0, InitDefaultsscc_info_ItemMassForceRequest_protos_2fhand_5fwrench_5fsrv_2eproto}, {
      &scc_info_ItemMassForce_protos_2fhand_5fwrench_5fsrv_2eproto.base,}};

static void InitDefaultsscc_info_ItemMassForceResponse_protos_2fhand_5fwrench_5fsrv_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::protos::_ItemMassForceResponse_default_instance_;
    new (ptr) ::protos::ItemMassForceResponse();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::protos::ItemMassForceResponse::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<1> scc_info_ItemMassForceResponse_protos_2fhand_5fwrench_5fsrv_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 1, 0, InitDefaultsscc_info_ItemMassForceResponse_protos_2fhand_5fwrench_5fsrv_2eproto}, {
      &scc_info_ItemMassForce_protos_2fhand_5fwrench_5fsrv_2eproto.base,}};

static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_protos_2fhand_5fwrench_5fsrv_2eproto[3];
static const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* file_level_enum_descriptors_protos_2fhand_5fwrench_5fsrv_2eproto[2];
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_protos_2fhand_5fwrench_5fsrv_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_protos_2fhand_5fwrench_5fsrv_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::protos::ItemMassForce, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::protos::ItemMassForce, case_name_),
  PROTOBUF_FIELD_OFFSET(::protos::ItemMassForce, description_),
  PROTOBUF_FIELD_OFFSET(::protos::ItemMassForce, item_mass_),
  PROTOBUF_FIELD_OFFSET(::protos::ItemMassForce, lforce_x_),
  PROTOBUF_FIELD_OFFSET(::protos::ItemMassForce, lforce_y_),
  PROTOBUF_FIELD_OFFSET(::protos::ItemMassForce, lforce_z_),
  PROTOBUF_FIELD_OFFSET(::protos::ItemMassForceRequest, _has_bits_),
  PROTOBUF_FIELD_OFFSET(::protos::ItemMassForceRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::protos::ItemMassForceRequest, operation_),
  PROTOBUF_FIELD_OFFSET(::protos::ItemMassForceRequest, data_),
  ~0u,
  0,
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::protos::ItemMassForceResponse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::protos::ItemMassForceResponse, operation_),
  PROTOBUF_FIELD_OFFSET(::protos::ItemMassForceResponse, status_),
  PROTOBUF_FIELD_OFFSET(::protos::ItemMassForceResponse, description_),
  PROTOBUF_FIELD_OFFSET(::protos::ItemMassForceResponse, item_mass_forces_),
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::protos::ItemMassForce)},
  { 11, 18, sizeof(::protos::ItemMassForceRequest)},
  { 20, -1, sizeof(::protos::ItemMassForceResponse)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::protos::_ItemMassForce_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::protos::_ItemMassForceRequest_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::protos::_ItemMassForceResponse_default_instance_),
};

const char descriptor_table_protodef_protos_2fhand_5fwrench_5fsrv_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\034protos/hand_wrench_srv.proto\022\006protos\"\200"
  "\001\n\rItemMassForce\022\021\n\tcase_name\030\001 \001(\t\022\023\n\013d"
  "escription\030\002 \001(\t\022\021\n\titem_mass\030\003 \001(\001\022\020\n\010l"
  "force_x\030\004 \001(\001\022\020\n\010lforce_y\030\005 \001(\001\022\020\n\010lforc"
  "e_z\030\006 \001(\001\"|\n\024ItemMassForceRequest\0221\n\tope"
  "ration\030\001 \001(\0162\036.protos.ItemMassForceOpera"
  "tion\022(\n\004data\030\002 \001(\0132\025.protos.ItemMassForc"
  "eH\000\210\001\001B\007\n\005_data\"\234\002\n\025ItemMassForceRespons"
  "e\0221\n\toperation\030\001 \001(\0162\036.protos.ItemMassFo"
  "rceOperation\022=\n\006status\030\002 \001(\0162-.protos.It"
  "emMassForceResponse.OperationStatus\022\023\n\013d"
  "escription\030\003 \001(\t\022/\n\020item_mass_forces\030\004 \003"
  "(\0132\025.protos.ItemMassForce\"K\n\017OperationSt"
  "atus\022\013\n\007SUCCESS\020\000\022\t\n\005ERROR\020\001\022\013\n\007TIMEOUT\020"
  "\002\022\023\n\017INVALID_REQUEST\020\003**\n\026ItemMassForceO"
  "peration\022\007\n\003GET\020\000\022\007\n\003SET\020\001b\006proto3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_protos_2fhand_5fwrench_5fsrv_2eproto_deps[1] = {
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_protos_2fhand_5fwrench_5fsrv_2eproto_sccs[3] = {
  &scc_info_ItemMassForce_protos_2fhand_5fwrench_5fsrv_2eproto.base,
  &scc_info_ItemMassForceRequest_protos_2fhand_5fwrench_5fsrv_2eproto.base,
  &scc_info_ItemMassForceResponse_protos_2fhand_5fwrench_5fsrv_2eproto.base,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_protos_2fhand_5fwrench_5fsrv_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_protos_2fhand_5fwrench_5fsrv_2eproto = {
  false, false, descriptor_table_protodef_protos_2fhand_5fwrench_5fsrv_2eproto, "protos/hand_wrench_srv.proto", 634,
  &descriptor_table_protos_2fhand_5fwrench_5fsrv_2eproto_once, descriptor_table_protos_2fhand_5fwrench_5fsrv_2eproto_sccs, descriptor_table_protos_2fhand_5fwrench_5fsrv_2eproto_deps, 3, 0,
  schemas, file_default_instances, TableStruct_protos_2fhand_5fwrench_5fsrv_2eproto::offsets,
  file_level_metadata_protos_2fhand_5fwrench_5fsrv_2eproto, 3, file_level_enum_descriptors_protos_2fhand_5fwrench_5fsrv_2eproto, file_level_service_descriptors_protos_2fhand_5fwrench_5fsrv_2eproto,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_protos_2fhand_5fwrench_5fsrv_2eproto = (static_cast<void>(::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_protos_2fhand_5fwrench_5fsrv_2eproto)), true);
namespace protos {
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ItemMassForceResponse_OperationStatus_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_protos_2fhand_5fwrench_5fsrv_2eproto);
  return file_level_enum_descriptors_protos_2fhand_5fwrench_5fsrv_2eproto[0];
}
bool ItemMassForceResponse_OperationStatus_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
      return true;
    default:
      return false;
  }
}

#if (__cplusplus < 201703) && (!defined(_MSC_VER) || _MSC_VER >= 1900)
constexpr ItemMassForceResponse_OperationStatus ItemMassForceResponse::SUCCESS;
constexpr ItemMassForceResponse_OperationStatus ItemMassForceResponse::ERROR;
constexpr ItemMassForceResponse_OperationStatus ItemMassForceResponse::TIMEOUT;
constexpr ItemMassForceResponse_OperationStatus ItemMassForceResponse::INVALID_REQUEST;
constexpr ItemMassForceResponse_OperationStatus ItemMassForceResponse::OperationStatus_MIN;
constexpr ItemMassForceResponse_OperationStatus ItemMassForceResponse::OperationStatus_MAX;
constexpr int ItemMassForceResponse::OperationStatus_ARRAYSIZE;
#endif  // (__cplusplus < 201703) && (!defined(_MSC_VER) || _MSC_VER >= 1900)
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ItemMassForceOperation_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_protos_2fhand_5fwrench_5fsrv_2eproto);
  return file_level_enum_descriptors_protos_2fhand_5fwrench_5fsrv_2eproto[1];
}
bool ItemMassForceOperation_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
      return true;
    default:
      return false;
  }
}


// ===================================================================

void ItemMassForce::InitAsDefaultInstance() {
}
class ItemMassForce::_Internal {
 public:
};

ItemMassForce::ItemMassForce(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:protos.ItemMassForce)
}
ItemMassForce::ItemMassForce(const ItemMassForce& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  case_name_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_case_name().empty()) {
    case_name_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from._internal_case_name(),
      GetArena());
  }
  description_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_description().empty()) {
    description_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from._internal_description(),
      GetArena());
  }
  ::memcpy(&item_mass_, &from.item_mass_,
    static_cast<size_t>(reinterpret_cast<char*>(&lforce_z_) -
    reinterpret_cast<char*>(&item_mass_)) + sizeof(lforce_z_));
  // @@protoc_insertion_point(copy_constructor:protos.ItemMassForce)
}

void ItemMassForce::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_ItemMassForce_protos_2fhand_5fwrench_5fsrv_2eproto.base);
  case_name_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  description_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  ::memset(&item_mass_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&lforce_z_) -
      reinterpret_cast<char*>(&item_mass_)) + sizeof(lforce_z_));
}

ItemMassForce::~ItemMassForce() {
  // @@protoc_insertion_point(destructor:protos.ItemMassForce)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void ItemMassForce::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  case_name_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  description_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void ItemMassForce::ArenaDtor(void* object) {
  ItemMassForce* _this = reinterpret_cast< ItemMassForce* >(object);
  (void)_this;
}
void ItemMassForce::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void ItemMassForce::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ItemMassForce& ItemMassForce::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_ItemMassForce_protos_2fhand_5fwrench_5fsrv_2eproto.base);
  return *internal_default_instance();
}


void ItemMassForce::Clear() {
// @@protoc_insertion_point(message_clear_start:protos.ItemMassForce)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  case_name_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  description_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  ::memset(&item_mass_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&lforce_z_) -
      reinterpret_cast<char*>(&item_mass_)) + sizeof(lforce_z_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* ItemMassForce::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // string case_name = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          auto str = _internal_mutable_case_name();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "protos.ItemMassForce.case_name"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // string description = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 18)) {
          auto str = _internal_mutable_description();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "protos.ItemMassForce.description"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // double item_mass = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 25)) {
          item_mass_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else goto handle_unusual;
        continue;
      // double lforce_x = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 33)) {
          lforce_x_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else goto handle_unusual;
        continue;
      // double lforce_y = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 41)) {
          lforce_y_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else goto handle_unusual;
        continue;
      // double lforce_z = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 49)) {
          lforce_z_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* ItemMassForce::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:protos.ItemMassForce)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string case_name = 1;
  if (this->case_name().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_case_name().data(), static_cast<int>(this->_internal_case_name().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "protos.ItemMassForce.case_name");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_case_name(), target);
  }

  // string description = 2;
  if (this->description().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_description().data(), static_cast<int>(this->_internal_description().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "protos.ItemMassForce.description");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_description(), target);
  }

  // double item_mass = 3;
  if (!(this->item_mass() <= 0 && this->item_mass() >= 0)) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteDoubleToArray(3, this->_internal_item_mass(), target);
  }

  // double lforce_x = 4;
  if (!(this->lforce_x() <= 0 && this->lforce_x() >= 0)) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteDoubleToArray(4, this->_internal_lforce_x(), target);
  }

  // double lforce_y = 5;
  if (!(this->lforce_y() <= 0 && this->lforce_y() >= 0)) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteDoubleToArray(5, this->_internal_lforce_y(), target);
  }

  // double lforce_z = 6;
  if (!(this->lforce_z() <= 0 && this->lforce_z() >= 0)) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteDoubleToArray(6, this->_internal_lforce_z(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:protos.ItemMassForce)
  return target;
}

size_t ItemMassForce::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:protos.ItemMassForce)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string case_name = 1;
  if (this->case_name().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_case_name());
  }

  // string description = 2;
  if (this->description().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_description());
  }

  // double item_mass = 3;
  if (!(this->item_mass() <= 0 && this->item_mass() >= 0)) {
    total_size += 1 + 8;
  }

  // double lforce_x = 4;
  if (!(this->lforce_x() <= 0 && this->lforce_x() >= 0)) {
    total_size += 1 + 8;
  }

  // double lforce_y = 5;
  if (!(this->lforce_y() <= 0 && this->lforce_y() >= 0)) {
    total_size += 1 + 8;
  }

  // double lforce_z = 6;
  if (!(this->lforce_z() <= 0 && this->lforce_z() >= 0)) {
    total_size += 1 + 8;
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void ItemMassForce::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:protos.ItemMassForce)
  GOOGLE_DCHECK_NE(&from, this);
  const ItemMassForce* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<ItemMassForce>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:protos.ItemMassForce)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:protos.ItemMassForce)
    MergeFrom(*source);
  }
}

void ItemMassForce::MergeFrom(const ItemMassForce& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:protos.ItemMassForce)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.case_name().size() > 0) {
    _internal_set_case_name(from._internal_case_name());
  }
  if (from.description().size() > 0) {
    _internal_set_description(from._internal_description());
  }
  if (!(from.item_mass() <= 0 && from.item_mass() >= 0)) {
    _internal_set_item_mass(from._internal_item_mass());
  }
  if (!(from.lforce_x() <= 0 && from.lforce_x() >= 0)) {
    _internal_set_lforce_x(from._internal_lforce_x());
  }
  if (!(from.lforce_y() <= 0 && from.lforce_y() >= 0)) {
    _internal_set_lforce_y(from._internal_lforce_y());
  }
  if (!(from.lforce_z() <= 0 && from.lforce_z() >= 0)) {
    _internal_set_lforce_z(from._internal_lforce_z());
  }
}

void ItemMassForce::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:protos.ItemMassForce)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ItemMassForce::CopyFrom(const ItemMassForce& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:protos.ItemMassForce)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ItemMassForce::IsInitialized() const {
  return true;
}

void ItemMassForce::InternalSwap(ItemMassForce* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  case_name_.Swap(&other->case_name_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  description_.Swap(&other->description_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(ItemMassForce, lforce_z_)
      + sizeof(ItemMassForce::lforce_z_)
      - PROTOBUF_FIELD_OFFSET(ItemMassForce, item_mass_)>(
          reinterpret_cast<char*>(&item_mass_),
          reinterpret_cast<char*>(&other->item_mass_));
}

::PROTOBUF_NAMESPACE_ID::Metadata ItemMassForce::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

void ItemMassForceRequest::InitAsDefaultInstance() {
  ::protos::_ItemMassForceRequest_default_instance_._instance.get_mutable()->data_ = const_cast< ::protos::ItemMassForce*>(
      ::protos::ItemMassForce::internal_default_instance());
}
class ItemMassForceRequest::_Internal {
 public:
  using HasBits = decltype(std::declval<ItemMassForceRequest>()._has_bits_);
  static const ::protos::ItemMassForce& data(const ItemMassForceRequest* msg);
  static void set_has_data(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
};

const ::protos::ItemMassForce&
ItemMassForceRequest::_Internal::data(const ItemMassForceRequest* msg) {
  return *msg->data_;
}
ItemMassForceRequest::ItemMassForceRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:protos.ItemMassForceRequest)
}
ItemMassForceRequest::ItemMassForceRequest(const ItemMassForceRequest& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _has_bits_(from._has_bits_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_data()) {
    data_ = new ::protos::ItemMassForce(*from.data_);
  } else {
    data_ = nullptr;
  }
  operation_ = from.operation_;
  // @@protoc_insertion_point(copy_constructor:protos.ItemMassForceRequest)
}

void ItemMassForceRequest::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_ItemMassForceRequest_protos_2fhand_5fwrench_5fsrv_2eproto.base);
  ::memset(&data_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&operation_) -
      reinterpret_cast<char*>(&data_)) + sizeof(operation_));
}

ItemMassForceRequest::~ItemMassForceRequest() {
  // @@protoc_insertion_point(destructor:protos.ItemMassForceRequest)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void ItemMassForceRequest::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  if (this != internal_default_instance()) delete data_;
}

void ItemMassForceRequest::ArenaDtor(void* object) {
  ItemMassForceRequest* _this = reinterpret_cast< ItemMassForceRequest* >(object);
  (void)_this;
}
void ItemMassForceRequest::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void ItemMassForceRequest::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ItemMassForceRequest& ItemMassForceRequest::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_ItemMassForceRequest_protos_2fhand_5fwrench_5fsrv_2eproto.base);
  return *internal_default_instance();
}


void ItemMassForceRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:protos.ItemMassForceRequest)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    if (GetArena() == nullptr && data_ != nullptr) {
      delete data_;
    }
    data_ = nullptr;
  }
  operation_ = 0;
  _has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* ItemMassForceRequest::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // .protos.ItemMassForceOperation operation = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8)) {
          ::PROTOBUF_NAMESPACE_ID::uint64 val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_operation(static_cast<::protos::ItemMassForceOperation>(val));
        } else goto handle_unusual;
        continue;
      // .protos.ItemMassForce data = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 18)) {
          ptr = ctx->ParseMessage(_internal_mutable_data(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  _has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* ItemMassForceRequest::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:protos.ItemMassForceRequest)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .protos.ItemMassForceOperation operation = 1;
  if (this->operation() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteEnumToArray(
      1, this->_internal_operation(), target);
  }

  // .protos.ItemMassForce data = 2;
  if (_internal_has_data()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        2, _Internal::data(this), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:protos.ItemMassForceRequest)
  return target;
}

size_t ItemMassForceRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:protos.ItemMassForceRequest)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .protos.ItemMassForce data = 2;
  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *data_);
  }

  // .protos.ItemMassForceOperation operation = 1;
  if (this->operation() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::EnumSize(this->_internal_operation());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void ItemMassForceRequest::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:protos.ItemMassForceRequest)
  GOOGLE_DCHECK_NE(&from, this);
  const ItemMassForceRequest* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<ItemMassForceRequest>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:protos.ItemMassForceRequest)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:protos.ItemMassForceRequest)
    MergeFrom(*source);
  }
}

void ItemMassForceRequest::MergeFrom(const ItemMassForceRequest& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:protos.ItemMassForceRequest)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_has_data()) {
    _internal_mutable_data()->::protos::ItemMassForce::MergeFrom(from._internal_data());
  }
  if (from.operation() != 0) {
    _internal_set_operation(from._internal_operation());
  }
}

void ItemMassForceRequest::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:protos.ItemMassForceRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ItemMassForceRequest::CopyFrom(const ItemMassForceRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:protos.ItemMassForceRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ItemMassForceRequest::IsInitialized() const {
  return true;
}

void ItemMassForceRequest::InternalSwap(ItemMassForceRequest* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(ItemMassForceRequest, operation_)
      + sizeof(ItemMassForceRequest::operation_)
      - PROTOBUF_FIELD_OFFSET(ItemMassForceRequest, data_)>(
          reinterpret_cast<char*>(&data_),
          reinterpret_cast<char*>(&other->data_));
}

::PROTOBUF_NAMESPACE_ID::Metadata ItemMassForceRequest::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

void ItemMassForceResponse::InitAsDefaultInstance() {
}
class ItemMassForceResponse::_Internal {
 public:
};

ItemMassForceResponse::ItemMassForceResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena),
  item_mass_forces_(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:protos.ItemMassForceResponse)
}
ItemMassForceResponse::ItemMassForceResponse(const ItemMassForceResponse& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      item_mass_forces_(from.item_mass_forces_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  description_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_description().empty()) {
    description_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from._internal_description(),
      GetArena());
  }
  ::memcpy(&operation_, &from.operation_,
    static_cast<size_t>(reinterpret_cast<char*>(&status_) -
    reinterpret_cast<char*>(&operation_)) + sizeof(status_));
  // @@protoc_insertion_point(copy_constructor:protos.ItemMassForceResponse)
}

void ItemMassForceResponse::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_ItemMassForceResponse_protos_2fhand_5fwrench_5fsrv_2eproto.base);
  description_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  ::memset(&operation_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&status_) -
      reinterpret_cast<char*>(&operation_)) + sizeof(status_));
}

ItemMassForceResponse::~ItemMassForceResponse() {
  // @@protoc_insertion_point(destructor:protos.ItemMassForceResponse)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void ItemMassForceResponse::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  description_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void ItemMassForceResponse::ArenaDtor(void* object) {
  ItemMassForceResponse* _this = reinterpret_cast< ItemMassForceResponse* >(object);
  (void)_this;
}
void ItemMassForceResponse::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void ItemMassForceResponse::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ItemMassForceResponse& ItemMassForceResponse::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_ItemMassForceResponse_protos_2fhand_5fwrench_5fsrv_2eproto.base);
  return *internal_default_instance();
}


void ItemMassForceResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:protos.ItemMassForceResponse)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  item_mass_forces_.Clear();
  description_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  ::memset(&operation_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&status_) -
      reinterpret_cast<char*>(&operation_)) + sizeof(status_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* ItemMassForceResponse::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // .protos.ItemMassForceOperation operation = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8)) {
          ::PROTOBUF_NAMESPACE_ID::uint64 val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_operation(static_cast<::protos::ItemMassForceOperation>(val));
        } else goto handle_unusual;
        continue;
      // .protos.ItemMassForceResponse.OperationStatus status = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 16)) {
          ::PROTOBUF_NAMESPACE_ID::uint64 val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_status(static_cast<::protos::ItemMassForceResponse_OperationStatus>(val));
        } else goto handle_unusual;
        continue;
      // string description = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 26)) {
          auto str = _internal_mutable_description();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "protos.ItemMassForceResponse.description"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // repeated .protos.ItemMassForce item_mass_forces = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 34)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_item_mass_forces(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<34>(ptr));
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* ItemMassForceResponse::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:protos.ItemMassForceResponse)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .protos.ItemMassForceOperation operation = 1;
  if (this->operation() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteEnumToArray(
      1, this->_internal_operation(), target);
  }

  // .protos.ItemMassForceResponse.OperationStatus status = 2;
  if (this->status() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteEnumToArray(
      2, this->_internal_status(), target);
  }

  // string description = 3;
  if (this->description().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_description().data(), static_cast<int>(this->_internal_description().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "protos.ItemMassForceResponse.description");
    target = stream->WriteStringMaybeAliased(
        3, this->_internal_description(), target);
  }

  // repeated .protos.ItemMassForce item_mass_forces = 4;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->_internal_item_mass_forces_size()); i < n; i++) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(4, this->_internal_item_mass_forces(i), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:protos.ItemMassForceResponse)
  return target;
}

size_t ItemMassForceResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:protos.ItemMassForceResponse)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .protos.ItemMassForce item_mass_forces = 4;
  total_size += 1UL * this->_internal_item_mass_forces_size();
  for (const auto& msg : this->item_mass_forces_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // string description = 3;
  if (this->description().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_description());
  }

  // .protos.ItemMassForceOperation operation = 1;
  if (this->operation() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::EnumSize(this->_internal_operation());
  }

  // .protos.ItemMassForceResponse.OperationStatus status = 2;
  if (this->status() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::EnumSize(this->_internal_status());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void ItemMassForceResponse::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:protos.ItemMassForceResponse)
  GOOGLE_DCHECK_NE(&from, this);
  const ItemMassForceResponse* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<ItemMassForceResponse>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:protos.ItemMassForceResponse)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:protos.ItemMassForceResponse)
    MergeFrom(*source);
  }
}

void ItemMassForceResponse::MergeFrom(const ItemMassForceResponse& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:protos.ItemMassForceResponse)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  item_mass_forces_.MergeFrom(from.item_mass_forces_);
  if (from.description().size() > 0) {
    _internal_set_description(from._internal_description());
  }
  if (from.operation() != 0) {
    _internal_set_operation(from._internal_operation());
  }
  if (from.status() != 0) {
    _internal_set_status(from._internal_status());
  }
}

void ItemMassForceResponse::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:protos.ItemMassForceResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ItemMassForceResponse::CopyFrom(const ItemMassForceResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:protos.ItemMassForceResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ItemMassForceResponse::IsInitialized() const {
  return true;
}

void ItemMassForceResponse::InternalSwap(ItemMassForceResponse* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  item_mass_forces_.InternalSwap(&other->item_mass_forces_);
  description_.Swap(&other->description_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(ItemMassForceResponse, status_)
      + sizeof(ItemMassForceResponse::status_)
      - PROTOBUF_FIELD_OFFSET(ItemMassForceResponse, operation_)>(
          reinterpret_cast<char*>(&operation_),
          reinterpret_cast<char*>(&other->operation_));
}

::PROTOBUF_NAMESPACE_ID::Metadata ItemMassForceResponse::GetMetadata() const {
  return GetMetadataStatic();
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace protos
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::protos::ItemMassForce* Arena::CreateMaybeMessage< ::protos::ItemMassForce >(Arena* arena) {
  return Arena::CreateMessageInternal< ::protos::ItemMassForce >(arena);
}
template<> PROTOBUF_NOINLINE ::protos::ItemMassForceRequest* Arena::CreateMaybeMessage< ::protos::ItemMassForceRequest >(Arena* arena) {
  return Arena::CreateMessageInternal< ::protos::ItemMassForceRequest >(arena);
}
template<> PROTOBUF_NOINLINE ::protos::ItemMassForceResponse* Arena::CreateMaybeMessage< ::protos::ItemMassForceResponse >(Arena* arena) {
  return Arena::CreateMessageInternal< ::protos::ItemMassForceResponse >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
