// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/hand_pose.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_protos_2fhand_5fpose_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_protos_2fhand_5fpose_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3012000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3012004 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "hand_wrench_srv.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_protos_2fhand_5fpose_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_protos_2fhand_5fpose_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[5]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_protos_2fhand_5fpose_2eproto;
namespace protos {
class LejuHandPoseEvent;
class LejuHandPoseEventDefaultTypeInternal;
extern LejuHandPoseEventDefaultTypeInternal _LejuHandPoseEvent_default_instance_;
class LejuHandPoseEvent_Joystick;
class LejuHandPoseEvent_JoystickDefaultTypeInternal;
extern LejuHandPoseEvent_JoystickDefaultTypeInternal _LejuHandPoseEvent_Joystick_default_instance_;
class LejuHandPoseEvent_Pose;
class LejuHandPoseEvent_PoseDefaultTypeInternal;
extern LejuHandPoseEvent_PoseDefaultTypeInternal _LejuHandPoseEvent_Pose_default_instance_;
class LejuHandPoseEvent_Pose_Position;
class LejuHandPoseEvent_Pose_PositionDefaultTypeInternal;
extern LejuHandPoseEvent_Pose_PositionDefaultTypeInternal _LejuHandPoseEvent_Pose_Position_default_instance_;
class LejuHandPoseEvent_Pose_Quaternion;
class LejuHandPoseEvent_Pose_QuaternionDefaultTypeInternal;
extern LejuHandPoseEvent_Pose_QuaternionDefaultTypeInternal _LejuHandPoseEvent_Pose_Quaternion_default_instance_;
}  // namespace protos
PROTOBUF_NAMESPACE_OPEN
template<> ::protos::LejuHandPoseEvent* Arena::CreateMaybeMessage<::protos::LejuHandPoseEvent>(Arena*);
template<> ::protos::LejuHandPoseEvent_Joystick* Arena::CreateMaybeMessage<::protos::LejuHandPoseEvent_Joystick>(Arena*);
template<> ::protos::LejuHandPoseEvent_Pose* Arena::CreateMaybeMessage<::protos::LejuHandPoseEvent_Pose>(Arena*);
template<> ::protos::LejuHandPoseEvent_Pose_Position* Arena::CreateMaybeMessage<::protos::LejuHandPoseEvent_Pose_Position>(Arena*);
template<> ::protos::LejuHandPoseEvent_Pose_Quaternion* Arena::CreateMaybeMessage<::protos::LejuHandPoseEvent_Pose_Quaternion>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace protos {

// ===================================================================

class LejuHandPoseEvent_Pose_Position PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:protos.LejuHandPoseEvent.Pose.Position) */ {
 public:
  inline LejuHandPoseEvent_Pose_Position() : LejuHandPoseEvent_Pose_Position(nullptr) {};
  virtual ~LejuHandPoseEvent_Pose_Position();

  LejuHandPoseEvent_Pose_Position(const LejuHandPoseEvent_Pose_Position& from);
  LejuHandPoseEvent_Pose_Position(LejuHandPoseEvent_Pose_Position&& from) noexcept
    : LejuHandPoseEvent_Pose_Position() {
    *this = ::std::move(from);
  }

  inline LejuHandPoseEvent_Pose_Position& operator=(const LejuHandPoseEvent_Pose_Position& from) {
    CopyFrom(from);
    return *this;
  }
  inline LejuHandPoseEvent_Pose_Position& operator=(LejuHandPoseEvent_Pose_Position&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const LejuHandPoseEvent_Pose_Position& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const LejuHandPoseEvent_Pose_Position* internal_default_instance() {
    return reinterpret_cast<const LejuHandPoseEvent_Pose_Position*>(
               &_LejuHandPoseEvent_Pose_Position_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(LejuHandPoseEvent_Pose_Position& a, LejuHandPoseEvent_Pose_Position& b) {
    a.Swap(&b);
  }
  inline void Swap(LejuHandPoseEvent_Pose_Position* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(LejuHandPoseEvent_Pose_Position* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline LejuHandPoseEvent_Pose_Position* New() const final {
    return CreateMaybeMessage<LejuHandPoseEvent_Pose_Position>(nullptr);
  }

  LejuHandPoseEvent_Pose_Position* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<LejuHandPoseEvent_Pose_Position>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const LejuHandPoseEvent_Pose_Position& from);
  void MergeFrom(const LejuHandPoseEvent_Pose_Position& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(LejuHandPoseEvent_Pose_Position* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "protos.LejuHandPoseEvent.Pose.Position";
  }
  protected:
  explicit LejuHandPoseEvent_Pose_Position(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_protos_2fhand_5fpose_2eproto);
    return ::descriptor_table_protos_2fhand_5fpose_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kXFieldNumber = 1,
    kYFieldNumber = 2,
    kZFieldNumber = 3,
  };
  // float x = 1;
  void clear_x();
  float x() const;
  void set_x(float value);
  private:
  float _internal_x() const;
  void _internal_set_x(float value);
  public:

  // float y = 2;
  void clear_y();
  float y() const;
  void set_y(float value);
  private:
  float _internal_y() const;
  void _internal_set_y(float value);
  public:

  // float z = 3;
  void clear_z();
  float z() const;
  void set_z(float value);
  private:
  float _internal_z() const;
  void _internal_set_z(float value);
  public:

  // @@protoc_insertion_point(class_scope:protos.LejuHandPoseEvent.Pose.Position)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  float x_;
  float y_;
  float z_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_protos_2fhand_5fpose_2eproto;
};
// -------------------------------------------------------------------

class LejuHandPoseEvent_Pose_Quaternion PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:protos.LejuHandPoseEvent.Pose.Quaternion) */ {
 public:
  inline LejuHandPoseEvent_Pose_Quaternion() : LejuHandPoseEvent_Pose_Quaternion(nullptr) {};
  virtual ~LejuHandPoseEvent_Pose_Quaternion();

  LejuHandPoseEvent_Pose_Quaternion(const LejuHandPoseEvent_Pose_Quaternion& from);
  LejuHandPoseEvent_Pose_Quaternion(LejuHandPoseEvent_Pose_Quaternion&& from) noexcept
    : LejuHandPoseEvent_Pose_Quaternion() {
    *this = ::std::move(from);
  }

  inline LejuHandPoseEvent_Pose_Quaternion& operator=(const LejuHandPoseEvent_Pose_Quaternion& from) {
    CopyFrom(from);
    return *this;
  }
  inline LejuHandPoseEvent_Pose_Quaternion& operator=(LejuHandPoseEvent_Pose_Quaternion&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const LejuHandPoseEvent_Pose_Quaternion& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const LejuHandPoseEvent_Pose_Quaternion* internal_default_instance() {
    return reinterpret_cast<const LejuHandPoseEvent_Pose_Quaternion*>(
               &_LejuHandPoseEvent_Pose_Quaternion_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(LejuHandPoseEvent_Pose_Quaternion& a, LejuHandPoseEvent_Pose_Quaternion& b) {
    a.Swap(&b);
  }
  inline void Swap(LejuHandPoseEvent_Pose_Quaternion* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(LejuHandPoseEvent_Pose_Quaternion* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline LejuHandPoseEvent_Pose_Quaternion* New() const final {
    return CreateMaybeMessage<LejuHandPoseEvent_Pose_Quaternion>(nullptr);
  }

  LejuHandPoseEvent_Pose_Quaternion* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<LejuHandPoseEvent_Pose_Quaternion>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const LejuHandPoseEvent_Pose_Quaternion& from);
  void MergeFrom(const LejuHandPoseEvent_Pose_Quaternion& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(LejuHandPoseEvent_Pose_Quaternion* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "protos.LejuHandPoseEvent.Pose.Quaternion";
  }
  protected:
  explicit LejuHandPoseEvent_Pose_Quaternion(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_protos_2fhand_5fpose_2eproto);
    return ::descriptor_table_protos_2fhand_5fpose_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kXFieldNumber = 1,
    kYFieldNumber = 2,
    kZFieldNumber = 3,
    kWFieldNumber = 4,
  };
  // float x = 1;
  void clear_x();
  float x() const;
  void set_x(float value);
  private:
  float _internal_x() const;
  void _internal_set_x(float value);
  public:

  // float y = 2;
  void clear_y();
  float y() const;
  void set_y(float value);
  private:
  float _internal_y() const;
  void _internal_set_y(float value);
  public:

  // float z = 3;
  void clear_z();
  float z() const;
  void set_z(float value);
  private:
  float _internal_z() const;
  void _internal_set_z(float value);
  public:

  // float w = 4;
  void clear_w();
  float w() const;
  void set_w(float value);
  private:
  float _internal_w() const;
  void _internal_set_w(float value);
  public:

  // @@protoc_insertion_point(class_scope:protos.LejuHandPoseEvent.Pose.Quaternion)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  float x_;
  float y_;
  float z_;
  float w_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_protos_2fhand_5fpose_2eproto;
};
// -------------------------------------------------------------------

class LejuHandPoseEvent_Pose PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:protos.LejuHandPoseEvent.Pose) */ {
 public:
  inline LejuHandPoseEvent_Pose() : LejuHandPoseEvent_Pose(nullptr) {};
  virtual ~LejuHandPoseEvent_Pose();

  LejuHandPoseEvent_Pose(const LejuHandPoseEvent_Pose& from);
  LejuHandPoseEvent_Pose(LejuHandPoseEvent_Pose&& from) noexcept
    : LejuHandPoseEvent_Pose() {
    *this = ::std::move(from);
  }

  inline LejuHandPoseEvent_Pose& operator=(const LejuHandPoseEvent_Pose& from) {
    CopyFrom(from);
    return *this;
  }
  inline LejuHandPoseEvent_Pose& operator=(LejuHandPoseEvent_Pose&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const LejuHandPoseEvent_Pose& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const LejuHandPoseEvent_Pose* internal_default_instance() {
    return reinterpret_cast<const LejuHandPoseEvent_Pose*>(
               &_LejuHandPoseEvent_Pose_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(LejuHandPoseEvent_Pose& a, LejuHandPoseEvent_Pose& b) {
    a.Swap(&b);
  }
  inline void Swap(LejuHandPoseEvent_Pose* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(LejuHandPoseEvent_Pose* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline LejuHandPoseEvent_Pose* New() const final {
    return CreateMaybeMessage<LejuHandPoseEvent_Pose>(nullptr);
  }

  LejuHandPoseEvent_Pose* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<LejuHandPoseEvent_Pose>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const LejuHandPoseEvent_Pose& from);
  void MergeFrom(const LejuHandPoseEvent_Pose& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(LejuHandPoseEvent_Pose* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "protos.LejuHandPoseEvent.Pose";
  }
  protected:
  explicit LejuHandPoseEvent_Pose(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_protos_2fhand_5fpose_2eproto);
    return ::descriptor_table_protos_2fhand_5fpose_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  typedef LejuHandPoseEvent_Pose_Position Position;
  typedef LejuHandPoseEvent_Pose_Quaternion Quaternion;

  // accessors -------------------------------------------------------

  enum : int {
    kPositionFieldNumber = 1,
    kQuaternionFieldNumber = 2,
  };
  // .protos.LejuHandPoseEvent.Pose.Position position = 1;
  bool has_position() const;
  private:
  bool _internal_has_position() const;
  public:
  void clear_position();
  const ::protos::LejuHandPoseEvent_Pose_Position& position() const;
  ::protos::LejuHandPoseEvent_Pose_Position* release_position();
  ::protos::LejuHandPoseEvent_Pose_Position* mutable_position();
  void set_allocated_position(::protos::LejuHandPoseEvent_Pose_Position* position);
  private:
  const ::protos::LejuHandPoseEvent_Pose_Position& _internal_position() const;
  ::protos::LejuHandPoseEvent_Pose_Position* _internal_mutable_position();
  public:
  void unsafe_arena_set_allocated_position(
      ::protos::LejuHandPoseEvent_Pose_Position* position);
  ::protos::LejuHandPoseEvent_Pose_Position* unsafe_arena_release_position();

  // .protos.LejuHandPoseEvent.Pose.Quaternion quaternion = 2;
  bool has_quaternion() const;
  private:
  bool _internal_has_quaternion() const;
  public:
  void clear_quaternion();
  const ::protos::LejuHandPoseEvent_Pose_Quaternion& quaternion() const;
  ::protos::LejuHandPoseEvent_Pose_Quaternion* release_quaternion();
  ::protos::LejuHandPoseEvent_Pose_Quaternion* mutable_quaternion();
  void set_allocated_quaternion(::protos::LejuHandPoseEvent_Pose_Quaternion* quaternion);
  private:
  const ::protos::LejuHandPoseEvent_Pose_Quaternion& _internal_quaternion() const;
  ::protos::LejuHandPoseEvent_Pose_Quaternion* _internal_mutable_quaternion();
  public:
  void unsafe_arena_set_allocated_quaternion(
      ::protos::LejuHandPoseEvent_Pose_Quaternion* quaternion);
  ::protos::LejuHandPoseEvent_Pose_Quaternion* unsafe_arena_release_quaternion();

  // @@protoc_insertion_point(class_scope:protos.LejuHandPoseEvent.Pose)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::protos::LejuHandPoseEvent_Pose_Position* position_;
  ::protos::LejuHandPoseEvent_Pose_Quaternion* quaternion_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_protos_2fhand_5fpose_2eproto;
};
// -------------------------------------------------------------------

class LejuHandPoseEvent_Joystick PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:protos.LejuHandPoseEvent.Joystick) */ {
 public:
  inline LejuHandPoseEvent_Joystick() : LejuHandPoseEvent_Joystick(nullptr) {};
  virtual ~LejuHandPoseEvent_Joystick();

  LejuHandPoseEvent_Joystick(const LejuHandPoseEvent_Joystick& from);
  LejuHandPoseEvent_Joystick(LejuHandPoseEvent_Joystick&& from) noexcept
    : LejuHandPoseEvent_Joystick() {
    *this = ::std::move(from);
  }

  inline LejuHandPoseEvent_Joystick& operator=(const LejuHandPoseEvent_Joystick& from) {
    CopyFrom(from);
    return *this;
  }
  inline LejuHandPoseEvent_Joystick& operator=(LejuHandPoseEvent_Joystick&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const LejuHandPoseEvent_Joystick& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const LejuHandPoseEvent_Joystick* internal_default_instance() {
    return reinterpret_cast<const LejuHandPoseEvent_Joystick*>(
               &_LejuHandPoseEvent_Joystick_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(LejuHandPoseEvent_Joystick& a, LejuHandPoseEvent_Joystick& b) {
    a.Swap(&b);
  }
  inline void Swap(LejuHandPoseEvent_Joystick* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(LejuHandPoseEvent_Joystick* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline LejuHandPoseEvent_Joystick* New() const final {
    return CreateMaybeMessage<LejuHandPoseEvent_Joystick>(nullptr);
  }

  LejuHandPoseEvent_Joystick* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<LejuHandPoseEvent_Joystick>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const LejuHandPoseEvent_Joystick& from);
  void MergeFrom(const LejuHandPoseEvent_Joystick& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(LejuHandPoseEvent_Joystick* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "protos.LejuHandPoseEvent.Joystick";
  }
  protected:
  explicit LejuHandPoseEvent_Joystick(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_protos_2fhand_5fpose_2eproto);
    return ::descriptor_table_protos_2fhand_5fpose_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kXFieldNumber = 1,
    kYFieldNumber = 2,
    kTriggerFieldNumber = 3,
    kGripFieldNumber = 4,
    kFirstButtonPressedFieldNumber = 5,
    kSecondButtonPressedFieldNumber = 6,
    kFirstButtonTouchedFieldNumber = 7,
    kSecondButtonTouchedFieldNumber = 8,
  };
  // float x = 1;
  void clear_x();
  float x() const;
  void set_x(float value);
  private:
  float _internal_x() const;
  void _internal_set_x(float value);
  public:

  // float y = 2;
  void clear_y();
  float y() const;
  void set_y(float value);
  private:
  float _internal_y() const;
  void _internal_set_y(float value);
  public:

  // float trigger = 3;
  void clear_trigger();
  float trigger() const;
  void set_trigger(float value);
  private:
  float _internal_trigger() const;
  void _internal_set_trigger(float value);
  public:

  // float grip = 4;
  void clear_grip();
  float grip() const;
  void set_grip(float value);
  private:
  float _internal_grip() const;
  void _internal_set_grip(float value);
  public:

  // bool firstButtonPressed = 5;
  void clear_firstbuttonpressed();
  bool firstbuttonpressed() const;
  void set_firstbuttonpressed(bool value);
  private:
  bool _internal_firstbuttonpressed() const;
  void _internal_set_firstbuttonpressed(bool value);
  public:

  // bool secondButtonPressed = 6;
  void clear_secondbuttonpressed();
  bool secondbuttonpressed() const;
  void set_secondbuttonpressed(bool value);
  private:
  bool _internal_secondbuttonpressed() const;
  void _internal_set_secondbuttonpressed(bool value);
  public:

  // bool firstButtonTouched = 7;
  void clear_firstbuttontouched();
  bool firstbuttontouched() const;
  void set_firstbuttontouched(bool value);
  private:
  bool _internal_firstbuttontouched() const;
  void _internal_set_firstbuttontouched(bool value);
  public:

  // bool secondButtonTouched = 8;
  void clear_secondbuttontouched();
  bool secondbuttontouched() const;
  void set_secondbuttontouched(bool value);
  private:
  bool _internal_secondbuttontouched() const;
  void _internal_set_secondbuttontouched(bool value);
  public:

  // @@protoc_insertion_point(class_scope:protos.LejuHandPoseEvent.Joystick)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  float x_;
  float y_;
  float trigger_;
  float grip_;
  bool firstbuttonpressed_;
  bool secondbuttonpressed_;
  bool firstbuttontouched_;
  bool secondbuttontouched_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_protos_2fhand_5fpose_2eproto;
};
// -------------------------------------------------------------------

class LejuHandPoseEvent PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:protos.LejuHandPoseEvent) */ {
 public:
  inline LejuHandPoseEvent() : LejuHandPoseEvent(nullptr) {};
  virtual ~LejuHandPoseEvent();

  LejuHandPoseEvent(const LejuHandPoseEvent& from);
  LejuHandPoseEvent(LejuHandPoseEvent&& from) noexcept
    : LejuHandPoseEvent() {
    *this = ::std::move(from);
  }

  inline LejuHandPoseEvent& operator=(const LejuHandPoseEvent& from) {
    CopyFrom(from);
    return *this;
  }
  inline LejuHandPoseEvent& operator=(LejuHandPoseEvent&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const LejuHandPoseEvent& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const LejuHandPoseEvent* internal_default_instance() {
    return reinterpret_cast<const LejuHandPoseEvent*>(
               &_LejuHandPoseEvent_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(LejuHandPoseEvent& a, LejuHandPoseEvent& b) {
    a.Swap(&b);
  }
  inline void Swap(LejuHandPoseEvent* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(LejuHandPoseEvent* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline LejuHandPoseEvent* New() const final {
    return CreateMaybeMessage<LejuHandPoseEvent>(nullptr);
  }

  LejuHandPoseEvent* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<LejuHandPoseEvent>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const LejuHandPoseEvent& from);
  void MergeFrom(const LejuHandPoseEvent& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(LejuHandPoseEvent* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "protos.LejuHandPoseEvent";
  }
  protected:
  explicit LejuHandPoseEvent(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_protos_2fhand_5fpose_2eproto);
    return ::descriptor_table_protos_2fhand_5fpose_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  typedef LejuHandPoseEvent_Pose Pose;
  typedef LejuHandPoseEvent_Joystick Joystick;

  // accessors -------------------------------------------------------

  enum : int {
    kPosesFieldNumber = 2,
    kLeftJoystickFieldNumber = 5,
    kRightJoystickFieldNumber = 6,
    kItemMassForceRequestFieldNumber = 7,
    kTimestampFieldNumber = 1,
    kIsDataHighConfidenceFieldNumber = 3,
    kIsHandTrackingFieldNumber = 4,
  };
  // repeated .protos.LejuHandPoseEvent.Pose poses = 2;
  int poses_size() const;
  private:
  int _internal_poses_size() const;
  public:
  void clear_poses();
  ::protos::LejuHandPoseEvent_Pose* mutable_poses(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::protos::LejuHandPoseEvent_Pose >*
      mutable_poses();
  private:
  const ::protos::LejuHandPoseEvent_Pose& _internal_poses(int index) const;
  ::protos::LejuHandPoseEvent_Pose* _internal_add_poses();
  public:
  const ::protos::LejuHandPoseEvent_Pose& poses(int index) const;
  ::protos::LejuHandPoseEvent_Pose* add_poses();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::protos::LejuHandPoseEvent_Pose >&
      poses() const;

  // .protos.LejuHandPoseEvent.Joystick left_joystick = 5;
  bool has_left_joystick() const;
  private:
  bool _internal_has_left_joystick() const;
  public:
  void clear_left_joystick();
  const ::protos::LejuHandPoseEvent_Joystick& left_joystick() const;
  ::protos::LejuHandPoseEvent_Joystick* release_left_joystick();
  ::protos::LejuHandPoseEvent_Joystick* mutable_left_joystick();
  void set_allocated_left_joystick(::protos::LejuHandPoseEvent_Joystick* left_joystick);
  private:
  const ::protos::LejuHandPoseEvent_Joystick& _internal_left_joystick() const;
  ::protos::LejuHandPoseEvent_Joystick* _internal_mutable_left_joystick();
  public:
  void unsafe_arena_set_allocated_left_joystick(
      ::protos::LejuHandPoseEvent_Joystick* left_joystick);
  ::protos::LejuHandPoseEvent_Joystick* unsafe_arena_release_left_joystick();

  // .protos.LejuHandPoseEvent.Joystick right_joystick = 6;
  bool has_right_joystick() const;
  private:
  bool _internal_has_right_joystick() const;
  public:
  void clear_right_joystick();
  const ::protos::LejuHandPoseEvent_Joystick& right_joystick() const;
  ::protos::LejuHandPoseEvent_Joystick* release_right_joystick();
  ::protos::LejuHandPoseEvent_Joystick* mutable_right_joystick();
  void set_allocated_right_joystick(::protos::LejuHandPoseEvent_Joystick* right_joystick);
  private:
  const ::protos::LejuHandPoseEvent_Joystick& _internal_right_joystick() const;
  ::protos::LejuHandPoseEvent_Joystick* _internal_mutable_right_joystick();
  public:
  void unsafe_arena_set_allocated_right_joystick(
      ::protos::LejuHandPoseEvent_Joystick* right_joystick);
  ::protos::LejuHandPoseEvent_Joystick* unsafe_arena_release_right_joystick();

  // .protos.ItemMassForceRequest item_mass_force_request = 7;
  bool has_item_mass_force_request() const;
  private:
  bool _internal_has_item_mass_force_request() const;
  public:
  void clear_item_mass_force_request();
  const ::protos::ItemMassForceRequest& item_mass_force_request() const;
  ::protos::ItemMassForceRequest* release_item_mass_force_request();
  ::protos::ItemMassForceRequest* mutable_item_mass_force_request();
  void set_allocated_item_mass_force_request(::protos::ItemMassForceRequest* item_mass_force_request);
  private:
  const ::protos::ItemMassForceRequest& _internal_item_mass_force_request() const;
  ::protos::ItemMassForceRequest* _internal_mutable_item_mass_force_request();
  public:
  void unsafe_arena_set_allocated_item_mass_force_request(
      ::protos::ItemMassForceRequest* item_mass_force_request);
  ::protos::ItemMassForceRequest* unsafe_arena_release_item_mass_force_request();

  // int64 timestamp = 1;
  void clear_timestamp();
  ::PROTOBUF_NAMESPACE_ID::int64 timestamp() const;
  void set_timestamp(::PROTOBUF_NAMESPACE_ID::int64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int64 _internal_timestamp() const;
  void _internal_set_timestamp(::PROTOBUF_NAMESPACE_ID::int64 value);
  public:

  // bool IsDataHighConfidence = 3;
  void clear_isdatahighconfidence();
  bool isdatahighconfidence() const;
  void set_isdatahighconfidence(bool value);
  private:
  bool _internal_isdatahighconfidence() const;
  void _internal_set_isdatahighconfidence(bool value);
  public:

  // bool IsHandTracking = 4;
  void clear_ishandtracking();
  bool ishandtracking() const;
  void set_ishandtracking(bool value);
  private:
  bool _internal_ishandtracking() const;
  void _internal_set_ishandtracking(bool value);
  public:

  // @@protoc_insertion_point(class_scope:protos.LejuHandPoseEvent)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::protos::LejuHandPoseEvent_Pose > poses_;
  ::protos::LejuHandPoseEvent_Joystick* left_joystick_;
  ::protos::LejuHandPoseEvent_Joystick* right_joystick_;
  ::protos::ItemMassForceRequest* item_mass_force_request_;
  ::PROTOBUF_NAMESPACE_ID::int64 timestamp_;
  bool isdatahighconfidence_;
  bool ishandtracking_;
  friend struct ::TableStruct_protos_2fhand_5fpose_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// LejuHandPoseEvent_Pose_Position

// float x = 1;
inline void LejuHandPoseEvent_Pose_Position::clear_x() {
  x_ = 0;
}
inline float LejuHandPoseEvent_Pose_Position::_internal_x() const {
  return x_;
}
inline float LejuHandPoseEvent_Pose_Position::x() const {
  // @@protoc_insertion_point(field_get:protos.LejuHandPoseEvent.Pose.Position.x)
  return _internal_x();
}
inline void LejuHandPoseEvent_Pose_Position::_internal_set_x(float value) {
  
  x_ = value;
}
inline void LejuHandPoseEvent_Pose_Position::set_x(float value) {
  _internal_set_x(value);
  // @@protoc_insertion_point(field_set:protos.LejuHandPoseEvent.Pose.Position.x)
}

// float y = 2;
inline void LejuHandPoseEvent_Pose_Position::clear_y() {
  y_ = 0;
}
inline float LejuHandPoseEvent_Pose_Position::_internal_y() const {
  return y_;
}
inline float LejuHandPoseEvent_Pose_Position::y() const {
  // @@protoc_insertion_point(field_get:protos.LejuHandPoseEvent.Pose.Position.y)
  return _internal_y();
}
inline void LejuHandPoseEvent_Pose_Position::_internal_set_y(float value) {
  
  y_ = value;
}
inline void LejuHandPoseEvent_Pose_Position::set_y(float value) {
  _internal_set_y(value);
  // @@protoc_insertion_point(field_set:protos.LejuHandPoseEvent.Pose.Position.y)
}

// float z = 3;
inline void LejuHandPoseEvent_Pose_Position::clear_z() {
  z_ = 0;
}
inline float LejuHandPoseEvent_Pose_Position::_internal_z() const {
  return z_;
}
inline float LejuHandPoseEvent_Pose_Position::z() const {
  // @@protoc_insertion_point(field_get:protos.LejuHandPoseEvent.Pose.Position.z)
  return _internal_z();
}
inline void LejuHandPoseEvent_Pose_Position::_internal_set_z(float value) {
  
  z_ = value;
}
inline void LejuHandPoseEvent_Pose_Position::set_z(float value) {
  _internal_set_z(value);
  // @@protoc_insertion_point(field_set:protos.LejuHandPoseEvent.Pose.Position.z)
}

// -------------------------------------------------------------------

// LejuHandPoseEvent_Pose_Quaternion

// float x = 1;
inline void LejuHandPoseEvent_Pose_Quaternion::clear_x() {
  x_ = 0;
}
inline float LejuHandPoseEvent_Pose_Quaternion::_internal_x() const {
  return x_;
}
inline float LejuHandPoseEvent_Pose_Quaternion::x() const {
  // @@protoc_insertion_point(field_get:protos.LejuHandPoseEvent.Pose.Quaternion.x)
  return _internal_x();
}
inline void LejuHandPoseEvent_Pose_Quaternion::_internal_set_x(float value) {
  
  x_ = value;
}
inline void LejuHandPoseEvent_Pose_Quaternion::set_x(float value) {
  _internal_set_x(value);
  // @@protoc_insertion_point(field_set:protos.LejuHandPoseEvent.Pose.Quaternion.x)
}

// float y = 2;
inline void LejuHandPoseEvent_Pose_Quaternion::clear_y() {
  y_ = 0;
}
inline float LejuHandPoseEvent_Pose_Quaternion::_internal_y() const {
  return y_;
}
inline float LejuHandPoseEvent_Pose_Quaternion::y() const {
  // @@protoc_insertion_point(field_get:protos.LejuHandPoseEvent.Pose.Quaternion.y)
  return _internal_y();
}
inline void LejuHandPoseEvent_Pose_Quaternion::_internal_set_y(float value) {
  
  y_ = value;
}
inline void LejuHandPoseEvent_Pose_Quaternion::set_y(float value) {
  _internal_set_y(value);
  // @@protoc_insertion_point(field_set:protos.LejuHandPoseEvent.Pose.Quaternion.y)
}

// float z = 3;
inline void LejuHandPoseEvent_Pose_Quaternion::clear_z() {
  z_ = 0;
}
inline float LejuHandPoseEvent_Pose_Quaternion::_internal_z() const {
  return z_;
}
inline float LejuHandPoseEvent_Pose_Quaternion::z() const {
  // @@protoc_insertion_point(field_get:protos.LejuHandPoseEvent.Pose.Quaternion.z)
  return _internal_z();
}
inline void LejuHandPoseEvent_Pose_Quaternion::_internal_set_z(float value) {
  
  z_ = value;
}
inline void LejuHandPoseEvent_Pose_Quaternion::set_z(float value) {
  _internal_set_z(value);
  // @@protoc_insertion_point(field_set:protos.LejuHandPoseEvent.Pose.Quaternion.z)
}

// float w = 4;
inline void LejuHandPoseEvent_Pose_Quaternion::clear_w() {
  w_ = 0;
}
inline float LejuHandPoseEvent_Pose_Quaternion::_internal_w() const {
  return w_;
}
inline float LejuHandPoseEvent_Pose_Quaternion::w() const {
  // @@protoc_insertion_point(field_get:protos.LejuHandPoseEvent.Pose.Quaternion.w)
  return _internal_w();
}
inline void LejuHandPoseEvent_Pose_Quaternion::_internal_set_w(float value) {
  
  w_ = value;
}
inline void LejuHandPoseEvent_Pose_Quaternion::set_w(float value) {
  _internal_set_w(value);
  // @@protoc_insertion_point(field_set:protos.LejuHandPoseEvent.Pose.Quaternion.w)
}

// -------------------------------------------------------------------

// LejuHandPoseEvent_Pose

// .protos.LejuHandPoseEvent.Pose.Position position = 1;
inline bool LejuHandPoseEvent_Pose::_internal_has_position() const {
  return this != internal_default_instance() && position_ != nullptr;
}
inline bool LejuHandPoseEvent_Pose::has_position() const {
  return _internal_has_position();
}
inline void LejuHandPoseEvent_Pose::clear_position() {
  if (GetArena() == nullptr && position_ != nullptr) {
    delete position_;
  }
  position_ = nullptr;
}
inline const ::protos::LejuHandPoseEvent_Pose_Position& LejuHandPoseEvent_Pose::_internal_position() const {
  const ::protos::LejuHandPoseEvent_Pose_Position* p = position_;
  return p != nullptr ? *p : *reinterpret_cast<const ::protos::LejuHandPoseEvent_Pose_Position*>(
      &::protos::_LejuHandPoseEvent_Pose_Position_default_instance_);
}
inline const ::protos::LejuHandPoseEvent_Pose_Position& LejuHandPoseEvent_Pose::position() const {
  // @@protoc_insertion_point(field_get:protos.LejuHandPoseEvent.Pose.position)
  return _internal_position();
}
inline void LejuHandPoseEvent_Pose::unsafe_arena_set_allocated_position(
    ::protos::LejuHandPoseEvent_Pose_Position* position) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(position_);
  }
  position_ = position;
  if (position) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:protos.LejuHandPoseEvent.Pose.position)
}
inline ::protos::LejuHandPoseEvent_Pose_Position* LejuHandPoseEvent_Pose::release_position() {
  auto temp = unsafe_arena_release_position();
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::protos::LejuHandPoseEvent_Pose_Position* LejuHandPoseEvent_Pose::unsafe_arena_release_position() {
  // @@protoc_insertion_point(field_release:protos.LejuHandPoseEvent.Pose.position)
  
  ::protos::LejuHandPoseEvent_Pose_Position* temp = position_;
  position_ = nullptr;
  return temp;
}
inline ::protos::LejuHandPoseEvent_Pose_Position* LejuHandPoseEvent_Pose::_internal_mutable_position() {
  
  if (position_ == nullptr) {
    auto* p = CreateMaybeMessage<::protos::LejuHandPoseEvent_Pose_Position>(GetArena());
    position_ = p;
  }
  return position_;
}
inline ::protos::LejuHandPoseEvent_Pose_Position* LejuHandPoseEvent_Pose::mutable_position() {
  // @@protoc_insertion_point(field_mutable:protos.LejuHandPoseEvent.Pose.position)
  return _internal_mutable_position();
}
inline void LejuHandPoseEvent_Pose::set_allocated_position(::protos::LejuHandPoseEvent_Pose_Position* position) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete position_;
  }
  if (position) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::GetArena(position);
    if (message_arena != submessage_arena) {
      position = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, position, submessage_arena);
    }
    
  } else {
    
  }
  position_ = position;
  // @@protoc_insertion_point(field_set_allocated:protos.LejuHandPoseEvent.Pose.position)
}

// .protos.LejuHandPoseEvent.Pose.Quaternion quaternion = 2;
inline bool LejuHandPoseEvent_Pose::_internal_has_quaternion() const {
  return this != internal_default_instance() && quaternion_ != nullptr;
}
inline bool LejuHandPoseEvent_Pose::has_quaternion() const {
  return _internal_has_quaternion();
}
inline void LejuHandPoseEvent_Pose::clear_quaternion() {
  if (GetArena() == nullptr && quaternion_ != nullptr) {
    delete quaternion_;
  }
  quaternion_ = nullptr;
}
inline const ::protos::LejuHandPoseEvent_Pose_Quaternion& LejuHandPoseEvent_Pose::_internal_quaternion() const {
  const ::protos::LejuHandPoseEvent_Pose_Quaternion* p = quaternion_;
  return p != nullptr ? *p : *reinterpret_cast<const ::protos::LejuHandPoseEvent_Pose_Quaternion*>(
      &::protos::_LejuHandPoseEvent_Pose_Quaternion_default_instance_);
}
inline const ::protos::LejuHandPoseEvent_Pose_Quaternion& LejuHandPoseEvent_Pose::quaternion() const {
  // @@protoc_insertion_point(field_get:protos.LejuHandPoseEvent.Pose.quaternion)
  return _internal_quaternion();
}
inline void LejuHandPoseEvent_Pose::unsafe_arena_set_allocated_quaternion(
    ::protos::LejuHandPoseEvent_Pose_Quaternion* quaternion) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(quaternion_);
  }
  quaternion_ = quaternion;
  if (quaternion) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:protos.LejuHandPoseEvent.Pose.quaternion)
}
inline ::protos::LejuHandPoseEvent_Pose_Quaternion* LejuHandPoseEvent_Pose::release_quaternion() {
  auto temp = unsafe_arena_release_quaternion();
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::protos::LejuHandPoseEvent_Pose_Quaternion* LejuHandPoseEvent_Pose::unsafe_arena_release_quaternion() {
  // @@protoc_insertion_point(field_release:protos.LejuHandPoseEvent.Pose.quaternion)
  
  ::protos::LejuHandPoseEvent_Pose_Quaternion* temp = quaternion_;
  quaternion_ = nullptr;
  return temp;
}
inline ::protos::LejuHandPoseEvent_Pose_Quaternion* LejuHandPoseEvent_Pose::_internal_mutable_quaternion() {
  
  if (quaternion_ == nullptr) {
    auto* p = CreateMaybeMessage<::protos::LejuHandPoseEvent_Pose_Quaternion>(GetArena());
    quaternion_ = p;
  }
  return quaternion_;
}
inline ::protos::LejuHandPoseEvent_Pose_Quaternion* LejuHandPoseEvent_Pose::mutable_quaternion() {
  // @@protoc_insertion_point(field_mutable:protos.LejuHandPoseEvent.Pose.quaternion)
  return _internal_mutable_quaternion();
}
inline void LejuHandPoseEvent_Pose::set_allocated_quaternion(::protos::LejuHandPoseEvent_Pose_Quaternion* quaternion) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete quaternion_;
  }
  if (quaternion) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::GetArena(quaternion);
    if (message_arena != submessage_arena) {
      quaternion = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, quaternion, submessage_arena);
    }
    
  } else {
    
  }
  quaternion_ = quaternion;
  // @@protoc_insertion_point(field_set_allocated:protos.LejuHandPoseEvent.Pose.quaternion)
}

// -------------------------------------------------------------------

// LejuHandPoseEvent_Joystick

// float x = 1;
inline void LejuHandPoseEvent_Joystick::clear_x() {
  x_ = 0;
}
inline float LejuHandPoseEvent_Joystick::_internal_x() const {
  return x_;
}
inline float LejuHandPoseEvent_Joystick::x() const {
  // @@protoc_insertion_point(field_get:protos.LejuHandPoseEvent.Joystick.x)
  return _internal_x();
}
inline void LejuHandPoseEvent_Joystick::_internal_set_x(float value) {
  
  x_ = value;
}
inline void LejuHandPoseEvent_Joystick::set_x(float value) {
  _internal_set_x(value);
  // @@protoc_insertion_point(field_set:protos.LejuHandPoseEvent.Joystick.x)
}

// float y = 2;
inline void LejuHandPoseEvent_Joystick::clear_y() {
  y_ = 0;
}
inline float LejuHandPoseEvent_Joystick::_internal_y() const {
  return y_;
}
inline float LejuHandPoseEvent_Joystick::y() const {
  // @@protoc_insertion_point(field_get:protos.LejuHandPoseEvent.Joystick.y)
  return _internal_y();
}
inline void LejuHandPoseEvent_Joystick::_internal_set_y(float value) {
  
  y_ = value;
}
inline void LejuHandPoseEvent_Joystick::set_y(float value) {
  _internal_set_y(value);
  // @@protoc_insertion_point(field_set:protos.LejuHandPoseEvent.Joystick.y)
}

// float trigger = 3;
inline void LejuHandPoseEvent_Joystick::clear_trigger() {
  trigger_ = 0;
}
inline float LejuHandPoseEvent_Joystick::_internal_trigger() const {
  return trigger_;
}
inline float LejuHandPoseEvent_Joystick::trigger() const {
  // @@protoc_insertion_point(field_get:protos.LejuHandPoseEvent.Joystick.trigger)
  return _internal_trigger();
}
inline void LejuHandPoseEvent_Joystick::_internal_set_trigger(float value) {
  
  trigger_ = value;
}
inline void LejuHandPoseEvent_Joystick::set_trigger(float value) {
  _internal_set_trigger(value);
  // @@protoc_insertion_point(field_set:protos.LejuHandPoseEvent.Joystick.trigger)
}

// float grip = 4;
inline void LejuHandPoseEvent_Joystick::clear_grip() {
  grip_ = 0;
}
inline float LejuHandPoseEvent_Joystick::_internal_grip() const {
  return grip_;
}
inline float LejuHandPoseEvent_Joystick::grip() const {
  // @@protoc_insertion_point(field_get:protos.LejuHandPoseEvent.Joystick.grip)
  return _internal_grip();
}
inline void LejuHandPoseEvent_Joystick::_internal_set_grip(float value) {
  
  grip_ = value;
}
inline void LejuHandPoseEvent_Joystick::set_grip(float value) {
  _internal_set_grip(value);
  // @@protoc_insertion_point(field_set:protos.LejuHandPoseEvent.Joystick.grip)
}

// bool firstButtonPressed = 5;
inline void LejuHandPoseEvent_Joystick::clear_firstbuttonpressed() {
  firstbuttonpressed_ = false;
}
inline bool LejuHandPoseEvent_Joystick::_internal_firstbuttonpressed() const {
  return firstbuttonpressed_;
}
inline bool LejuHandPoseEvent_Joystick::firstbuttonpressed() const {
  // @@protoc_insertion_point(field_get:protos.LejuHandPoseEvent.Joystick.firstButtonPressed)
  return _internal_firstbuttonpressed();
}
inline void LejuHandPoseEvent_Joystick::_internal_set_firstbuttonpressed(bool value) {
  
  firstbuttonpressed_ = value;
}
inline void LejuHandPoseEvent_Joystick::set_firstbuttonpressed(bool value) {
  _internal_set_firstbuttonpressed(value);
  // @@protoc_insertion_point(field_set:protos.LejuHandPoseEvent.Joystick.firstButtonPressed)
}

// bool secondButtonPressed = 6;
inline void LejuHandPoseEvent_Joystick::clear_secondbuttonpressed() {
  secondbuttonpressed_ = false;
}
inline bool LejuHandPoseEvent_Joystick::_internal_secondbuttonpressed() const {
  return secondbuttonpressed_;
}
inline bool LejuHandPoseEvent_Joystick::secondbuttonpressed() const {
  // @@protoc_insertion_point(field_get:protos.LejuHandPoseEvent.Joystick.secondButtonPressed)
  return _internal_secondbuttonpressed();
}
inline void LejuHandPoseEvent_Joystick::_internal_set_secondbuttonpressed(bool value) {
  
  secondbuttonpressed_ = value;
}
inline void LejuHandPoseEvent_Joystick::set_secondbuttonpressed(bool value) {
  _internal_set_secondbuttonpressed(value);
  // @@protoc_insertion_point(field_set:protos.LejuHandPoseEvent.Joystick.secondButtonPressed)
}

// bool firstButtonTouched = 7;
inline void LejuHandPoseEvent_Joystick::clear_firstbuttontouched() {
  firstbuttontouched_ = false;
}
inline bool LejuHandPoseEvent_Joystick::_internal_firstbuttontouched() const {
  return firstbuttontouched_;
}
inline bool LejuHandPoseEvent_Joystick::firstbuttontouched() const {
  // @@protoc_insertion_point(field_get:protos.LejuHandPoseEvent.Joystick.firstButtonTouched)
  return _internal_firstbuttontouched();
}
inline void LejuHandPoseEvent_Joystick::_internal_set_firstbuttontouched(bool value) {
  
  firstbuttontouched_ = value;
}
inline void LejuHandPoseEvent_Joystick::set_firstbuttontouched(bool value) {
  _internal_set_firstbuttontouched(value);
  // @@protoc_insertion_point(field_set:protos.LejuHandPoseEvent.Joystick.firstButtonTouched)
}

// bool secondButtonTouched = 8;
inline void LejuHandPoseEvent_Joystick::clear_secondbuttontouched() {
  secondbuttontouched_ = false;
}
inline bool LejuHandPoseEvent_Joystick::_internal_secondbuttontouched() const {
  return secondbuttontouched_;
}
inline bool LejuHandPoseEvent_Joystick::secondbuttontouched() const {
  // @@protoc_insertion_point(field_get:protos.LejuHandPoseEvent.Joystick.secondButtonTouched)
  return _internal_secondbuttontouched();
}
inline void LejuHandPoseEvent_Joystick::_internal_set_secondbuttontouched(bool value) {
  
  secondbuttontouched_ = value;
}
inline void LejuHandPoseEvent_Joystick::set_secondbuttontouched(bool value) {
  _internal_set_secondbuttontouched(value);
  // @@protoc_insertion_point(field_set:protos.LejuHandPoseEvent.Joystick.secondButtonTouched)
}

// -------------------------------------------------------------------

// LejuHandPoseEvent

// int64 timestamp = 1;
inline void LejuHandPoseEvent::clear_timestamp() {
  timestamp_ = PROTOBUF_LONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::int64 LejuHandPoseEvent::_internal_timestamp() const {
  return timestamp_;
}
inline ::PROTOBUF_NAMESPACE_ID::int64 LejuHandPoseEvent::timestamp() const {
  // @@protoc_insertion_point(field_get:protos.LejuHandPoseEvent.timestamp)
  return _internal_timestamp();
}
inline void LejuHandPoseEvent::_internal_set_timestamp(::PROTOBUF_NAMESPACE_ID::int64 value) {
  
  timestamp_ = value;
}
inline void LejuHandPoseEvent::set_timestamp(::PROTOBUF_NAMESPACE_ID::int64 value) {
  _internal_set_timestamp(value);
  // @@protoc_insertion_point(field_set:protos.LejuHandPoseEvent.timestamp)
}

// repeated .protos.LejuHandPoseEvent.Pose poses = 2;
inline int LejuHandPoseEvent::_internal_poses_size() const {
  return poses_.size();
}
inline int LejuHandPoseEvent::poses_size() const {
  return _internal_poses_size();
}
inline void LejuHandPoseEvent::clear_poses() {
  poses_.Clear();
}
inline ::protos::LejuHandPoseEvent_Pose* LejuHandPoseEvent::mutable_poses(int index) {
  // @@protoc_insertion_point(field_mutable:protos.LejuHandPoseEvent.poses)
  return poses_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::protos::LejuHandPoseEvent_Pose >*
LejuHandPoseEvent::mutable_poses() {
  // @@protoc_insertion_point(field_mutable_list:protos.LejuHandPoseEvent.poses)
  return &poses_;
}
inline const ::protos::LejuHandPoseEvent_Pose& LejuHandPoseEvent::_internal_poses(int index) const {
  return poses_.Get(index);
}
inline const ::protos::LejuHandPoseEvent_Pose& LejuHandPoseEvent::poses(int index) const {
  // @@protoc_insertion_point(field_get:protos.LejuHandPoseEvent.poses)
  return _internal_poses(index);
}
inline ::protos::LejuHandPoseEvent_Pose* LejuHandPoseEvent::_internal_add_poses() {
  return poses_.Add();
}
inline ::protos::LejuHandPoseEvent_Pose* LejuHandPoseEvent::add_poses() {
  // @@protoc_insertion_point(field_add:protos.LejuHandPoseEvent.poses)
  return _internal_add_poses();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::protos::LejuHandPoseEvent_Pose >&
LejuHandPoseEvent::poses() const {
  // @@protoc_insertion_point(field_list:protos.LejuHandPoseEvent.poses)
  return poses_;
}

// bool IsDataHighConfidence = 3;
inline void LejuHandPoseEvent::clear_isdatahighconfidence() {
  isdatahighconfidence_ = false;
}
inline bool LejuHandPoseEvent::_internal_isdatahighconfidence() const {
  return isdatahighconfidence_;
}
inline bool LejuHandPoseEvent::isdatahighconfidence() const {
  // @@protoc_insertion_point(field_get:protos.LejuHandPoseEvent.IsDataHighConfidence)
  return _internal_isdatahighconfidence();
}
inline void LejuHandPoseEvent::_internal_set_isdatahighconfidence(bool value) {
  
  isdatahighconfidence_ = value;
}
inline void LejuHandPoseEvent::set_isdatahighconfidence(bool value) {
  _internal_set_isdatahighconfidence(value);
  // @@protoc_insertion_point(field_set:protos.LejuHandPoseEvent.IsDataHighConfidence)
}

// bool IsHandTracking = 4;
inline void LejuHandPoseEvent::clear_ishandtracking() {
  ishandtracking_ = false;
}
inline bool LejuHandPoseEvent::_internal_ishandtracking() const {
  return ishandtracking_;
}
inline bool LejuHandPoseEvent::ishandtracking() const {
  // @@protoc_insertion_point(field_get:protos.LejuHandPoseEvent.IsHandTracking)
  return _internal_ishandtracking();
}
inline void LejuHandPoseEvent::_internal_set_ishandtracking(bool value) {
  
  ishandtracking_ = value;
}
inline void LejuHandPoseEvent::set_ishandtracking(bool value) {
  _internal_set_ishandtracking(value);
  // @@protoc_insertion_point(field_set:protos.LejuHandPoseEvent.IsHandTracking)
}

// .protos.LejuHandPoseEvent.Joystick left_joystick = 5;
inline bool LejuHandPoseEvent::_internal_has_left_joystick() const {
  return this != internal_default_instance() && left_joystick_ != nullptr;
}
inline bool LejuHandPoseEvent::has_left_joystick() const {
  return _internal_has_left_joystick();
}
inline void LejuHandPoseEvent::clear_left_joystick() {
  if (GetArena() == nullptr && left_joystick_ != nullptr) {
    delete left_joystick_;
  }
  left_joystick_ = nullptr;
}
inline const ::protos::LejuHandPoseEvent_Joystick& LejuHandPoseEvent::_internal_left_joystick() const {
  const ::protos::LejuHandPoseEvent_Joystick* p = left_joystick_;
  return p != nullptr ? *p : *reinterpret_cast<const ::protos::LejuHandPoseEvent_Joystick*>(
      &::protos::_LejuHandPoseEvent_Joystick_default_instance_);
}
inline const ::protos::LejuHandPoseEvent_Joystick& LejuHandPoseEvent::left_joystick() const {
  // @@protoc_insertion_point(field_get:protos.LejuHandPoseEvent.left_joystick)
  return _internal_left_joystick();
}
inline void LejuHandPoseEvent::unsafe_arena_set_allocated_left_joystick(
    ::protos::LejuHandPoseEvent_Joystick* left_joystick) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(left_joystick_);
  }
  left_joystick_ = left_joystick;
  if (left_joystick) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:protos.LejuHandPoseEvent.left_joystick)
}
inline ::protos::LejuHandPoseEvent_Joystick* LejuHandPoseEvent::release_left_joystick() {
  auto temp = unsafe_arena_release_left_joystick();
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::protos::LejuHandPoseEvent_Joystick* LejuHandPoseEvent::unsafe_arena_release_left_joystick() {
  // @@protoc_insertion_point(field_release:protos.LejuHandPoseEvent.left_joystick)
  
  ::protos::LejuHandPoseEvent_Joystick* temp = left_joystick_;
  left_joystick_ = nullptr;
  return temp;
}
inline ::protos::LejuHandPoseEvent_Joystick* LejuHandPoseEvent::_internal_mutable_left_joystick() {
  
  if (left_joystick_ == nullptr) {
    auto* p = CreateMaybeMessage<::protos::LejuHandPoseEvent_Joystick>(GetArena());
    left_joystick_ = p;
  }
  return left_joystick_;
}
inline ::protos::LejuHandPoseEvent_Joystick* LejuHandPoseEvent::mutable_left_joystick() {
  // @@protoc_insertion_point(field_mutable:protos.LejuHandPoseEvent.left_joystick)
  return _internal_mutable_left_joystick();
}
inline void LejuHandPoseEvent::set_allocated_left_joystick(::protos::LejuHandPoseEvent_Joystick* left_joystick) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete left_joystick_;
  }
  if (left_joystick) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::GetArena(left_joystick);
    if (message_arena != submessage_arena) {
      left_joystick = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, left_joystick, submessage_arena);
    }
    
  } else {
    
  }
  left_joystick_ = left_joystick;
  // @@protoc_insertion_point(field_set_allocated:protos.LejuHandPoseEvent.left_joystick)
}

// .protos.LejuHandPoseEvent.Joystick right_joystick = 6;
inline bool LejuHandPoseEvent::_internal_has_right_joystick() const {
  return this != internal_default_instance() && right_joystick_ != nullptr;
}
inline bool LejuHandPoseEvent::has_right_joystick() const {
  return _internal_has_right_joystick();
}
inline void LejuHandPoseEvent::clear_right_joystick() {
  if (GetArena() == nullptr && right_joystick_ != nullptr) {
    delete right_joystick_;
  }
  right_joystick_ = nullptr;
}
inline const ::protos::LejuHandPoseEvent_Joystick& LejuHandPoseEvent::_internal_right_joystick() const {
  const ::protos::LejuHandPoseEvent_Joystick* p = right_joystick_;
  return p != nullptr ? *p : *reinterpret_cast<const ::protos::LejuHandPoseEvent_Joystick*>(
      &::protos::_LejuHandPoseEvent_Joystick_default_instance_);
}
inline const ::protos::LejuHandPoseEvent_Joystick& LejuHandPoseEvent::right_joystick() const {
  // @@protoc_insertion_point(field_get:protos.LejuHandPoseEvent.right_joystick)
  return _internal_right_joystick();
}
inline void LejuHandPoseEvent::unsafe_arena_set_allocated_right_joystick(
    ::protos::LejuHandPoseEvent_Joystick* right_joystick) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(right_joystick_);
  }
  right_joystick_ = right_joystick;
  if (right_joystick) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:protos.LejuHandPoseEvent.right_joystick)
}
inline ::protos::LejuHandPoseEvent_Joystick* LejuHandPoseEvent::release_right_joystick() {
  auto temp = unsafe_arena_release_right_joystick();
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::protos::LejuHandPoseEvent_Joystick* LejuHandPoseEvent::unsafe_arena_release_right_joystick() {
  // @@protoc_insertion_point(field_release:protos.LejuHandPoseEvent.right_joystick)
  
  ::protos::LejuHandPoseEvent_Joystick* temp = right_joystick_;
  right_joystick_ = nullptr;
  return temp;
}
inline ::protos::LejuHandPoseEvent_Joystick* LejuHandPoseEvent::_internal_mutable_right_joystick() {
  
  if (right_joystick_ == nullptr) {
    auto* p = CreateMaybeMessage<::protos::LejuHandPoseEvent_Joystick>(GetArena());
    right_joystick_ = p;
  }
  return right_joystick_;
}
inline ::protos::LejuHandPoseEvent_Joystick* LejuHandPoseEvent::mutable_right_joystick() {
  // @@protoc_insertion_point(field_mutable:protos.LejuHandPoseEvent.right_joystick)
  return _internal_mutable_right_joystick();
}
inline void LejuHandPoseEvent::set_allocated_right_joystick(::protos::LejuHandPoseEvent_Joystick* right_joystick) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete right_joystick_;
  }
  if (right_joystick) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::GetArena(right_joystick);
    if (message_arena != submessage_arena) {
      right_joystick = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, right_joystick, submessage_arena);
    }
    
  } else {
    
  }
  right_joystick_ = right_joystick;
  // @@protoc_insertion_point(field_set_allocated:protos.LejuHandPoseEvent.right_joystick)
}

// .protos.ItemMassForceRequest item_mass_force_request = 7;
inline bool LejuHandPoseEvent::_internal_has_item_mass_force_request() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  PROTOBUF_ASSUME(!value || item_mass_force_request_ != nullptr);
  return value;
}
inline bool LejuHandPoseEvent::has_item_mass_force_request() const {
  return _internal_has_item_mass_force_request();
}
inline const ::protos::ItemMassForceRequest& LejuHandPoseEvent::_internal_item_mass_force_request() const {
  const ::protos::ItemMassForceRequest* p = item_mass_force_request_;
  return p != nullptr ? *p : *reinterpret_cast<const ::protos::ItemMassForceRequest*>(
      &::protos::_ItemMassForceRequest_default_instance_);
}
inline const ::protos::ItemMassForceRequest& LejuHandPoseEvent::item_mass_force_request() const {
  // @@protoc_insertion_point(field_get:protos.LejuHandPoseEvent.item_mass_force_request)
  return _internal_item_mass_force_request();
}
inline void LejuHandPoseEvent::unsafe_arena_set_allocated_item_mass_force_request(
    ::protos::ItemMassForceRequest* item_mass_force_request) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(item_mass_force_request_);
  }
  item_mass_force_request_ = item_mass_force_request;
  if (item_mass_force_request) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:protos.LejuHandPoseEvent.item_mass_force_request)
}
inline ::protos::ItemMassForceRequest* LejuHandPoseEvent::release_item_mass_force_request() {
  auto temp = unsafe_arena_release_item_mass_force_request();
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::protos::ItemMassForceRequest* LejuHandPoseEvent::unsafe_arena_release_item_mass_force_request() {
  // @@protoc_insertion_point(field_release:protos.LejuHandPoseEvent.item_mass_force_request)
  _has_bits_[0] &= ~0x00000001u;
  ::protos::ItemMassForceRequest* temp = item_mass_force_request_;
  item_mass_force_request_ = nullptr;
  return temp;
}
inline ::protos::ItemMassForceRequest* LejuHandPoseEvent::_internal_mutable_item_mass_force_request() {
  _has_bits_[0] |= 0x00000001u;
  if (item_mass_force_request_ == nullptr) {
    auto* p = CreateMaybeMessage<::protos::ItemMassForceRequest>(GetArena());
    item_mass_force_request_ = p;
  }
  return item_mass_force_request_;
}
inline ::protos::ItemMassForceRequest* LejuHandPoseEvent::mutable_item_mass_force_request() {
  // @@protoc_insertion_point(field_mutable:protos.LejuHandPoseEvent.item_mass_force_request)
  return _internal_mutable_item_mass_force_request();
}
inline void LejuHandPoseEvent::set_allocated_item_mass_force_request(::protos::ItemMassForceRequest* item_mass_force_request) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(item_mass_force_request_);
  }
  if (item_mass_force_request) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(item_mass_force_request)->GetArena();
    if (message_arena != submessage_arena) {
      item_mass_force_request = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, item_mass_force_request, submessage_arena);
    }
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  item_mass_force_request_ = item_mass_force_request;
  // @@protoc_insertion_point(field_set_allocated:protos.LejuHandPoseEvent.item_mass_force_request)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace protos

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_protos_2fhand_5fpose_2eproto
