// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/hand_wrench_srv.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_protos_2fhand_5fwrench_5fsrv_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_protos_2fhand_5fwrench_5fsrv_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3012000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3012004 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_protos_2fhand_5fwrench_5fsrv_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_protos_2fhand_5fwrench_5fsrv_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[3]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_protos_2fhand_5fwrench_5fsrv_2eproto;
namespace protos {
class ItemMassForce;
class ItemMassForceDefaultTypeInternal;
extern ItemMassForceDefaultTypeInternal _ItemMassForce_default_instance_;
class ItemMassForceRequest;
class ItemMassForceRequestDefaultTypeInternal;
extern ItemMassForceRequestDefaultTypeInternal _ItemMassForceRequest_default_instance_;
class ItemMassForceResponse;
class ItemMassForceResponseDefaultTypeInternal;
extern ItemMassForceResponseDefaultTypeInternal _ItemMassForceResponse_default_instance_;
}  // namespace protos
PROTOBUF_NAMESPACE_OPEN
template<> ::protos::ItemMassForce* Arena::CreateMaybeMessage<::protos::ItemMassForce>(Arena*);
template<> ::protos::ItemMassForceRequest* Arena::CreateMaybeMessage<::protos::ItemMassForceRequest>(Arena*);
template<> ::protos::ItemMassForceResponse* Arena::CreateMaybeMessage<::protos::ItemMassForceResponse>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace protos {

enum ItemMassForceResponse_OperationStatus : int {
  ItemMassForceResponse_OperationStatus_SUCCESS = 0,
  ItemMassForceResponse_OperationStatus_ERROR = 1,
  ItemMassForceResponse_OperationStatus_TIMEOUT = 2,
  ItemMassForceResponse_OperationStatus_INVALID_REQUEST = 3,
  ItemMassForceResponse_OperationStatus_ItemMassForceResponse_OperationStatus_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::min(),
  ItemMassForceResponse_OperationStatus_ItemMassForceResponse_OperationStatus_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::max()
};
bool ItemMassForceResponse_OperationStatus_IsValid(int value);
constexpr ItemMassForceResponse_OperationStatus ItemMassForceResponse_OperationStatus_OperationStatus_MIN = ItemMassForceResponse_OperationStatus_SUCCESS;
constexpr ItemMassForceResponse_OperationStatus ItemMassForceResponse_OperationStatus_OperationStatus_MAX = ItemMassForceResponse_OperationStatus_INVALID_REQUEST;
constexpr int ItemMassForceResponse_OperationStatus_OperationStatus_ARRAYSIZE = ItemMassForceResponse_OperationStatus_OperationStatus_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ItemMassForceResponse_OperationStatus_descriptor();
template<typename T>
inline const std::string& ItemMassForceResponse_OperationStatus_Name(T enum_t_value) {
  static_assert(::std::is_same<T, ItemMassForceResponse_OperationStatus>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function ItemMassForceResponse_OperationStatus_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    ItemMassForceResponse_OperationStatus_descriptor(), enum_t_value);
}
inline bool ItemMassForceResponse_OperationStatus_Parse(
    const std::string& name, ItemMassForceResponse_OperationStatus* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<ItemMassForceResponse_OperationStatus>(
    ItemMassForceResponse_OperationStatus_descriptor(), name, value);
}
enum ItemMassForceOperation : int {
  GET = 0,
  SET = 1,
  ItemMassForceOperation_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::min(),
  ItemMassForceOperation_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::max()
};
bool ItemMassForceOperation_IsValid(int value);
constexpr ItemMassForceOperation ItemMassForceOperation_MIN = GET;
constexpr ItemMassForceOperation ItemMassForceOperation_MAX = SET;
constexpr int ItemMassForceOperation_ARRAYSIZE = ItemMassForceOperation_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ItemMassForceOperation_descriptor();
template<typename T>
inline const std::string& ItemMassForceOperation_Name(T enum_t_value) {
  static_assert(::std::is_same<T, ItemMassForceOperation>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function ItemMassForceOperation_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    ItemMassForceOperation_descriptor(), enum_t_value);
}
inline bool ItemMassForceOperation_Parse(
    const std::string& name, ItemMassForceOperation* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<ItemMassForceOperation>(
    ItemMassForceOperation_descriptor(), name, value);
}
// ===================================================================

class ItemMassForce PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:protos.ItemMassForce) */ {
 public:
  inline ItemMassForce() : ItemMassForce(nullptr) {};
  virtual ~ItemMassForce();

  ItemMassForce(const ItemMassForce& from);
  ItemMassForce(ItemMassForce&& from) noexcept
    : ItemMassForce() {
    *this = ::std::move(from);
  }

  inline ItemMassForce& operator=(const ItemMassForce& from) {
    CopyFrom(from);
    return *this;
  }
  inline ItemMassForce& operator=(ItemMassForce&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const ItemMassForce& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ItemMassForce* internal_default_instance() {
    return reinterpret_cast<const ItemMassForce*>(
               &_ItemMassForce_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(ItemMassForce& a, ItemMassForce& b) {
    a.Swap(&b);
  }
  inline void Swap(ItemMassForce* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ItemMassForce* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline ItemMassForce* New() const final {
    return CreateMaybeMessage<ItemMassForce>(nullptr);
  }

  ItemMassForce* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<ItemMassForce>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const ItemMassForce& from);
  void MergeFrom(const ItemMassForce& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ItemMassForce* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "protos.ItemMassForce";
  }
  protected:
  explicit ItemMassForce(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_protos_2fhand_5fwrench_5fsrv_2eproto);
    return ::descriptor_table_protos_2fhand_5fwrench_5fsrv_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kCaseNameFieldNumber = 1,
    kDescriptionFieldNumber = 2,
    kItemMassFieldNumber = 3,
    kLforceXFieldNumber = 4,
    kLforceYFieldNumber = 5,
    kLforceZFieldNumber = 6,
  };
  // string case_name = 1;
  void clear_case_name();
  const std::string& case_name() const;
  void set_case_name(const std::string& value);
  void set_case_name(std::string&& value);
  void set_case_name(const char* value);
  void set_case_name(const char* value, size_t size);
  std::string* mutable_case_name();
  std::string* release_case_name();
  void set_allocated_case_name(std::string* case_name);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_case_name();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_case_name(
      std::string* case_name);
  private:
  const std::string& _internal_case_name() const;
  void _internal_set_case_name(const std::string& value);
  std::string* _internal_mutable_case_name();
  public:

  // string description = 2;
  void clear_description();
  const std::string& description() const;
  void set_description(const std::string& value);
  void set_description(std::string&& value);
  void set_description(const char* value);
  void set_description(const char* value, size_t size);
  std::string* mutable_description();
  std::string* release_description();
  void set_allocated_description(std::string* description);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_description();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_description(
      std::string* description);
  private:
  const std::string& _internal_description() const;
  void _internal_set_description(const std::string& value);
  std::string* _internal_mutable_description();
  public:

  // double item_mass = 3;
  void clear_item_mass();
  double item_mass() const;
  void set_item_mass(double value);
  private:
  double _internal_item_mass() const;
  void _internal_set_item_mass(double value);
  public:

  // double lforce_x = 4;
  void clear_lforce_x();
  double lforce_x() const;
  void set_lforce_x(double value);
  private:
  double _internal_lforce_x() const;
  void _internal_set_lforce_x(double value);
  public:

  // double lforce_y = 5;
  void clear_lforce_y();
  double lforce_y() const;
  void set_lforce_y(double value);
  private:
  double _internal_lforce_y() const;
  void _internal_set_lforce_y(double value);
  public:

  // double lforce_z = 6;
  void clear_lforce_z();
  double lforce_z() const;
  void set_lforce_z(double value);
  private:
  double _internal_lforce_z() const;
  void _internal_set_lforce_z(double value);
  public:

  // @@protoc_insertion_point(class_scope:protos.ItemMassForce)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr case_name_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr description_;
  double item_mass_;
  double lforce_x_;
  double lforce_y_;
  double lforce_z_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_protos_2fhand_5fwrench_5fsrv_2eproto;
};
// -------------------------------------------------------------------

class ItemMassForceRequest PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:protos.ItemMassForceRequest) */ {
 public:
  inline ItemMassForceRequest() : ItemMassForceRequest(nullptr) {};
  virtual ~ItemMassForceRequest();

  ItemMassForceRequest(const ItemMassForceRequest& from);
  ItemMassForceRequest(ItemMassForceRequest&& from) noexcept
    : ItemMassForceRequest() {
    *this = ::std::move(from);
  }

  inline ItemMassForceRequest& operator=(const ItemMassForceRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline ItemMassForceRequest& operator=(ItemMassForceRequest&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const ItemMassForceRequest& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ItemMassForceRequest* internal_default_instance() {
    return reinterpret_cast<const ItemMassForceRequest*>(
               &_ItemMassForceRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(ItemMassForceRequest& a, ItemMassForceRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(ItemMassForceRequest* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ItemMassForceRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline ItemMassForceRequest* New() const final {
    return CreateMaybeMessage<ItemMassForceRequest>(nullptr);
  }

  ItemMassForceRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<ItemMassForceRequest>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const ItemMassForceRequest& from);
  void MergeFrom(const ItemMassForceRequest& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ItemMassForceRequest* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "protos.ItemMassForceRequest";
  }
  protected:
  explicit ItemMassForceRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_protos_2fhand_5fwrench_5fsrv_2eproto);
    return ::descriptor_table_protos_2fhand_5fwrench_5fsrv_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kDataFieldNumber = 2,
    kOperationFieldNumber = 1,
  };
  // .protos.ItemMassForce data = 2;
  bool has_data() const;
  private:
  bool _internal_has_data() const;
  public:
  void clear_data();
  const ::protos::ItemMassForce& data() const;
  ::protos::ItemMassForce* release_data();
  ::protos::ItemMassForce* mutable_data();
  void set_allocated_data(::protos::ItemMassForce* data);
  private:
  const ::protos::ItemMassForce& _internal_data() const;
  ::protos::ItemMassForce* _internal_mutable_data();
  public:
  void unsafe_arena_set_allocated_data(
      ::protos::ItemMassForce* data);
  ::protos::ItemMassForce* unsafe_arena_release_data();

  // .protos.ItemMassForceOperation operation = 1;
  void clear_operation();
  ::protos::ItemMassForceOperation operation() const;
  void set_operation(::protos::ItemMassForceOperation value);
  private:
  ::protos::ItemMassForceOperation _internal_operation() const;
  void _internal_set_operation(::protos::ItemMassForceOperation value);
  public:

  // @@protoc_insertion_point(class_scope:protos.ItemMassForceRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::protos::ItemMassForce* data_;
  int operation_;
  friend struct ::TableStruct_protos_2fhand_5fwrench_5fsrv_2eproto;
};
// -------------------------------------------------------------------

class ItemMassForceResponse PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:protos.ItemMassForceResponse) */ {
 public:
  inline ItemMassForceResponse() : ItemMassForceResponse(nullptr) {};
  virtual ~ItemMassForceResponse();

  ItemMassForceResponse(const ItemMassForceResponse& from);
  ItemMassForceResponse(ItemMassForceResponse&& from) noexcept
    : ItemMassForceResponse() {
    *this = ::std::move(from);
  }

  inline ItemMassForceResponse& operator=(const ItemMassForceResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline ItemMassForceResponse& operator=(ItemMassForceResponse&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const ItemMassForceResponse& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ItemMassForceResponse* internal_default_instance() {
    return reinterpret_cast<const ItemMassForceResponse*>(
               &_ItemMassForceResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(ItemMassForceResponse& a, ItemMassForceResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(ItemMassForceResponse* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ItemMassForceResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline ItemMassForceResponse* New() const final {
    return CreateMaybeMessage<ItemMassForceResponse>(nullptr);
  }

  ItemMassForceResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<ItemMassForceResponse>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const ItemMassForceResponse& from);
  void MergeFrom(const ItemMassForceResponse& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ItemMassForceResponse* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "protos.ItemMassForceResponse";
  }
  protected:
  explicit ItemMassForceResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_protos_2fhand_5fwrench_5fsrv_2eproto);
    return ::descriptor_table_protos_2fhand_5fwrench_5fsrv_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  typedef ItemMassForceResponse_OperationStatus OperationStatus;
  static constexpr OperationStatus SUCCESS =
    ItemMassForceResponse_OperationStatus_SUCCESS;
  static constexpr OperationStatus ERROR =
    ItemMassForceResponse_OperationStatus_ERROR;
  static constexpr OperationStatus TIMEOUT =
    ItemMassForceResponse_OperationStatus_TIMEOUT;
  static constexpr OperationStatus INVALID_REQUEST =
    ItemMassForceResponse_OperationStatus_INVALID_REQUEST;
  static inline bool OperationStatus_IsValid(int value) {
    return ItemMassForceResponse_OperationStatus_IsValid(value);
  }
  static constexpr OperationStatus OperationStatus_MIN =
    ItemMassForceResponse_OperationStatus_OperationStatus_MIN;
  static constexpr OperationStatus OperationStatus_MAX =
    ItemMassForceResponse_OperationStatus_OperationStatus_MAX;
  static constexpr int OperationStatus_ARRAYSIZE =
    ItemMassForceResponse_OperationStatus_OperationStatus_ARRAYSIZE;
  static inline const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor*
  OperationStatus_descriptor() {
    return ItemMassForceResponse_OperationStatus_descriptor();
  }
  template<typename T>
  static inline const std::string& OperationStatus_Name(T enum_t_value) {
    static_assert(::std::is_same<T, OperationStatus>::value ||
      ::std::is_integral<T>::value,
      "Incorrect type passed to function OperationStatus_Name.");
    return ItemMassForceResponse_OperationStatus_Name(enum_t_value);
  }
  static inline bool OperationStatus_Parse(const std::string& name,
      OperationStatus* value) {
    return ItemMassForceResponse_OperationStatus_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  enum : int {
    kItemMassForcesFieldNumber = 4,
    kDescriptionFieldNumber = 3,
    kOperationFieldNumber = 1,
    kStatusFieldNumber = 2,
  };
  // repeated .protos.ItemMassForce item_mass_forces = 4;
  int item_mass_forces_size() const;
  private:
  int _internal_item_mass_forces_size() const;
  public:
  void clear_item_mass_forces();
  ::protos::ItemMassForce* mutable_item_mass_forces(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::protos::ItemMassForce >*
      mutable_item_mass_forces();
  private:
  const ::protos::ItemMassForce& _internal_item_mass_forces(int index) const;
  ::protos::ItemMassForce* _internal_add_item_mass_forces();
  public:
  const ::protos::ItemMassForce& item_mass_forces(int index) const;
  ::protos::ItemMassForce* add_item_mass_forces();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::protos::ItemMassForce >&
      item_mass_forces() const;

  // string description = 3;
  void clear_description();
  const std::string& description() const;
  void set_description(const std::string& value);
  void set_description(std::string&& value);
  void set_description(const char* value);
  void set_description(const char* value, size_t size);
  std::string* mutable_description();
  std::string* release_description();
  void set_allocated_description(std::string* description);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_description();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_description(
      std::string* description);
  private:
  const std::string& _internal_description() const;
  void _internal_set_description(const std::string& value);
  std::string* _internal_mutable_description();
  public:

  // .protos.ItemMassForceOperation operation = 1;
  void clear_operation();
  ::protos::ItemMassForceOperation operation() const;
  void set_operation(::protos::ItemMassForceOperation value);
  private:
  ::protos::ItemMassForceOperation _internal_operation() const;
  void _internal_set_operation(::protos::ItemMassForceOperation value);
  public:

  // .protos.ItemMassForceResponse.OperationStatus status = 2;
  void clear_status();
  ::protos::ItemMassForceResponse_OperationStatus status() const;
  void set_status(::protos::ItemMassForceResponse_OperationStatus value);
  private:
  ::protos::ItemMassForceResponse_OperationStatus _internal_status() const;
  void _internal_set_status(::protos::ItemMassForceResponse_OperationStatus value);
  public:

  // @@protoc_insertion_point(class_scope:protos.ItemMassForceResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::protos::ItemMassForce > item_mass_forces_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr description_;
  int operation_;
  int status_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_protos_2fhand_5fwrench_5fsrv_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// ItemMassForce

// string case_name = 1;
inline void ItemMassForce::clear_case_name() {
  case_name_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& ItemMassForce::case_name() const {
  // @@protoc_insertion_point(field_get:protos.ItemMassForce.case_name)
  return _internal_case_name();
}
inline void ItemMassForce::set_case_name(const std::string& value) {
  _internal_set_case_name(value);
  // @@protoc_insertion_point(field_set:protos.ItemMassForce.case_name)
}
inline std::string* ItemMassForce::mutable_case_name() {
  // @@protoc_insertion_point(field_mutable:protos.ItemMassForce.case_name)
  return _internal_mutable_case_name();
}
inline const std::string& ItemMassForce::_internal_case_name() const {
  return case_name_.Get();
}
inline void ItemMassForce::_internal_set_case_name(const std::string& value) {
  
  case_name_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void ItemMassForce::set_case_name(std::string&& value) {
  
  case_name_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:protos.ItemMassForce.case_name)
}
inline void ItemMassForce::set_case_name(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  case_name_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:protos.ItemMassForce.case_name)
}
inline void ItemMassForce::set_case_name(const char* value,
    size_t size) {
  
  case_name_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:protos.ItemMassForce.case_name)
}
inline std::string* ItemMassForce::_internal_mutable_case_name() {
  
  return case_name_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* ItemMassForce::release_case_name() {
  // @@protoc_insertion_point(field_release:protos.ItemMassForce.case_name)
  return case_name_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void ItemMassForce::set_allocated_case_name(std::string* case_name) {
  if (case_name != nullptr) {
    
  } else {
    
  }
  case_name_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), case_name,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:protos.ItemMassForce.case_name)
}
inline std::string* ItemMassForce::unsafe_arena_release_case_name() {
  // @@protoc_insertion_point(field_unsafe_arena_release:protos.ItemMassForce.case_name)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return case_name_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void ItemMassForce::unsafe_arena_set_allocated_case_name(
    std::string* case_name) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (case_name != nullptr) {
    
  } else {
    
  }
  case_name_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      case_name, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:protos.ItemMassForce.case_name)
}

// string description = 2;
inline void ItemMassForce::clear_description() {
  description_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& ItemMassForce::description() const {
  // @@protoc_insertion_point(field_get:protos.ItemMassForce.description)
  return _internal_description();
}
inline void ItemMassForce::set_description(const std::string& value) {
  _internal_set_description(value);
  // @@protoc_insertion_point(field_set:protos.ItemMassForce.description)
}
inline std::string* ItemMassForce::mutable_description() {
  // @@protoc_insertion_point(field_mutable:protos.ItemMassForce.description)
  return _internal_mutable_description();
}
inline const std::string& ItemMassForce::_internal_description() const {
  return description_.Get();
}
inline void ItemMassForce::_internal_set_description(const std::string& value) {
  
  description_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void ItemMassForce::set_description(std::string&& value) {
  
  description_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:protos.ItemMassForce.description)
}
inline void ItemMassForce::set_description(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  description_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:protos.ItemMassForce.description)
}
inline void ItemMassForce::set_description(const char* value,
    size_t size) {
  
  description_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:protos.ItemMassForce.description)
}
inline std::string* ItemMassForce::_internal_mutable_description() {
  
  return description_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* ItemMassForce::release_description() {
  // @@protoc_insertion_point(field_release:protos.ItemMassForce.description)
  return description_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void ItemMassForce::set_allocated_description(std::string* description) {
  if (description != nullptr) {
    
  } else {
    
  }
  description_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), description,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:protos.ItemMassForce.description)
}
inline std::string* ItemMassForce::unsafe_arena_release_description() {
  // @@protoc_insertion_point(field_unsafe_arena_release:protos.ItemMassForce.description)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return description_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void ItemMassForce::unsafe_arena_set_allocated_description(
    std::string* description) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (description != nullptr) {
    
  } else {
    
  }
  description_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      description, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:protos.ItemMassForce.description)
}

// double item_mass = 3;
inline void ItemMassForce::clear_item_mass() {
  item_mass_ = 0;
}
inline double ItemMassForce::_internal_item_mass() const {
  return item_mass_;
}
inline double ItemMassForce::item_mass() const {
  // @@protoc_insertion_point(field_get:protos.ItemMassForce.item_mass)
  return _internal_item_mass();
}
inline void ItemMassForce::_internal_set_item_mass(double value) {
  
  item_mass_ = value;
}
inline void ItemMassForce::set_item_mass(double value) {
  _internal_set_item_mass(value);
  // @@protoc_insertion_point(field_set:protos.ItemMassForce.item_mass)
}

// double lforce_x = 4;
inline void ItemMassForce::clear_lforce_x() {
  lforce_x_ = 0;
}
inline double ItemMassForce::_internal_lforce_x() const {
  return lforce_x_;
}
inline double ItemMassForce::lforce_x() const {
  // @@protoc_insertion_point(field_get:protos.ItemMassForce.lforce_x)
  return _internal_lforce_x();
}
inline void ItemMassForce::_internal_set_lforce_x(double value) {
  
  lforce_x_ = value;
}
inline void ItemMassForce::set_lforce_x(double value) {
  _internal_set_lforce_x(value);
  // @@protoc_insertion_point(field_set:protos.ItemMassForce.lforce_x)
}

// double lforce_y = 5;
inline void ItemMassForce::clear_lforce_y() {
  lforce_y_ = 0;
}
inline double ItemMassForce::_internal_lforce_y() const {
  return lforce_y_;
}
inline double ItemMassForce::lforce_y() const {
  // @@protoc_insertion_point(field_get:protos.ItemMassForce.lforce_y)
  return _internal_lforce_y();
}
inline void ItemMassForce::_internal_set_lforce_y(double value) {
  
  lforce_y_ = value;
}
inline void ItemMassForce::set_lforce_y(double value) {
  _internal_set_lforce_y(value);
  // @@protoc_insertion_point(field_set:protos.ItemMassForce.lforce_y)
}

// double lforce_z = 6;
inline void ItemMassForce::clear_lforce_z() {
  lforce_z_ = 0;
}
inline double ItemMassForce::_internal_lforce_z() const {
  return lforce_z_;
}
inline double ItemMassForce::lforce_z() const {
  // @@protoc_insertion_point(field_get:protos.ItemMassForce.lforce_z)
  return _internal_lforce_z();
}
inline void ItemMassForce::_internal_set_lforce_z(double value) {
  
  lforce_z_ = value;
}
inline void ItemMassForce::set_lforce_z(double value) {
  _internal_set_lforce_z(value);
  // @@protoc_insertion_point(field_set:protos.ItemMassForce.lforce_z)
}

// -------------------------------------------------------------------

// ItemMassForceRequest

// .protos.ItemMassForceOperation operation = 1;
inline void ItemMassForceRequest::clear_operation() {
  operation_ = 0;
}
inline ::protos::ItemMassForceOperation ItemMassForceRequest::_internal_operation() const {
  return static_cast< ::protos::ItemMassForceOperation >(operation_);
}
inline ::protos::ItemMassForceOperation ItemMassForceRequest::operation() const {
  // @@protoc_insertion_point(field_get:protos.ItemMassForceRequest.operation)
  return _internal_operation();
}
inline void ItemMassForceRequest::_internal_set_operation(::protos::ItemMassForceOperation value) {
  
  operation_ = value;
}
inline void ItemMassForceRequest::set_operation(::protos::ItemMassForceOperation value) {
  _internal_set_operation(value);
  // @@protoc_insertion_point(field_set:protos.ItemMassForceRequest.operation)
}

// .protos.ItemMassForce data = 2;
inline bool ItemMassForceRequest::_internal_has_data() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  PROTOBUF_ASSUME(!value || data_ != nullptr);
  return value;
}
inline bool ItemMassForceRequest::has_data() const {
  return _internal_has_data();
}
inline void ItemMassForceRequest::clear_data() {
  if (GetArena() == nullptr && data_ != nullptr) {
    delete data_;
  }
  data_ = nullptr;
  _has_bits_[0] &= ~0x00000001u;
}
inline const ::protos::ItemMassForce& ItemMassForceRequest::_internal_data() const {
  const ::protos::ItemMassForce* p = data_;
  return p != nullptr ? *p : *reinterpret_cast<const ::protos::ItemMassForce*>(
      &::protos::_ItemMassForce_default_instance_);
}
inline const ::protos::ItemMassForce& ItemMassForceRequest::data() const {
  // @@protoc_insertion_point(field_get:protos.ItemMassForceRequest.data)
  return _internal_data();
}
inline void ItemMassForceRequest::unsafe_arena_set_allocated_data(
    ::protos::ItemMassForce* data) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(data_);
  }
  data_ = data;
  if (data) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:protos.ItemMassForceRequest.data)
}
inline ::protos::ItemMassForce* ItemMassForceRequest::release_data() {
  auto temp = unsafe_arena_release_data();
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::protos::ItemMassForce* ItemMassForceRequest::unsafe_arena_release_data() {
  // @@protoc_insertion_point(field_release:protos.ItemMassForceRequest.data)
  _has_bits_[0] &= ~0x00000001u;
  ::protos::ItemMassForce* temp = data_;
  data_ = nullptr;
  return temp;
}
inline ::protos::ItemMassForce* ItemMassForceRequest::_internal_mutable_data() {
  _has_bits_[0] |= 0x00000001u;
  if (data_ == nullptr) {
    auto* p = CreateMaybeMessage<::protos::ItemMassForce>(GetArena());
    data_ = p;
  }
  return data_;
}
inline ::protos::ItemMassForce* ItemMassForceRequest::mutable_data() {
  // @@protoc_insertion_point(field_mutable:protos.ItemMassForceRequest.data)
  return _internal_mutable_data();
}
inline void ItemMassForceRequest::set_allocated_data(::protos::ItemMassForce* data) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete data_;
  }
  if (data) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::GetArena(data);
    if (message_arena != submessage_arena) {
      data = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, data, submessage_arena);
    }
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  data_ = data;
  // @@protoc_insertion_point(field_set_allocated:protos.ItemMassForceRequest.data)
}

// -------------------------------------------------------------------

// ItemMassForceResponse

// .protos.ItemMassForceOperation operation = 1;
inline void ItemMassForceResponse::clear_operation() {
  operation_ = 0;
}
inline ::protos::ItemMassForceOperation ItemMassForceResponse::_internal_operation() const {
  return static_cast< ::protos::ItemMassForceOperation >(operation_);
}
inline ::protos::ItemMassForceOperation ItemMassForceResponse::operation() const {
  // @@protoc_insertion_point(field_get:protos.ItemMassForceResponse.operation)
  return _internal_operation();
}
inline void ItemMassForceResponse::_internal_set_operation(::protos::ItemMassForceOperation value) {
  
  operation_ = value;
}
inline void ItemMassForceResponse::set_operation(::protos::ItemMassForceOperation value) {
  _internal_set_operation(value);
  // @@protoc_insertion_point(field_set:protos.ItemMassForceResponse.operation)
}

// .protos.ItemMassForceResponse.OperationStatus status = 2;
inline void ItemMassForceResponse::clear_status() {
  status_ = 0;
}
inline ::protos::ItemMassForceResponse_OperationStatus ItemMassForceResponse::_internal_status() const {
  return static_cast< ::protos::ItemMassForceResponse_OperationStatus >(status_);
}
inline ::protos::ItemMassForceResponse_OperationStatus ItemMassForceResponse::status() const {
  // @@protoc_insertion_point(field_get:protos.ItemMassForceResponse.status)
  return _internal_status();
}
inline void ItemMassForceResponse::_internal_set_status(::protos::ItemMassForceResponse_OperationStatus value) {
  
  status_ = value;
}
inline void ItemMassForceResponse::set_status(::protos::ItemMassForceResponse_OperationStatus value) {
  _internal_set_status(value);
  // @@protoc_insertion_point(field_set:protos.ItemMassForceResponse.status)
}

// string description = 3;
inline void ItemMassForceResponse::clear_description() {
  description_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& ItemMassForceResponse::description() const {
  // @@protoc_insertion_point(field_get:protos.ItemMassForceResponse.description)
  return _internal_description();
}
inline void ItemMassForceResponse::set_description(const std::string& value) {
  _internal_set_description(value);
  // @@protoc_insertion_point(field_set:protos.ItemMassForceResponse.description)
}
inline std::string* ItemMassForceResponse::mutable_description() {
  // @@protoc_insertion_point(field_mutable:protos.ItemMassForceResponse.description)
  return _internal_mutable_description();
}
inline const std::string& ItemMassForceResponse::_internal_description() const {
  return description_.Get();
}
inline void ItemMassForceResponse::_internal_set_description(const std::string& value) {
  
  description_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void ItemMassForceResponse::set_description(std::string&& value) {
  
  description_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:protos.ItemMassForceResponse.description)
}
inline void ItemMassForceResponse::set_description(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  description_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:protos.ItemMassForceResponse.description)
}
inline void ItemMassForceResponse::set_description(const char* value,
    size_t size) {
  
  description_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:protos.ItemMassForceResponse.description)
}
inline std::string* ItemMassForceResponse::_internal_mutable_description() {
  
  return description_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* ItemMassForceResponse::release_description() {
  // @@protoc_insertion_point(field_release:protos.ItemMassForceResponse.description)
  return description_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void ItemMassForceResponse::set_allocated_description(std::string* description) {
  if (description != nullptr) {
    
  } else {
    
  }
  description_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), description,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:protos.ItemMassForceResponse.description)
}
inline std::string* ItemMassForceResponse::unsafe_arena_release_description() {
  // @@protoc_insertion_point(field_unsafe_arena_release:protos.ItemMassForceResponse.description)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return description_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void ItemMassForceResponse::unsafe_arena_set_allocated_description(
    std::string* description) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (description != nullptr) {
    
  } else {
    
  }
  description_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      description, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:protos.ItemMassForceResponse.description)
}

// repeated .protos.ItemMassForce item_mass_forces = 4;
inline int ItemMassForceResponse::_internal_item_mass_forces_size() const {
  return item_mass_forces_.size();
}
inline int ItemMassForceResponse::item_mass_forces_size() const {
  return _internal_item_mass_forces_size();
}
inline void ItemMassForceResponse::clear_item_mass_forces() {
  item_mass_forces_.Clear();
}
inline ::protos::ItemMassForce* ItemMassForceResponse::mutable_item_mass_forces(int index) {
  // @@protoc_insertion_point(field_mutable:protos.ItemMassForceResponse.item_mass_forces)
  return item_mass_forces_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::protos::ItemMassForce >*
ItemMassForceResponse::mutable_item_mass_forces() {
  // @@protoc_insertion_point(field_mutable_list:protos.ItemMassForceResponse.item_mass_forces)
  return &item_mass_forces_;
}
inline const ::protos::ItemMassForce& ItemMassForceResponse::_internal_item_mass_forces(int index) const {
  return item_mass_forces_.Get(index);
}
inline const ::protos::ItemMassForce& ItemMassForceResponse::item_mass_forces(int index) const {
  // @@protoc_insertion_point(field_get:protos.ItemMassForceResponse.item_mass_forces)
  return _internal_item_mass_forces(index);
}
inline ::protos::ItemMassForce* ItemMassForceResponse::_internal_add_item_mass_forces() {
  return item_mass_forces_.Add();
}
inline ::protos::ItemMassForce* ItemMassForceResponse::add_item_mass_forces() {
  // @@protoc_insertion_point(field_add:protos.ItemMassForceResponse.item_mass_forces)
  return _internal_add_item_mass_forces();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::protos::ItemMassForce >&
ItemMassForceResponse::item_mass_forces() const {
  // @@protoc_insertion_point(field_list:protos.ItemMassForceResponse.item_mass_forces)
  return item_mass_forces_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace protos

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::protos::ItemMassForceResponse_OperationStatus> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::protos::ItemMassForceResponse_OperationStatus>() {
  return ::protos::ItemMassForceResponse_OperationStatus_descriptor();
}
template <> struct is_proto_enum< ::protos::ItemMassForceOperation> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::protos::ItemMassForceOperation>() {
  return ::protos::ItemMassForceOperation_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_protos_2fhand_5fwrench_5fsrv_2eproto
