// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/robot_info.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_protos_2frobot_5finfo_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_protos_2frobot_5finfo_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3012000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3012004 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_protos_2frobot_5finfo_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_protos_2frobot_5finfo_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_protos_2frobot_5finfo_2eproto;
namespace protos {
class RobotDescription;
class RobotDescriptionDefaultTypeInternal;
extern RobotDescriptionDefaultTypeInternal _RobotDescription_default_instance_;
}  // namespace protos
PROTOBUF_NAMESPACE_OPEN
template<> ::protos::RobotDescription* Arena::CreateMaybeMessage<::protos::RobotDescription>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace protos {

// ===================================================================

class RobotDescription PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:protos.RobotDescription) */ {
 public:
  inline RobotDescription() : RobotDescription(nullptr) {};
  virtual ~RobotDescription();

  RobotDescription(const RobotDescription& from);
  RobotDescription(RobotDescription&& from) noexcept
    : RobotDescription() {
    *this = ::std::move(from);
  }

  inline RobotDescription& operator=(const RobotDescription& from) {
    CopyFrom(from);
    return *this;
  }
  inline RobotDescription& operator=(RobotDescription&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const RobotDescription& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const RobotDescription* internal_default_instance() {
    return reinterpret_cast<const RobotDescription*>(
               &_RobotDescription_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(RobotDescription& a, RobotDescription& b) {
    a.Swap(&b);
  }
  inline void Swap(RobotDescription* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(RobotDescription* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline RobotDescription* New() const final {
    return CreateMaybeMessage<RobotDescription>(nullptr);
  }

  RobotDescription* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<RobotDescription>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const RobotDescription& from);
  void MergeFrom(const RobotDescription& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(RobotDescription* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "protos.RobotDescription";
  }
  protected:
  explicit RobotDescription(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_protos_2frobot_5finfo_2eproto);
    return ::descriptor_table_protos_2frobot_5finfo_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kRobotNameFieldNumber = 1,
    kRobotVersionFieldNumber = 2,
  };
  // string robot_name = 1;
  void clear_robot_name();
  const std::string& robot_name() const;
  void set_robot_name(const std::string& value);
  void set_robot_name(std::string&& value);
  void set_robot_name(const char* value);
  void set_robot_name(const char* value, size_t size);
  std::string* mutable_robot_name();
  std::string* release_robot_name();
  void set_allocated_robot_name(std::string* robot_name);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_robot_name();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_robot_name(
      std::string* robot_name);
  private:
  const std::string& _internal_robot_name() const;
  void _internal_set_robot_name(const std::string& value);
  std::string* _internal_mutable_robot_name();
  public:

  // int32 robot_version = 2;
  void clear_robot_version();
  ::PROTOBUF_NAMESPACE_ID::int32 robot_version() const;
  void set_robot_version(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_robot_version() const;
  void _internal_set_robot_version(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // @@protoc_insertion_point(class_scope:protos.RobotDescription)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr robot_name_;
  ::PROTOBUF_NAMESPACE_ID::int32 robot_version_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_protos_2frobot_5finfo_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// RobotDescription

// string robot_name = 1;
inline void RobotDescription::clear_robot_name() {
  robot_name_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& RobotDescription::robot_name() const {
  // @@protoc_insertion_point(field_get:protos.RobotDescription.robot_name)
  return _internal_robot_name();
}
inline void RobotDescription::set_robot_name(const std::string& value) {
  _internal_set_robot_name(value);
  // @@protoc_insertion_point(field_set:protos.RobotDescription.robot_name)
}
inline std::string* RobotDescription::mutable_robot_name() {
  // @@protoc_insertion_point(field_mutable:protos.RobotDescription.robot_name)
  return _internal_mutable_robot_name();
}
inline const std::string& RobotDescription::_internal_robot_name() const {
  return robot_name_.Get();
}
inline void RobotDescription::_internal_set_robot_name(const std::string& value) {
  
  robot_name_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void RobotDescription::set_robot_name(std::string&& value) {
  
  robot_name_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:protos.RobotDescription.robot_name)
}
inline void RobotDescription::set_robot_name(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  robot_name_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:protos.RobotDescription.robot_name)
}
inline void RobotDescription::set_robot_name(const char* value,
    size_t size) {
  
  robot_name_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:protos.RobotDescription.robot_name)
}
inline std::string* RobotDescription::_internal_mutable_robot_name() {
  
  return robot_name_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* RobotDescription::release_robot_name() {
  // @@protoc_insertion_point(field_release:protos.RobotDescription.robot_name)
  return robot_name_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void RobotDescription::set_allocated_robot_name(std::string* robot_name) {
  if (robot_name != nullptr) {
    
  } else {
    
  }
  robot_name_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), robot_name,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:protos.RobotDescription.robot_name)
}
inline std::string* RobotDescription::unsafe_arena_release_robot_name() {
  // @@protoc_insertion_point(field_unsafe_arena_release:protos.RobotDescription.robot_name)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return robot_name_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void RobotDescription::unsafe_arena_set_allocated_robot_name(
    std::string* robot_name) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (robot_name != nullptr) {
    
  } else {
    
  }
  robot_name_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      robot_name, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:protos.RobotDescription.robot_name)
}

// int32 robot_version = 2;
inline void RobotDescription::clear_robot_version() {
  robot_version_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 RobotDescription::_internal_robot_version() const {
  return robot_version_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 RobotDescription::robot_version() const {
  // @@protoc_insertion_point(field_get:protos.RobotDescription.robot_version)
  return _internal_robot_version();
}
inline void RobotDescription::_internal_set_robot_version(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  robot_version_ = value;
}
inline void RobotDescription::set_robot_version(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_robot_version(value);
  // @@protoc_insertion_point(field_set:protos.RobotDescription.robot_version)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace protos

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_protos_2frobot_5finfo_2eproto
